### ISSUE TITLE
Add `submitting` to formState

### ISSUE THREAD

**Issue by fletcher91** [joepuzzo/informed#10]
Useful for displaying a loading indicator and greying out the submit.

**Comment by joepuzzo** [comment]
This would not be useful anymore because there is no asynchronous validation. The submission is now syncronous so it happens instantly. Then the developer. I.e you will make some sort of rest call with it or somthing

**Comment by joepuzzo** [comment]
Are we good with this issue? Can i close?

**Comment by fletcher91** [comment]
Validation yes, but `onSubmit` will probably call fetch, so it'll be async from there.

Calling `setState` on the form api in `onSubmit` will probably do the job, but I could imagine a lot of people needing such behaviour {if their onSubmit returns a promise}, so it seemed like an obvious addition.

If handling the return value of `onSubmit` if it is a promise is out-of-scope, it can be closed.

**Comment by joepuzzo** [comment]
Yup so i believe its out of scope. Informed gives you the values on submit and will ensure that onSubmit is only called with a valid form. It is not the responsibility once the form has been "submitted" of informed to take the inputed data and do something with it.
