### ISSUE TITLE
`setValue` and `setTouched` triggered for all fields in form

### ISSUE THREAD

**Issue by ramiyahya** [joepuzzo/informed#102]
I've created a [CodeSandbox](https://codesandbox.io/s/4xj7p8kz17) to make it easier to debug. 

I have two fields, `firstname` and `lastname`. I have a `FieldWrapper` component that wraps the text field and sets focus. I've simplified `FieldWrapper` for demonstration purposes. Anytime `setValue` or `setTouched` is triggered, it does so for all fields in the form instead of just the particular field that's triggering the actions. I've put in a `console.log` in FieldWrapper that shows this behaviour. 

<img width="624" alt="screen shot 2018-10-22 at 10 38 08 pm" src="https://user-images.githubusercontent.com/4978185/47315162-6da21f00-d64c-11e8-810d-0d7758ecb9a9.png">

**Comment by SergeyVoloshchuk** [comment]
Ye, I think it really problem. In highly loaded forms, this causes a freezing.

https://codesandbox.io/s/zn2q0r0yx

![1dpjeqcr0dp](https://user-images.githubusercontent.com/22756871/47483309-a0613880-d841-11e8-95ac-37c7fefb3241.gif)

**Comment by joepuzzo** [comment]
This should not be occurring as the internal components use pure components. I even show this off in the docs here https://joepuzzo.github.io/informed/?selectedKind=Gotchas&selectedStory=Unnecessary%20Rendering&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by joepuzzo** [comment]
Also its not in the docs but field wrapper still does exist in the lib just like it did in react form

**Comment by ramiyahya** [comment]
Thanks for your prompt response @joepuzzo ... I just refactored my `FieldWrapper` to use `Field` component from https://github.com/joepuzzo/informed/blob/master/src/components/Field.js but still having the same issue. Would you mind having a look at the [CodeSandbox](https://codesandbox.io/s/4xj7p8kz17) I created to see if you can spot anything I'm doing incorrectly.

**Comment by SergeyVoloshchuk** [comment]
@joepuzzo , It is not clear how to use this component `Field`. Could you help?

**Comment by joepuzzo** [comment]
V2 is out and highly optimized! So this should no longer be an issue!
