### ISSUE TITLE
Translation mechanism (Scope like) or expose Contexts

### ISSUE THREAD

**Issue by mathportillo** [joepuzzo/informed#103]
Hello,

Sorry for the vague issue title.

I want to implement a **Translate** feature that works just like Scopes do, but instead of prefixing values, errors, touched, etc.. It lets the user define translate methods that transform initial values from the source format to the form format.

The reason behind this is to be able to write extremely complex forms in a decoupled, organised, easily testable way.

My questions are:
- Would it be a good idea to have such mechanism? (detailed reasoning below)
- If not, what are better options? (I can be blind to some simples solutions)
- If yes, but its a too rare of a problem, could all of the Contexts (eg.: `import { FormContext, FieldContext, GroupContext, SelectContext } from 'informed'`) be exposed so I could import them and implement 

If it's probably a good idea, I could try to implement it, and if you think it's good enough, a PR.
Thanks a lot for the fine work!

--------------

Above is the TL;DR. The reasoning behind its usefulness is below:

Every form has to deal with one or both the challenges bellow:
- Prevent conforming source data (in this case an api response) to forms. My data format is only defined by the data itself
- Prevent me conforming the form to the data format. For example, in an api that responds a _json_ with 6 fields of information that could be easily edited by the user in a single masked text input, I wouldn't have to create 6 inputs.

The obvious way to solve this issue is to **translate** the data, to and from the form. But this has two common "problems":
- Who deals with translating? is it some kind of controller (e.g. Redux container)? if so, when I choose to change my form interface the controller would have to be aware of that change. Or is it the component itself? that parses the data that will be sent to the form `initialValues` and parses back the values sent with `onSubmit`.
- Wherever my translators are, if they are a single function for in and out I can't test them with as much granularity. And I still face the coupling problem where every form change would require an update in a the translate method aware of that field.
- A single function also doesn't let me reuse translations. For example, many entities in a my system have editable pictures, and all of them would require dealing with translation if I didn't separate it.

A `<Translator />` component would solve it all. Separate concerns for reusability, better tests. And a possible convention for defining relationships between forms and data good enough to enable each one to be designed without the other in mind.

**Comment by joepuzzo** [comment]
So this seems like something outside the scope of informed. Informed is designed to make it easy to create forms without state. Its up to the user of the lib to transform in and out of the form fields. If your backend domain model differs from the form thats fine and its probably because one is a data structure and the other is designed for a user. Im not sure how a transform component would aid in living with the lib.

**Comment by joepuzzo** [comment]
DATA FROM BACKEND ----> user defined transform function ( NOT in lib ) ---> initial form state ( user layout of data ----> SUBMIT ---> user defined transform function ---> Backend

**Comment by mathportillo** [comment]
So, do you think the contexts could be exposed for better customisation? I mean, exporting them in index.js.

I agree with the scope of the project, and with the flow you suggested. Thanks a lot.

**Comment by mathportillo** [comment]
Nevermind,
My idea wouldn't work because I couldn't use formApi to set values of fields never defined in the tree (because it never initializes the config of that field).
The compromise of going around this is too big. It is indeed much better if informed don't take care of this.
Thanks a lot.
