### ISSUE TITLE
Hooks support?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#105]
I assume that [React hooks](https://reactjs.org/docs/hooks-reference.html) is not something you can miss so easily so the question is imminent. Is Informed going to be hooked? :)

```js
const MyField = () => {
  const fieldApi = useFormField(fieldName, options)
  return <input /* you know the drill */ />
}
```

I think I would be even willing to contribute to this, because it's really exciting new world :)

Honestly, I am still forced to use `react-form` because lack of complete TypeScript definitions for Informed is a big stopgap for me. Hooks are definitely much easier to type.

**Comment by joepuzzo** [comment]
Oh yeah! However its still in Alpha so im not going to jump the gun :)

**Comment by FredyC** [comment]
Well, then you can have an alpha version of Informed as well :) It wouldn't be first, I am personally participating in making [MobX hooked](https://github.com/mobxjs/mobx-react/issues/588) and Apollo has some [experimental implementations](https://github.com/apollographql/react-apollo/issues/2539). Lastly, just by looking [at this list](https://nikgraf.github.io/react-hooks/) you can see how many people "jumped the gun" :)

**Comment by joepuzzo** [comment]
I plan on a rewrite with hooks and swaping out the underlying data structure with somthing more robust soon

**Comment by joepuzzo** [comment]
In progress!

**Comment by joepuzzo** [comment]
Update! Im getting real close to V2. The hooks optimize and simplify the hell out of informed! Keep an eye out

**Comment by FredyC** [comment]
@joepuzzo So with hooks officially out now how is it looking with V2? :)

**Comment by joepuzzo** [comment]
Almost Done!!! Just put out an issue with react about enzyme tests failing due to an update.. they are working on patch release now.. once thats in i need to make sure all the tests pass and write a changelog... also going to try to optimize bundle a little bit

**Comment by FredyC** [comment]
I see. Having similar issues with react-testing-library which are almost fixed by now. Looking forward to it.

**Comment by joepuzzo** [comment]
V2 Is out!!!!!!
