### ISSUE TITLE
Custom field validation

### ISSUE THREAD

**Issue by Gunthervg** [joepuzzo/informed#106]
Hello,

I've created a custom field according the docs: https://joepuzzo.github.io/informed/?selectedKind=CustomInputs&selectedStory=Creating%20Custom%20Inputs&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

But what if I want to move the validateOnBlur and validate method to the custom component? Can't find the solution to make it work.

**Comment by joepuzzo** [comment]
So one way would be to wrap your custom field one more time and pass them in there. Another would be to use the `<Field>` component 

```
const CustomField = (props) => {
  const validate = () => {...}
  return (
    <Field validateOnBlur validate={validate} {...props}>
       { ( { fieldApi, fieldState } ) =>
          <input> your code here!
       }
    <Field>
  )
}
```

**Comment by swarnakumar** [comment]
Is this still the recommended way? Where is the Field component exported from?

**Comment by joepuzzo** [comment]
Stand by

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?path=/story/custominputs--creating-custom-inputs Go to the heading labled `What if I want more control!?`
