### ISSUE TITLE
All inputs re-rendering even without validation.

### ISSUE THREAD

**Issue by timothyallan** [joepuzzo/informed#114]
Heya, I've got 25ish textfields in a Form in v1.10.9. Every time I enter anything in one of them, they all re-render, taking about 250-300ms per keystroke. 

I've checked the gotchas section about validation, and I've culled mine down so there's no validation, no external onChange/onBlur being passed in, no functions being created inline on any components etc. If I console.log in the `render()` of `<InformedTextField/>` I see a render for all 25 instances, every keystroke or blur.

My main class only has this in the `render()` function:
```
<Form>
  {({ formApi }) => (
  <React.Fragment>
	<InformedTextField
                    field="name"
                    label="Name"
                    initialValue=""
        />

... X 25 or so

 	<Button label="Add User" onClick={formApi.submitForm} disabled={this.busy} />
   </React.Fragment>
  )}
</Form>
```
`<InformedTextField/>` is a custom class which wraps the Material-UI TextField. It doesn't do any validation or setting of state and simply exports `export default asField(InformedTextField);` after setting the appropriate value and onChange/onBlur functions.

The change/blur functions of `<InformedTextField/>` are set on the TextField itself like:
```
onChange={this.handleChange}
onBlur={this.handleBlur}
```
and the functions are:

```
 handleChange = event => {
    this.props.fieldApi.setValue(event.target.value);
    //if (this.props.onChange) {
    //  this.props.onChange(event);
    // }
  };

  handleBlur = event => {
    this.props.fieldApi.setTouched(true);
    //if (this.props.onBlur) {
    //  this.props.onBlur(event);
    //}
  };
```

It's really not usable currently with all these form items, so I'm assuming I must be missing something. Any suggestions on what I could look at to prevent everything from re-rendering?

**Comment by joepuzzo** [comment]
Can u also post code for ur custom field

**Comment by timothyallan** [comment]
Sure thing
```

import TextField  from '@material-ui/core/TextField';
...
class InformedTextField extends React.Component {
  handleChange = event => {
    this.props.fieldApi.setValue(event.target.value);
    if (this.props.onChange) {
      this.props.onChange(event);
    }
  };

  handleBlur = event => {
    this.props.fieldApi.setTouched(true);
    if (this.props.onBlur) {
      this.props.onBlur(event);
    }
  };

  public render(): JSX.Element {
    const {
      field,
      fieldState,
      fieldApi,
      onChange,
      onBlur,
      initialValue,
      forwardedRef,
      className,
      setFocus,
      children,
      InputProps,
      validate,
      ...rest
    } = this.props;

    const { value, error } = fieldState;

    return (
      <TextField
        {...rest}
        value={!value && value !== 0 ? '' : value}
        onChange={this.handleChange}
        onBlur={this.handleBlur}
        error={!!error}
        helperText={error}
      />
    );
  }
}

export default asField(InformedTextField);
```

**Comment by khendrikse** [comment]
We've had the same problem and were only able to fix it by using shouldComponentUpdate :/ I think it is because of the HOC's. This seemed to be the only workaround.

**Comment by ramiyahya** [comment]
I've had similar issue when you're using a HOC or RenderProps that wraps a field. If you put a `shouldComponentUpdate(nextProps, nextState) {...}` in your wrapper and do an equality check `nextProps === this.props`, you'll notice that the `children` is always different. 

I did something like this to fix it. 

```
shouldComponentUpdate(nextProps, nextState) {
        if (
            nextProps.fieldState === this.props.fieldState &&
            nextState === this.state
        ) {
            return false;
        }
        return true;
}
```

**Comment by joepuzzo** [comment]
Eventually when i have more time im going use hooks instead of HOCs and hopefully these issues will be easier to debug/or non existent

**Comment by timothyallan** [comment]
Thanks all, looks like manual `shouldComponentUpdate` check is the only way to do it!

**Comment by joepuzzo** [comment]
Ok so I have completely rewritten informed from the ground up and its now highly optimized through the use of memoization and hooks! Check out V2 !!!
