### ISSUE TITLE
Possibility to reset only one field

### ISSUE THREAD

**Issue by khendrikse** [joepuzzo/informed#117]
Hi! 

I was wondering if it might be nice to have a more native option on informed to reset one specific field. Right now, in one of the projects I have we do this by specifically setting the values to, for example, an empty object.

I don't know if this is in scope, but I think it would really help all the workarounds. Especially since there is a `reset()`option. Or could it be possible to use this with some specifications for which field you want to use.

**Comment by joepuzzo** [comment]
Hmmm would you want it to reset to the initial values like the main reset function at the form level too.

**Comment by khendrikse** [comment]
Yeah just the same functionality, but then only on one field would be simply amazing.

**Comment by joepuzzo** [comment]
So im currently in the process of creating a V2 and will add this to the list

**Comment by joepuzzo** [comment]
Its in there!!!! I think i might have forgot to mention it in docs.. but you can totally call fieldApi.reset() now!!

**Comment by michael-mason** [comment]
Heya... I too would love to reset individual fields and not the entire form.
But there doesnt appear to be a fieldApi.reset() in v2 using the useFieldApi hook.

**Comment by joepuzzo** [comment]
There is! I may not have it documented but there is
