### ISSUE TITLE
Array validation

### ISSUE THREAD

**Issue by kneczaj** [joepuzzo/informed#119]
Hello,

I want to add a 'required` validator for an array. The array is dynamical so it is possible to add as many fields as possible. I want to force the array to have at least one value which is not an empty string, and ideally display the error below. Currently [1] shows validation per field of all array values, but it is not ideal. Such "required" validator would show the error under every field, and it seems the other displayed error messages does not disappear when one of the fields gets the value.

[1] https://joepuzzo.github.io/informed/?selectedKind=Validation&selectedStory=Complex%20Validation&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

A trial:
I checked out if a scope can have its validator so I can have a scope with one array, and validate it at scope level. Unfortunately not. 

Proposition:
Allow a validator to be assigned to array-level or at least scope level, so a scope with one array is possible.

**Comment by joepuzzo** [comment]
Hmm this is not as easy as you would think because an array is not a field in the eyes of informed. I am currently working on a V2 of this lib and will add this to the list of things to try to support.

**Comment by kneczaj** [comment]
Yes, I can imagine :D. I also have experience with development using Angular, they have quite complex support for forms. Take a look at FormGroup, FormArray and FormControl, they may inspire you a bit. 

Anyway I like there a fact that it is possible to add the validators not only to FormControl (the model for a field) but also to FormArray and FormGroup which have the value containing its the children' value, and validators have access to it. Together they form a kind of tree model with parent, and children.

https://angular.io/guide/reactive-forms

I hope that it is not a shame for react devs to get inspired with Angular :)

**Comment by joepuzzo** [comment]
Working on it

**Comment by joepuzzo** [comment]
Done!
