### ISSUE TITLE
Missing files for cloning repo and help with PRs

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#12]
Hi @joepuzzo I've cloned the repo and tried to do `npm start`

I've got this

<img width="903" alt="captura de pantalla 2018-06-26 a la s 20 03 55" src="https://user-images.githubusercontent.com/517228/41944000-2a72da9e-797c-11e8-8357-8d57cacb780e.png">

Can you add the missing files? I think I can help fixing bugs, etc. Cheers!

**Comment by joepuzzo** [comment]
npm run storybook ... not npm star

**Comment by joepuzzo** [comment]
Have you tried npm run storybook? can i close?

**Comment by jacargentina** [comment]
Yes, close

**Comment by joepuzzo** [comment]
Cool! thanks
