### ISSUE TITLE
What about async validation of multiple values?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#123]
This is something that seems to be missing in comparison to react-form. My use case is a form for entering credentials to 3rd party services. I want to be able to validate those so I can write those to a database on submit. 

It appears it's not even possible to validate synchronously across multiple fields? I mean if some field validation relies on value from another field, eg. require text value only if a radio group has a particular value. I just don't see such options in a current api and that's a pity.

**Comment by joepuzzo** [comment]
This is totally doable! Just use the HOCs to get access to other fields values.

**Comment by FredyC** [comment]
Ok, that would work I suppose, but it feels somewhat awkward. I mean if I have to run the validation within a specific field. For example, I have 3 related fields, all have to be filled in and then one of those fields would execute async validation? How I would decide which field is the controlling one? In the case of validation over the whole form, there is no doubt and it's less hidden.

I can understand you are trying to keep API minimal which is totally cool, but it seems that for some cases the Informed is not such a great choice, unfortunately.

**Comment by joepuzzo** [comment]
You are never interacting with more than one field at once. So its obvious what field is the “controlling one”. Sometimes two fieds are related such as pssword and confirm password. But coding that is simple. When u type in password it calls its validation which checks against password rules and the confirmation field. When uou type in the confirm password it does the same. Now if you want other fields to revalidate there is a solution for that too in the docs. See notifications under validation.

**Comment by FredyC** [comment]
Confirm password scenario is easy, no doubt there. It's synchronous also. I have 3 related fields and once all of those are filled (sync validation passes) I need to run async validation to verify these before a form is submitted.  On top of that, I want auto to submit onChange (with some timeout).

Obviously, setting the same async validation on every one of those fields is not a good idea, I don't want to run the verification process 3 times. Sure, I could have some throttling there to limit to only one request, but then it's getting awkward again as I need to pass the result to remaining 2 fields somehow.

I am thinking to have some hidden field for async validation purposes only and reach all form values through the HOC (_looking forward to hooks approach_). It does feel right either, too much hidden inside and not apparent at a first glance.

So, in the end, I guess I will just use sync validation to ensure all fields are valid and take care of async verification in `onSubmit`. It means I have to take care of `isSubmitting` on my own and display results outside of the form scope. Oh well, trade-offs everywhere :)

**Comment by joepuzzo** [comment]
Ok so we decided to remove async validation in V2 as it heavily complicates the lib. But TBH V2 will still be the most powerful form lib you have used! Go check out the docs !
