### ISSUE TITLE
Multiple Select with Checkbox Example

### ISSUE THREAD

**Issue by benbkk** [joepuzzo/informed#124]
Hi,
Thanks for this work, appreciate and learned from it.
I just got confused when it comes to work with checkboxes it seems like only boolean allowed in there. 

Is there a way to create multiple select with with a group of checkboxes that can have same 'name' attribute as any other form elements. But instead of single value, this group of checkbox will return array of values that are checked (that is other than boolean)

So exactly the example of multi-select, but instead of select, it's checkboxes. Is #there a way? 

#Thanks

**Comment by joepuzzo** [comment]
You would have to try to make a custom field for that. See the custom field section of docs

**Comment by benbkk** [comment]
Hi Joe! Thanks for the quick response

Yea actually I just realised that checkboxes are only giving booleans. How years of doing this and until just know 🤔
Anyway, sorry for this. so yes trying css hacking first & the custom later.
You could actually or I will come up with something and post it here up to you ok.

Thanks, 
Ben

**Comment by joepuzzo** [comment]
Hey V2 was just released!! go check it out !!

**Comment by brian-kilpatrick** [comment]
@joepuzzo Does V2 include a native solution to this?

**Comment by joepuzzo** [comment]
Not native no
