### ISSUE TITLE
Unable to remove exact objects from array with index? Can u please help me?? Basically adding and removing values from Array?

### ISSUE THREAD

**Issue by reddybashanaguru** [joepuzzo/informed#125]
Removing objects from the Arrays with array index

**Comment by joepuzzo** [comment]
Working on support for this in V2

**Comment by reddybashanaguru** [comment]
> Working on support for this in V2
 I'm already using this, So facing issues. May i know when we are getting V2

**Comment by joepuzzo** [comment]
V2 is out!!!

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?selectedKind=Arrays&selectedStory=Dynamic%20Arrays&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
