### ISSUE TITLE
Mask function changes caret position

### ISSUE THREAD

**Issue by kallaspriit** [joepuzzo/informed#126]
When the input mask function changes the value, the caret (cursor position) is moved to the end of the input but should remain the same.

**To replicate consider the following simple text input:**
```typescript
<Text field="name" id="name" mask={name => name.toUpperCase()}/>
```

Try writing something in the input, then move the caret somewhere in the middle/beginning of the text and then try to modify the text (type something new in the middle of existing text).

**What should happen:** entered text should become uppercase but the caret should remain at the position of writing.

**What actually happens:** entered text becomes uppercase but the caret is reset to the end of the input.

*Tested on latest Chrome.*

**Comment by joepuzzo** [comment]
Hey sorry i'm just getting back to this issue. I have been working on V2 for the past month. umm this is a good issue and i'm not sure how to solve it atm.. need to put my brain on it

**Comment by joepuzzo** [comment]
I did it! in V2 there will be a `maintainCursor` prop you can optionally pass in!

**Comment by kallaspriit** [comment]
Very good, but I've got a few issues

1. is there any reason why the `maintainCursor` would not be enabled by default?
2. The `maintainCursor` attribute seems to be missing from the typings (typings file says "Type definitions for informed 1.4.0").
3. The value passed to `mask` function is `undefined` for empty value (try adding some text and then deleting it). I'm expecting it to always be a string and that's also what the typings say. Somehow this works without errors in [storybook](https://joepuzzo.github.io/informed/?selectedKind=Formatting&selectedStory=Mask&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel), not sure what's going on.
