### ISSUE TITLE
JSON.parse(JSON.stringify(...))

### ISSUE THREAD

**Issue by peternoordijk** [joepuzzo/informed#128]
I was just looking through the code at <https://github.com/joepuzzo/informed/blob/master/src/Controller/FormController.js> and I found _a lot_ of lines encoding/decoding the state to JSON. This feels like super bad practice to me... Is this just to make a copy of the object? I will make a PR if that's the case replacing those to `Object.assign` or something. However I'm not sure if I'm missing something here.

**Comment by joepuzzo** [comment]
Gone !!! Go get V2!!
