### ISSUE TITLE
Document return values of API methods

### ISSUE THREAD

**Issue by PatrickLerner** [joepuzzo/informed#130]
For example in https://joepuzzo.github.io/informed/?selectedKind=Form&selectedStory=Api&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel, there are methods such as 'submitForm', where it is completely unclear what it returns, which makes using it rather inconvenient.

**Comment by joepuzzo** [comment]
It does not return anything ? It submits the form. I guess i could add col to table for return values but the description should be clear

**Comment by PatrickLerner** [comment]
I think it is not at all clear, a reasonable expectation would be for it to return either

a) true/false if the submit was successful
or
b) a promise which resolves/fails with the result of the attempt to submit the form

In case of submitForm it turns out it is the first option it seems

**Comment by joepuzzo** [comment]
Hmm i dont think i agree. The submit button is the dynimic way of submitting the form ( alternative to the submit button ). The responsibility of what to do if form succeeds or fails should exist in the samr place regardless of if the form was submitted with button or this function.
