### ISSUE TITLE
Form refusing to submit

### ISSUE THREAD

**Issue by m1ch34lj0hns0n** [joepuzzo/informed#131]
Has anyone ever come across an issue where `<Form />` is refusing to submit to it's given action? I am able to submit the form using vanilla JavaScript therefore bypassing informed submitForm() but if I rely purely on informed to submit to the given action nothing happens.

Checking formstate on submit doesn't provide any validation errors or other clues as to what the issue is.

**Comment by joepuzzo** [comment]
Wait a second.. are u trying to do an old fashioned form submission?? You have method and url props on there

**Comment by joepuzzo** [comment]
If thats the case then thats your problem. Bu default informed is designed so the user can call a post using whatever library they want in the onSubmit function.. i.e using somthing like axios. If u want old school submission you need to pass in the “dontPreventDefault” prop.. see docs for details

**Comment by m1ch34lj0hns0n** [comment]
Understood, thanks. Feel free to close :)
