### ISSUE TITLE
TypeScript ... again

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#133]
Looks like this has escaped V2 release, that's kinda a pity, was looking forward getting hooked & informed :)

**Comment by joepuzzo** [comment]
I dont do typescript lol, other people maintain that and when they added it i told them i was not going to maintain it lol. Eventually i will but for now you are more than welcome to update the type files and create a PR

**Comment by FredyC** [comment]
Well, and who are those people? Can you ping them in here? You could have pinged them before releasing V2 to make things smoother. Oh well. I would love to help, but I have too much on my plate right now.

**Comment by joepuzzo** [comment]
Ha yeah sorry im not sure. Typescript is on my list of things to support but it simply is not required for most people atm. Again i will take this on soon enough but I also have to much on my plate to worry about types right now. I can go back and see who originally added the types. but for now stand by.

**Comment by JaffParker** [comment]
Hi there, I submitted the original typescript file. Right right now I do not have time, unfortunately, to update it with the latest API's (in fact I'm only reading about them now lol), but I'll try to put time into that soon. You could also make edits on your local installation and later submit it!
