### ISSUE TITLE
Warning: Invalid value for prop `render` on <form> tag

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#135]
Attached stack trace. Latest version.

<img width="1401" alt="captura de pantalla 2019-02-08 a la s 15 09 12" src="https://user-images.githubusercontent.com/517228/52496980-a5a97f80-2bb3-11e9-8eb2-3696a0ba429c.png">

**Comment by joepuzzo** [comment]
Thanks i may have forgot to take that off. I will update and release new version

**Comment by jacargentina** [comment]
I've updated the PR with new errors (thanks `npm run test`) for `validate` and `component`
