### ISSUE TITLE
useFieldState: when form uses prop "initialValues", fieldState.value is not getting its value but undefined

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#137]
Hey, trying the new version with hooks! But there is this bug.

**Comment by joepuzzo** [comment]
The initial value is not part of the field state.

**Comment by jacargentina** [comment]
Sorry, maybe it is not very well written. Changing title

**Comment by joepuzzo** [comment]
Ok this sounds like it could be bug i will look into it

**Comment by alaycock** [comment]
Not sure what @jacargentina's exact issue is, but here's an issue that I'm running into.
See the demo here: https://codesandbox.io/s/0vxom6ynop

When using `initialValues` on the `<Form>` component, on the first render,`fieldState.value` is `undefined`. It then re-renders immediately after with the `fieldState.value` being the correct value. 

The is causing a visual bug for me because it's flipping from an empty state to a completed state, which is triggering an animation. I would expect `fieldState.value` to be the correct value on the first render.

**Comment by joepuzzo** [comment]
So this is an order of operations issue. One of the great features of informed is that it allows you to use fields without a `<Form>` element. In other words a `<Text>` field will still work when not in the context of a `<Form>`. Now this does come with a side affect.

When the `<Text>` field renders, it will render itself and then, in a `useEffect` will register itself with the `<Form>` IF a `<Form>` exists. 

Next the form will see if the user passed in any form level initial values and populate that value ( triggering that second render ). ATM im not sure how to solve that / if this is a bug or not. 

For now you can pass the initial value at the field level if its really a big issue. BUT that being said i will start to think of a solve!

**Comment by alaycock** [comment]
That's fair, thanks for the response @joepuzzo. I applied the `initialValue` prop to the field directly and it now only runs the render function a single time, so that sounds like a sensible workaround.

**Comment by joepuzzo** [comment]
Yeah for now.. i may be able to do some magic and have the field attempt to register in the "constructor" haha

**Comment by joepuzzo** [comment]
The field now registers in the "constructor"!

**Comment by huykon** [comment]
> That's fair, thanks for the response @joepuzzo. I applied the `initialValue` prop to the field directly and it now only runs the render function a single time, so that sounds like a sensible workaround.

in my case the initialValue is changing but not saving. I know it's define on constructor, how I can change the initivalue of show the value to the front-end?

**Comment by joepuzzo** [comment]
The initial value does show in the front end ?
