### ISSUE TITLE
When initializing a form with initialValues, change event is firing, and dirty = true

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#138]
Feature request: add a property at form state level to know when user edited provided values (via initialvalues)

**Comment by joepuzzo** [comment]
So i went back and forth on this one. I call it dirty when there are values entered. But maybe it should not be for initial values.. i need to think about this and get back to you

**Comment by Jakobo** [comment]
Unfortunately, changing the `dirty` behavior would be a breaking change and push `informed` to v3. That's not itself terrible, but folks are just getting converted from v1 to v2.

As a non-breaking change, what do you think about passing the `initialValues` down to their matching fields? This would let you use hooks as a backwards compatible workaround:

```jsx
import React from 'react';
import { Text, useFieldState } from 'informed';

const MyText = ({field, ...props}) => {
  const fs = useFieldState(field);
  // fs.dirty == field is no longer a blank field (current behavior)
  if (fs.value != fs.initialValue) {
    // fs.initialValue is a new property of the fieldState, used to get
    // the original "initial value", no matter if it was passed in at the form or field
    // level. Inside this if,  field was changed form its initial value (desired behavior)
  }

  return (<Text field={field} {...props} />);
};

const MyForm = () => (<Form initialValues={{name: 'joe'}}>
  <MyText field="name" />
</Form>);
```

**Comment by jacargentina** [comment]
That way I must create my own editors that way? 😞

What do you think about instead adding a new field different from dirty, which would be true only when any field value was changed from it's initial value provided on form setup?

**Comment by Jakobo** [comment]
That would be better. Any thoughts on naming? Going along with the idea of a new field (different from dirty) could be `isInitialValue` then. It would be `true` if the value matches the initial value, and available in `fieldState`. I'm happy to try a PR this weekend and see what it looks like in code.

**Comment by jacargentina** [comment]
@Jakobo i was thinking of 'hasChanges', but at formState, not fieldState

I want to for example avoid sending values to save via an API when there is not the need (because user didn't edit anything)

**Comment by Jakobo** [comment]
@jacargentina took your thoughts and rolled it up into a proposed PR @ #151. I went with `initial` for the `fieldState` name since informed uses one-word descriptors for the form state (`dirty`, `pristine`, `invalid`, etc).

**Comment by Jakobo** [comment]
Just an update on this issue. After some discussion in pr #151, we are mirroring the `touched` pattern in #171. It provides the same kind of functionality of an `initial` prop, but in a less hacky way. A dozen thanks to @joepuzzo for his guidance in finding the best way to address this issue.

**Comment by jacargentina** [comment]
@joepuzzo any progress on this?

**Comment by jacargentina** [comment]
@joepuzzo A year later! Can i help somehow with this ?

**Comment by joepuzzo** [comment]
Try in V4!
