### ISSUE TITLE
Dynamic fields are linked on index rather than field name

### ISSUE THREAD

**Issue by fletcher91** [joepuzzo/informed#14]
When using dynamic fields, the position of the field seems to be used in the identity of the field, which leads to unexpected behaviour of the fields being linked in value. [Replicated in sandbox](https://codesandbox.io/s/m3qz2qv4l8)

Reversing the order of the fields in group A does not lead to the behaviour.

**Comment by joepuzzo** [comment]
Im having trouble loading the sandbox for some reason.. but make sure the `key=` is unique on your field

**Comment by joepuzzo** [comment]
I loaded it and this is not happening to me "Both fields are now linked, any text entered will appear in both fields"

**Comment by fletcher91** [comment]
Adding `key` properties works, thanks for the fix!

It does seem weird that `key`s are required, since they're ordinary react components (not arrays).

P.s. I accidentally saved the patched version (with `email` field in the second position in the 'A' case), corrected now.

**Comment by joepuzzo** [comment]
Cool Awesome so i can close? And yea React will try to optimize and whenever you have dynamic elements array or not array you can and prob will run into this issue :)

**Comment by fletcher91** [comment]
Nice to keep in mind for later cases :+1:
