### ISSUE TITLE
QA: reset errors on input change

### ISSUE THREAD

**Issue by reinfi** [joepuzzo/informed#142]
Hi,

first of all: thanks for this great form library!

Second, I have two question I try to figure out, but old issues and storybook does not help that much.

1. I have server side validation for my form which I would not like to transform into javascript at the moment as it requires database access and more. I could easily set the server side errors in the componentDidMount method. Now I would like to reset the form error when a field gets changed/touched. Is there another easy way than implementing an onChange handler for every input? Or should I providate a validation function which always returns true?

2. Is there a way to support required values via html required attribute?

Thanks.

**Comment by joepuzzo** [comment]
So both the methods you describe above will work. This is an unfortunate side affect to setting errors directly using the API. There is nothing wrong with doing this! However you need to "teach" your form to clear it out when the user types. I guess however... i could look into adding some type of field to clear the errors when there is no validation function passed... maybe somthing like 'clearErrorOnChange'.
