### ISSUE TITLE
How to reset the formstate values ??

### ISSUE THREAD

**Issue by reddybashanaguru** [joepuzzo/informed#144]
How to reset total  formState  values to another set of values??

**Comment by Jakobo** [comment]
Hey @reddybashanaguru. This is straightforward with Informed `^2.0.0`. Inside of your form, you can use the new `useFormApi` hook to change your set of values.

[This Example](https://joepuzzo.github.io/informed/?selectedKind=Hooks%21&selectedStory=useFormApi) shows how to do it. In the example's case, it's updating a single field to a new value in response to a user click, but it could easily be extended to change all of the form's values.

[Here's the full form API](https://joepuzzo.github.io/informed/?selectedKind=Form&selectedStory=Api), which would also allow you to manipulate the form's `errors`, and `touched` properties.

**Comment by joepuzzo** [comment]
Ok so good news! I just released V2.0.3 which added back `setValues` so when you reset you can also then call `setValues`. to set your new values!

**Comment by joepuzzo** [comment]
Closing as this is now achievable.
