### ISSUE TITLE
Custom error messages per field

### ISSUE THREAD

**Issue by blakeyoder** [joepuzzo/informed#146]
I have a form that needs to have field level custom validation. Is there a way in the validation API to have 1) an array that contains all errors with custom messages and 2) a way to notify the field that its invalid, such that I could, for example, highlight the input red if there is an error.

Example code below:
```
  render = () => {
    const {settings} = this.props;
    return (
      <React.Fragment>
        <div className="settings__container">
          <Form
            initialValues={({settings})}
            onSubmit={(formState) => this.save(formState)}
            render={({formState, formApi}) => (
              <React.Fragment>
                {this.renderErrors(formApi)}
                <div className="form-group">
                  <label>
                    Footer:
                    <Text
                      validate={basicValidation}
                      className="input-control"
                      field="settings.footerText"/>
                  </label>
                </div>
                <div className="form-group">
                  <label>
                    Company Info:
                    <Text
                      validate={basicValidation}
                      className="input-control"
                      field="settings.companyInfo"/>
                  </label>
                </div>
                <Button
                  type="submit">
                  Submit
                </Button>
              </React.Fragment>
            )}
          />
        </div>
      </React.Fragment>
    );
  }
```

When the form is posted I get an error object of the form `{"footerText": "Input must not be empty"}` via `formApi.getError('setting')` However, I'd like to hook into the API such that it would return an array of the form `[Footer must not be empty]`. This creates an easier UI for user feedback. This might be beyond the scope of the project since I need custom, field level validation and notification.

This might be able to be accomplished if the `validate` callback took a variable number of arguments. That way I could pass it a custom `key` value for the error object.

**Comment by joepuzzo** [comment]
So i would recomend checking out the custom field part of the docs. It is very easy to flag/notify/highlight a field that fails validation.

**Comment by blakeyoder** [comment]
Thanks @joepuzzo, checking it out now :)
