### ISSUE TITLE
Cannot read property 'keepState' of undefined

### ISSUE THREAD

**Issue by Jucesr** [joepuzzo/informed#147]
It seems like with the 2V you added a new property called 'keepState'.

When I unmount a component that uses the Form component I get the following error message.

> Uncaught TypeError: Cannot read property 'keepState' of undefined
>     at FormController.deregister (index.js?5725:4461)
>     at eval (index.js?5725:5038)
 
Here my code.

```js
// PARENT COMPONENT
toogleForm = () => {
    this.setState((prevState) => ({
      form_open: !prevState.form_open
    }))
  }

render(){
  return {this.state.form_open && <EstimateForm/> }
}


// COMPONENT THAT USES FORM

const EstimateForm = (props) => {
  return (
    <Form
      className='Modal_form'
    >
      <Text field='code' />

      <div className="Modal_form_section">
        <button className="Modal_form_submit" type="submit">
          Guardar
        </button>
      </div>
      
  </Form>
  )
}

```

**Comment by joepuzzo** [comment]
Hmm im not seeing this issue in this code sandbox https://codesandbox.io/s/5v5nxxrvn

**Comment by joepuzzo** [comment]
What version of informed are you using

**Comment by Jucesr** [comment]
I upload the complete component here. 

https://codesandbox.io/s/4qm31528m9

**Comment by joepuzzo** [comment]
Ok so the bigest issue i see is that your not creating a custom input correctly. You cant use informeds `Text` field within `asField` because then your getting duplicate inputs. You can however! use `BasicText` which will work. I bet thats your issue

**Comment by joepuzzo** [comment]
In other words if you opened the source code for informeds `Text` you would see that its wrapped in `asField`. The `BasicText` is not! therefore what your code is doing is creating two fields with the same name causing informed to freak out because it does this: 1. Deregister the field `code` 2. Deregister the field `code`.. "AHHH THERE IS IS FIELD CODE" :)

**Comment by sushmitg** [comment]
I am getting the same error. created a custom field using react-select library. the error occurs when route changes.

**Comment by joepuzzo** [comment]
Create a code sandbox. Prob doing something similar.
