### ISSUE TITLE
Reset form state with <button type="reset"/>

### ISSUE THREAD

**Issue by mielecmichal** [joepuzzo/informed#148]
What do you think about idea to reset the form with a ```<button type="reset">``` [HTML Specification](https://www.w3.org/TR/html52/sec-forms.html#element-statedef-input-reset) Similarly like we do with submit? 

Currently when we place that kind of button in informed form. Inputs are cleared but other form state is not changed and errors for instance are visible.

**Comment by joepuzzo** [comment]
Umm it should fully reset the form.. 

```
<form
              {...rest}
              onReset={this.controller.reset}
              onSubmit={this.controller.submitForm}>
```

Thats the source code that hooks it up for you

**Comment by joepuzzo** [comment]
You can find that code here https://github.com/joepuzzo/informed/blob/master/src/components/Form.js#L70

**Comment by mielecmichal** [comment]
Ok, now I checked it again and the problem is related with a flag ```validateOnBlur```. When this flag is set, it looks onBlur logic is called for all the inputs after reset button click. 

Example:
```javascript
import React, {useState} from "react";
import {Form, Text} from "informed";

export const CarForm = () => {

    const [formState, setFormState] = useState({});
    const [car, setCar] = useState({name: "BMW"});

    const {errors = {name: []}} = formState;

    return (
        <div>
            <h1>{car.name}</h1>
            <Form onSubmit={car => setCar({...car})} onChange={setFormState}>
                <Text validate={(value = "") => value.length ===0 ? "Cannot be empty" : ""} field={"name"} validateOnBlur/>
                <p style={{color: "red"}}>{JSON.stringify(errors.name)}</p>
                <button type={"submit"}>Submit</button>
                <button type={"reset"}>Reset</button>
            </Form>
        </div>
    )
};
```

The form behavior is weird in my opinion. Try to click "Reset" few times for example.

**Comment by joepuzzo** [comment]
One thing is you really should not have that `setFormState` function.. that defeats the purpose of this lib completely haha. If you want to do anything with the form state.. use the hooks `useFormState` or `useFormApi`. In terms of the reset issue i dont have any logic that will blur all the fields on reset..  only on submit. This should not be happening.

**Comment by joepuzzo** [comment]
closing as this does not seem to be an issue
