### ISSUE TITLE
onSubmit use always the same reference to values object

### ISSUE THREAD

**Issue by mielecmichal** [joepuzzo/informed#149]
Hi,

It is common scenario to create forms mapping 1 to 1 our domain objects. I am experiencing one annoying problem with this approach. Due to the fact that onSubmit always execute callback with the same values reference, my component is not re rendered after second and next submits. 

Example (try to click Submit multiple times with different values):
```javascript
export const CarForm = () => {

    const [car, setCar] = useState({name: "BMW"});

    return (
        <div>
            <h1>{car.name}</h1>
            <Form onSubmit={setCar}>
                <Text field={"name"}/>
                <button type={"submit"}>Submit</button>
            </Form>
        </div>
    )
};
```

The workaround for now is to clone the object with spread operator:
```javascript
export const CarForm = () => {

    const [car, setCar] = useState({name: "BMW"});

    return (
        <div>
            <h1>{car.name}</h1>
            <Form onSubmit={(values) => setCar({...values})}>
                <Text field={"name"}/>
                <button type={"submit"}>Submit</button>
            </Form>
        </div>
    )
};
```

Should not informed do it internally before onSubmit?Just to save users hours of debugging?

**Comment by joepuzzo** [comment]
So im going to have to go with no. Your correct in saying for your specific use case you would like a new object but this issue is actually unique to you. Funny enough i have had more issues with people complaining that the object is not the same. ( old version would submit a duplicate object )

**Comment by mielecmichal** [comment]
Ok, now I checked it again and the problem is related with a flag ```validateOnBlur```. When this flag is set, it looks onBlur logic is called for all the inputs.

Example:
```javascript
import React, {useState} from "react";
import {Form, Text} from "informed";

export const CarForm = () => {

    const [formState, setFormState] = useState({});
    const [car, setCar] = useState({name: "BMW"});

    const {errors = {name: []}} = formState;

    return (
        <div>
            <h1>{car.name}</h1>
            <Form onSubmit={car => setCar({...car})} onChange={setFormState}>
                <Text validate={(value = "") => value.length ===0 ? "Cannot be empty" : ""} field={"name"} validateOnBlur/>
                <p style={{color: "red"}}>{JSON.stringify(errors.name)}</p>
                <button type={"submit"}>Submit</button>
                <button type={"reset"}>Reset</button>
            </Form>
        </div>
    )
};
```

**Comment by mielecmichal** [comment]
I see your point. Thanks for explanation. You may close the issue.
