### ISSUE TITLE
Gatsby JS v2 error

### ISSUE THREAD

**Issue by goodok21** [joepuzzo/informed#152]
Trying to import `Form` and `Text` to Gatsby project, got error in Chrome console:
```
Uncaught SyntaxError: Unexpected token .
```

Node: v11.10.0
Gatsby: 2.0.72
Informed: 2.1.3

**Comment by joepuzzo** [comment]
Hmm does gatsby use webpack? how is the project built?

**Comment by goodok21** [comment]
Yes, Gatsby using Webpack, can you check the Gatsby repo?
[https://github.com/gatsbyjs/gatsby](https://github.com/gatsbyjs/gatsby)
It's really nice static site generator and it's very sad that I can't use your cool package together :/
