### ISSUE TITLE
TextArea will not receive input

### ISSUE THREAD

**Issue by kentrh** [joepuzzo/informed#153]
When trying to enter text in text area nothing is entered in the input field and only the last character typed is set as the value.

Ref: https://joepuzzo.github.io/informed/?selectedKind=Inputs&selectedStory=Text%20Area&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by joepuzzo** [comment]
You are right fixing now..

**Comment by joepuzzo** [comment]
Fixed sorry about that.. i had made an update to the mask function and broke the text area. Going to look into why tests did not catch this

**Comment by joepuzzo** [comment]
I also updated the unit tests to catch this !

**Comment by kentrh** [comment]
Perfect! and thanks! 😃
