### ISSUE TITLE
Form prop 'preSubmit' does not exist

### ISSUE THREAD

**Issue by jaymes-bearden** [joepuzzo/informed#156]
Just started a migration from 'react-form' in to this library; fantastic work!

It appears that `<Form>` preSubmit does not exist. It's [mentioned in the docs](https://joepuzzo.github.io/informed/?selectedKind=Form&selectedStory=Props&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) but [appears to be missing in the Form component](https://github.com/joepuzzo/informed/blob/d3642d04e590595090283fbaa5ca7a0769124ce3/src/components/Form.js#L49).

Also doesn't look like it's in the FormController either.

Have I missed something?

**Comment by joepuzzo** [comment]
https://github.com/joepuzzo/informed/blob/master/CHANGELOG.md It was removed. Take a look at the changelog.

**Comment by joepuzzo** [comment]
If its still in the docs that’s totally my bad as i forgot to remove that line from the table. Basically its very easy for a dev to do this himself so the function was never needed

**Comment by joepuzzo** [comment]
Removed from docs
