### ISSUE TITLE
MaintainCursor

### ISSUE THREAD

**Issue by kallrobin** [joepuzzo/informed#158]
Hi!

I just recently started using informed and i have hit a bit of a roadbump.
I'm not really sure if it's a bug or if i am using it wrong, let me explain.

I have an input that should format and parse a value.

```javascript
const parseSSN = (value) => {
  if (!value) {
    return value;
  }
  return value.replace(/[-]/g, '');
};

const formatSSN = (value) => {
  if (!value) {
    return '';
  }
  if (value.length <= 8) {
    return value;
  }
  return injectString(8, '-', value);
};

<Input
  field={id}
  id={id}
  type="text"
  maintainCursor
  format={formatSSN}
  parse={parseSSN}
/>
```
TLDR: `value: 201212121212` -> `format: 20121212-1212` -> `parse: 201212121212`

The formatting and parsing works just fine.
But, if i place my cursor before the dash(-) and type something the cursor jumps to the end. If i do the same but after the dash it works just as you would expect.

I thought the `maintainCursor` prop should prevent that from happening, or is it only for `mask`?

**Comment by joepuzzo** [comment]
Only on mask unforunately, I forget why off the top of my head but there was a limitation using maintainCursora and format and parse

**Comment by kallrobin** [comment]
Oh, i was thinking it was something like that.
I was able to solve it with a regexp and mask instead. Perhaps someone else encounters a similar problem, so i'll share some code.
```javascript
const normalizingRegex = /^((19|20)?[0-9]{2,6})-?([0-9]{0,4})$/

export const formatSSN = (value) => {
  if (!value) {
    return value;
  }
  const parts = value.match(normalizingRegex);
  if (!parts) {
    return value;
  }
  // eslint-disable-next-line
  const [full, date, century, last] = parts;
  if (
    (century && date.length === 8 && last) ||
    (!century && date.length === 6 && last)
  ) {
    return `${toString(date)}-${toString(last)}`;
  }
  return value;
};

<Input
  field={id}
  id={id}
  type="text"
  validateOnChange
   validateOnBlur
  maintainCursor
  mask={formatSSN}
  validate={validateSSN}
  success={value && !syncError && !isSSNLoading && !asyncError}
  error={!!syncError || !!asyncError}
/>

```

Thanks for the quick response!
