### ISSUE TITLE
Dynamic ArrayField with object value

### ISSUE THREAD

**Issue by blakeyoder** [joepuzzo/informed#159]
I'm attempting to use an `ArrayField` to dynamically add new items. It seems that the field works correctly with a flattened list such as `['john', 'terry']` but when I populate the `ArrayField` with an array of objects I'm unable to access the values within the object and can't prepopulate the form field.

Example initial value that doesn't work as expected.
```
[
   {
      "name":"john",
      "age":28
   },
   {
      "name":"terry",
      "age":25
   }
]
```

**Comment by joepuzzo** [comment]
Ahhh so you can't do this lol. At least not with any of the inputs provided with informed. Array fields are designed for flat arrays of fields. What type of input takes an object? Did you build a custom one?  If you want an array like you have above, then you need to use an array of scopes! https://joepuzzo.github.io/informed/?selectedKind=Arrays&selectedStory=Array%20Of%20Scopes&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by joepuzzo** [comment]
This is an interesting ask... i will need to rack my brain against if i can support this or not with dynamic array fields 🤔

**Comment by blakeyoder** [comment]
For context: I have an API that sends me back a response that includes an array of objects. I'd like to pre-populate the form with that data and then be able to add new entry in the array (which is an object) and PATCH back to the api with an additional object entry in that array.

**Comment by joepuzzo** [comment]
So you dont technically need to use the ArrayField to do this.. its simply a helper component. You can just manually add another JSX input ath the end with the array field syntax `field="siblings[4]"`

**Comment by joepuzzo** [comment]
and utilize scope.

**Comment by blakeyoder** [comment]
Thanks for the chat and direction @joepuzzo - closing out.
