### ISSUE TITLE
How to integrate with a redux app

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#16]
**Use case**
- Having an react redux app, with some object, holding a string property `path`
- Having a form for editing that objects `path` property
- Having a widget for navigating folders on disk, and dispatch a redux action to select a given path.

Is that possible with the current version?

**Comment by jacargentina** [comment]
Nope.

Redux has `mapStateToProps` in which any state should be made available to components via props. In this case for example:

```jsx
import { Form, Text } from 'informed';
import PathBrowser from './PathBrowser';

class MyComponent extends React.Component {
  render() {
    return (
      <Form
        initialValues={this.props.editing}
        render={() => (
          <div>
            <Text field="path" id="path" autoFocus />
            <PathBrowser onSelectedChanged={this.props.pathChanged} />
          </div>
        )}
      />
    );
  }
}

const mapStateToProps = state => {
  return {
    editing: state.obj // obj = { path: 'the string for the path' };
  };
};

const mapDispatchToProps = dispatch => {
  return {
    pathChanged: newPathStr => {
      dispatch(updateObj('path', newPathStr));
    }
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Mycomponent);

``` 

I don't know the internals of informed, so I suspect that when I provide an `obj` instance with some data, `initialValues` makes them available to every `field` on its editors; but I don't know how would `<Text />` know that the `path`value has changed after calling the `pathChanged`handler?

My example works fine when I'm editing the values myself, but is not getting the value I send via the <PathBrowser /> event.

**Comment by joepuzzo** [comment]
I guess i don’t understand your use case.. you want to set it up such that when a user types in the text field that it calles your path changed action?

**Comment by Mairu** [comment]
A change to intialValues will not update the form values, I think that is his problem.
To change values after initialization you have to call setValues of the formApi.

**Comment by joepuzzo** [comment]
Yeah you would call setValue if you needed to set the value dynamically based on some other change.

**Comment by jacargentina** [comment]
Great! Thanks for the advice.
