### ISSUE TITLE
Form onChange is triggered when form is unmounted

### ISSUE THREAD

**Issue by alaycock** [joepuzzo/informed#160]
When a `<Form>` element is unmounted, it triggers a final `onChange` with the values `{}`. You can see a [demo of this in this Code Sandbox](https://codesandbox.io/s/w09no4yn3l?fontsize=14). This seems like odd behavior to me, but it might be intentional, along the lines of this issue: https://github.com/joepuzzo/informed/issues/49

I would expect that when the form unmounts, it would not trigger an `onChange`, because the form ceases to exist. I understand that if you unmount a form field, the field should be removed from the form, but it seems odd that if the `<Form>` is unmounted, it then proceeds to clear that form during unmounting.

This is a problem for me beause I have a form that consists of several checkboxes. Each checkbox fires a request to my API which is triggered by the `<Form>`-level onChange. On unmount, it fires an additional `onChange` with empty values.

My current workaround is to bind an onChange to each individual checkbox, but this seems like something that might be more appropritately handled at the library level.

**Comment by joepuzzo** [comment]
Trying to figure out if this is expected behavior. Will get back to you on this.

**Comment by coulson84** [comment]
I am seeing similar behaviour at the moment. The onChange handler fires once for each field in the form. Each time it fires there is one less property present in formState.values until it is empty and the form finally unmounts. I can workaround it for now but it is frustrating on some pages where we use the onChange event to create an object - there is no submit button. The onChange event being triggered with no values in as it unmounts means that effectively any changes the user makes are wiped out when they navigate to the next tab.

We are working around it for now by wrapping the form in a class component and using componentWillUnmount to disable the onChange event during unmounting.

We are also doing the same during mounting where the onChange event is firing for every field that gets mounted in the form.

**Comment by joepuzzo** [comment]
So in the mean time i would not rely on the on change to keep the state externally. It sounds like you really just need the values once at the end. A better way to solve that would be to, when the button is clicked, simply get the values out of the forms state in one of two ways. 1 use the formApi.getValues() function. 2 use the useFormState hook

**Comment by coulson84** [comment]
yeah, the rub is that it is in any navigation that needs to save the data in case they come back to it later. Can probably do this with a before navigate hook or something I guess but  the current workaround it suitable until we find the time to revisit it.

Thanks for informed by the way - great library 👍
