### ISSUE TITLE
Can't remove array field with initialValues

### ISSUE THREAD

**Issue by DouglasGabr** [joepuzzo/informed#161]
After #157 was fixed, it's happening a new bug: you can't remove a field if it is in the `initialValues`.

Example code:
https://codesandbox.io/s/yp761o2xpz

How to reproduce the error:
1. Add a field after the initial ones (click "Add Sibling")
2. Type something in Sibling 2 field
3. Remove "Sibling 1"
4. The sibling 1 is removed but the value of sibling 2 is replaced with the initialValues at index 1

PS. using version 2.1.9

**Comment by joepuzzo** [comment]
Yup im aware of this and thinking of a fix. May have to remove initial value when remove is clicked.

**Comment by DouglasGabr** [comment]
I think it's a good idea, when the user removes an item from the list it should be deleted forever, even if it was an `initialValue`.
In my use case, I have an `event` entity with a bunch of `tickets`, and I want the user to be able to remove some of the saved tickets (that are in the `initialValues`)

**Comment by kyawkyawsoezhu** [comment]
@joepuzzo any update on this one, I found `Formik` have the same implementation, like @DouglasGabr said when user remove it should be delete forever, 
here example of `Formik ` https://codesandbox.io/s/x77o7v4kxz

**Comment by joepuzzo** [comment]
This has been fixed
