### ISSUE TITLE
setValues does not work

### ISSUE THREAD

**Issue by chrischen** [joepuzzo/informed#162]
In my code

`formApi.setValue("fieldName", "")` works but `formApi.setValues({"fieldName": ""})` does not work, and no console errors appear. The value is kept at what it was before.

And if I do this called sequentially:
```
formApi.setValues({"fieldName": ""}); // does not work
formApi.setValue("fieldName2", ""); // works
```
Then fieldName2 gets set to "" and fieldName keeps whatever value it previously had.

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/23n6zl0ln0 I think something must be messed up in your code because it works in that sandbox.

**Comment by joepuzzo** [comment]
closing

**Comment by chrischen** [comment]
I managed to figure out the actual issue:
https://codesandbox.io/s/rlpj5o919m

It turns out it works in your sandbox because you're setting non-empty values. But if you try to use setValues() to clear multiple values to be empty, it does not work. Calling setValue() multiple times to clear values does work.
