### ISSUE TITLE
SyntaxError in IE 11

### ISSUE THREAD

**Issue by eXaminator** [joepuzzo/informed#166]
Hi,

I just stumbled over a strange and hard to debug issue which I was able to kind of pinpoint to informed 2.x (it works after downgrading to 1.x).

Everything worked fine except when loading the app in IE 11 (in our case specifically via webpacks async import, I'm not sure if that is needed to reproduce the error, but I don't think so). It showed me a SyntaxError in the "debug" npm library where it uses an arrow function.

It seems that informed uses the "src" instead of "dist" version of debug, which contains arrow functions, and IE 11 stumbles over those. I'm not sure where this should be changed, but I have the feeling that informed needs some updated build process or something to rewire it to use the "debug/dist" files instead of "debug/src".

**Comment by joepuzzo** [comment]
https://github.com/joepuzzo/informed/issues/163

**Comment by joepuzzo** [comment]
Also I am trying to figure out if i want to do what you suggested ( using the `debug/dist` ). I think that may be my next move

**Comment by joepuzzo** [comment]
But in the mean time look at the issue i referenced

**Comment by joepuzzo** [comment]
@eXaminator after further reading... I cant seem to find any docs on a `/dist` file for the debug lib? Can you link to any docs that reference this?

**Comment by eXaminator** [comment]
Hi @joepuzzo, thanks for the quick answer!

I don't know about docs either, I just saw the dist folder in their package when debugging the issue.

The referenced issue is not the problem. For one I'm already using the polyfills. Second: The problems comes from a SyntaxError due to an arrow function, which no polyfill would even handle. That's babels job and should already be handled in the transpiled library code.

I'll see if I can get you some more specific info on the problem soon (I'll have to further inspect the packaged informed 2.x sources for that to get a feeling where that comes from).

**Comment by eXaminator** [comment]
This is sad.

I found an issue over at the debug library regarding this problem: https://github.com/visionmedia/debug/issues/674

It seems they have no wish to tackle this and leave it to each individual project to ensure that the library code is transpiled. This also means, that using this library in another frontend library (like informed) will break apps in legacy browsers if the app doesn't transpile every node_module itself (which imho most don't because of the build time overhead this would produce with many dependencies).

I guess you can close this issue as this isn't really an informed issue as I see it, unless of course you want to do something about it (update docs, remove debug etc.).

Anyway, sorry for bothering you with this, I still hope this information is helpful in some way.

**Comment by joepuzzo** [comment]
Keep reading in that other issue!! polyfills were not the fix!

**Comment by eXaminator** [comment]
I know that polyfills are NOT the issue (I never said otherwise) and that I could get this to work in my app, I'm just not convinced that I even want to try. I don't want to add even more stuff / configuration to my build process if it's not necessary.

As I see it, as of right now, informed is not compatible with IE11 unless users of the library have a specific build process that also transpiles some second hand dependencies. I'm just not willing to do that, at least not in a modern code base. I would always carry that stuff around, even if I might not need it in the future and I wouldn't even know it.

So my advice to you would be to either remove the "debug" library and use something else, remove support for old browsers (and update docs accordingly) or at least update the documentation on what to do to get this running for IE11 and other legacy browsers. Not for me, but maybe for others who want (or need) to have their application run in older browsers.

Maybe this is not a huge problem. Maybe newer apps that use create-react-app (and its webpack configuration) just transpile everything and it will work in those apps (I don't know, I haven't tested that). That's why I'll close this issue now and leave it up to you if you think it's worth the trouble to update documentation or generally investigate this further, or if you want to leave it to the (perhaps minority of) users to handle this problem themselves if they come across it.
