### ISSUE TITLE
Problem in values reference when submiting the form

### ISSUE THREAD

**Issue by DouglasGabr** [joepuzzo/informed#168]
When the form is submitted, the following line is executed to get the form state:
https://github.com/joepuzzo/informed/blob/094d9bf4eab6e5dda16f90b3a79aabf446fb5258/src/FormController.js#L58

This is causing problems, because `values` is an object inside the form state, and it is being passed as a reference to the `onSubmit` event in the `Form`. So, if the form is unmounted from the screen while the submission logic is executing (in my case, a graphql request), the values turn in an empty object.

I made a codesandbox that replicates the issue: https://codesandbox.io/s/p5712345mj
In the browser console, you will see that the values become an `{}` when the `Form` is unmounted

In version 1.x, the `getFormState` used to do `JSON.parse(JSON.stringify(this.state));`, which copies the entire object tree, nothing was passed as a reference.

Will this be changed, or do I need to manually do the parse stuff in the submit handler?

**Comment by joepuzzo** [comment]
This is pretty funny. One of the devs on my team ran into this same issue today.. Also funny is that i used to create a Deep copy of the form values in old versions of the lib BUT it caused more issues. Therefore i do pass the reference and will continue to do so. THAT BEING SAID, You can easily fix this by doing `JSON.parse(JSON.stringify( values ))`

**Comment by DouglasGabr** [comment]
Ok @joepuzzo, thanks for the quick response! Closing the issue
