### ISSUE TITLE
errors with Gatsby

### ISSUE THREAD

**Issue by gentleShark** [joepuzzo/informed#172]
couldn't get informed to work with Gatsby. there was a namespace error. Informed looks great but I ended up using a forms package that worked with Gatsby out of the box. Just wanted to call this to your attention (even though it may be a Gatsby issue) since Gatsby is pretty popular these days. Feel free to close this issue.

**Comment by joepuzzo** [comment]
So you would have to go into more details as i dont use Gatsby. Likely is something up with the way Gatsby is built.

**Comment by gentleShark** [comment]
I agree it's likely something with the way Gatsby is built. Here is the bug behavior in case it's something you want to look into.
1) Add an informed form in your gatsby project
2) Compile with gatsby (gatsby develop)
3) Visit your gatsby site on localhost:8000 and get blank page with error in the console "Uncaught SyntaxError: Unexpected token ." related to commons.js.
4) The error is throw related to line in bold below:
```
function save(namespaces) {
	if (namespaces) {
		**{}.DEBUG = namespaces;** //aforementioned error related to this line 
	} else {
		// If you set a process.env field to null or undefined, it gets cast to the
		// string 'null' or 'undefined'. Just delete instead.
		delete {}.DEBUG;
	}
}

```

**Comment by joepuzzo** [comment]
I have removed debug as a dependency so you can try this again

**Comment by teojunjie** [comment]
Any updates on this?
