### ISSUE TITLE
debug dependency

### ISSUE THREAD

**Issue by mistoo** [joepuzzo/informed#173]
How about removing debug dependency at all / strip it from production build? 
debug drags 'tty' and 'os', which in total adds 23kB extra to ES module (unminified) and make somewhat difficult to use with rollup (need extra plugins) 

```
$ ls -l build/dist
-rw-r--r-- 1 foo users 146666 Mar 15 11:16 index.js
-rw-r--r-- 1 foo users 123533 Mar 15 11:14 index.js.no-debug
```
I can make PR for this if you OK with that.

**Comment by joepuzzo** [comment]
Hmm i really wanted to utilize debug so that other developers could quickly and easily debug there code.  I don't think its something i want to remove.

**Comment by mistoo** [comment]
Sure, I do not want to remove debug messages, just strip them in production build (and save ~20kb of code), or replace debug with something simple if they are really needed in production, sth like:

```
export default function createLogger(prefix = null) {
    if (prefix)
        prefix = `[${prefix}]`

    return function(...args) {
        if (prefix)
            args.unshift(prefix)

        if (process.env.NODE_ENV !== "production") {
            console.log(...args)
        }
    }
}
```

**Comment by joepuzzo** [comment]
I may do somthing like this soon but its not high priority atm

**Comment by joepuzzo** [comment]
Done. Latest release uses my own home made debugger :)
