### ISSUE TITLE
form cannot be submitted -  all errors are null but form is invalid

### ISSUE THREAD

**Issue by mcmunder** [joepuzzo/informed#174]
Thank you for creating informed! It's great!

Howerver, I ran into a problem when upgrading from 1.10.12 to 2.1.12. Somehow I cannot submit a form anymore that worked flawlessly before. I did not change any code, only upgraded the informed dependency.

When I log out `formState` after clicking the submit button (which triggers a rerender but does not submit) I get a formState like:
```js
{
...,
errors: { 
  firstName: null,
  lastName: null
},
invalid: true
}
```
i.e. the form has no errors but is invalid. 

I'd love to start using  all that new hooks goodness but this stops me from updrading.
Thanks for any help!

**Comment by joepuzzo** [comment]
Thanks! And yup this is a simple fix! https://github.com/joepuzzo/informed/blob/master/CHANGELOG.md#200-feb-7-2019 

Always make sure you read the changelog when changing major versions. Specifically in this case you want to read this bullet 
```
the validate prop now expects the validation function to return undefined if there is no error. Any other returned value (including falsey null, 0, etc will be treated as an error for the field.
```

**Comment by mcmunder** [comment]
Arghhh. Somehow I missed that. Totally working again now. Thanks and sorry for wasting your time ;-)
