### ISSUE TITLE
Informed code is using hooks internally on "non-hook paths"

### ISSUE THREAD

**Issue by joshball** [joepuzzo/informed#176]
Because of the [limitations of hooks ](https://reactjs.org/warnings/invalid-hook-call-warning.html) (namely the multi instances of react), users of the library, if they are using hooks in their own code, and happen to be importing a library using informed, are getting hook errors even though informed does not **appear** to be using hooks. That is, informed hints/suggests in the docs that if you want to use hooks, do it "this" way. For instance, in the Form State doc page it says:

> 5) By accessing the `formState` via Hooks!

This might lead a user (or at least me ;-) to think that the library itself is not using hooks unless you do it like the above.

So the issue is that the internal components like `<Text field="name" />` are using hooks through `useFile` and `useFormApi`. And if there happens to be two libraries loaded by accident, then it will trigger the error.

So, this might just want to be documented in the gotcha and hooks library and even on the main page, along with links to debugging/resolution techniques.

[Here was the catalyst for this issue](https://github.com/facebook/react/issues/15097).

**Comment by joepuzzo** [comment]
Ahh yes i figured it was implied that you need the latest version of react. I may add info about that

**Comment by joshball** [comment]
I wasn’t even thinking about the version, but the fact that two versions
are running together.

**Comment by ppinel** [comment]
If I am getting this right, having two versions of `informed` is an issue or you're only talking about `react` ?

**Comment by joshball** [comment]
Just react.
If this doesn't make sense, I can try and explain it a bit better.
