### ISSUE TITLE
Submitting empty values

### ISSUE THREAD

**Issue by guyandy** [joepuzzo/informed#179]
I am having an issue submitting empty values for fields on an update form. For example, if I have a simple field:
`<Text type="number" field="pay_amount" id="pay_amount" />`
And, it's initially loaded with a value, which works just fine. However, if I remove the value so that the field is now blank (which is what I want to send to the backend) the object that is passed to the onSubmit handler does not contain that field. Now, if I have a field that initially loads as blank/empty and it's never touched, the onSubmit handler sees that field with a value of null, which is what I expect for the former example. Any guidance on how to get those empty values into the form submit? Thanks! And many thanks on a great form component!

**Comment by joepuzzo** [comment]
So question.. I think im going to simply add a prop allowEmptyStrings so this is not a breaking change. What would you expect the value to be when the form first loads and there is no initial value?

**Comment by guyandy** [comment]
I think any falsy value would be fine, but I would lean towards `null`

**Comment by joepuzzo** [comment]
The lib always chooses undefined over null. Because null is something and undefined is nothing lol

**Comment by joepuzzo** [comment]
also false is something and undefined is nothing :)

**Comment by guyandy** [comment]
Ha, right. I think that would be fine. So if I set allowEmptyStrings prop, then the those empty fields will be present, but set to undefined?

**Comment by joepuzzo** [comment]
umm so no lol. If a field is set to undefined it is removed from the object

**Comment by joepuzzo** [comment]
I was saying that the `allowEmptyString` prop would allow the user to set `initialValue` to `''` and also when the backspace it would not remove and instead be `''`

**Comment by guyandy** [comment]
Okay, I think that works. Maybe I misunderstood your original question.

**Comment by joepuzzo** [comment]
Ok i can elaborate on that! So lets use an example. Supose I have the following form.

```
<Form>
  <Text field="firstName"/>
</Form>
```

The values when the form loads will be `{}`

Now when the user types `asdf` and then backspaces it the values would be `{ firstName: ''}`

Would this be expected behavior?

**Comment by guyandy** [comment]
Thanks for the example. For the backspaced use case, that makes sense, and would be expected behavior. 

If we consider the case where the user doesn't interact with the field, I would expect the field to be present, and I don't really care what the value is ('', false, null, undefined). (The current code supports this, as outlined in my original post, I'm just mentioning it so that functionality is preserved.)

**Comment by joepuzzo** [comment]
The current code actually does not support this. If you load a form the field will not be there until you type?

**Comment by guyandy** [comment]
Ah, you are right. I was looking at my update form, and it's loading a null value, so I get that value back, if the field is untouched.

**Comment by rickykenny** [comment]
> I was saying that the `allowEmptyString` prop would allow the user to set `initialValue` to `''` and also when the backspace it would not remove and instead be `''`

@joepuzzo I would love this proposed allowEmptyStrings prop too! Is this something you've already started on?

**Comment by joepuzzo** [comment]
In progress

**Comment by joepuzzo** [comment]
Just released!!  2.3.0 there are two new props `allowEmptyStrings` <<< Form level prop && `allowEmptyString` <<< field level prop

**Comment by notyoyoma** [comment]
@joepuzzo I just spent awhile looking for this in the [docs](https://joepuzzo.github.io/informed/?path=/story/form--props), but couldn't find it. Are the docs up to date?

**Comment by notyoyoma** [comment]
(I just left a comment but deleted it)
I was looking for this in the docs, and couldn't find it, then switched back to the docs page, and saw exactly what I was looking for. Somehow Ctrl+F failed me. Maybe due to the sidebar on your docs.

Anyways. I found what I needed, so you can ignore my previous comment and this one.
