### ISSUE TITLE
What about useArrayField?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#181]
The `ArrayField` apparently offers good utility and yet it still requires render prop pattern while hook could do the same in a much easier way. In fact, the hook could be an underlying implementation to be used in the `ArrayField`. What do you think? I can do PR.

**Comment by joepuzzo** [comment]
Hmm i can look into this

**Comment by joepuzzo** [comment]
always open to a PR too

**Comment by joepuzzo** [comment]
This was very easy to do i will add soon

**Comment by joepuzzo** [comment]
This is done!
