### ISSUE TITLE
Why useLayoutEffect?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#182]
I've noticed in the code you are using `useLayoutEffect` instead of `useEffect` quite heavily. What is your reasoning behind it? It can make UI somewhat laggy since it runs synchronously after a render.

Is it perhaps because of the tests? Are you aware there is an [`act`](https://reactjs.org/docs/test-utils.html#act) utility that takes care of this problem?

**Comment by joepuzzo** [comment]
So yeah keeping things synchronous simplifies everything. I don't know of all the issues `useEffect` caused off the top of my head but i do know there is a list of things. Testing is one of them... unfortunately all of my tests have been written using Enzyme ( the previously recommended test framework by the react team  ) Enzyme has a much better testing interface! BUT unfortunately is behind on support for hooks, and unless my understanding is incorrect, I cant use act :( .

**Comment by FredyC** [comment]
Hm, I don't know anything about Enzyme, but I heard some rumors they do support `act` as well now.

Would be definitely great to figure it out, nobody wants laggy forms :)

**Comment by Jakobo** [comment]
Unfortunately, the heavy use of `useLayoutEffect` will also hamper the SSR case. Anyone who's rendering forms on the server side will generate the following warning

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.

**Comment by joepuzzo** [comment]
This has been changed. I now `useEffect`

**Comment by futjikato** [comment]
Still getting quite a lot of warnings regarding the use of useLayoutEffect in version 2.6.14. 
If I get that right that is because it is used in each Field ( e.g. Text ) for some debugging helper.

**Comment by FredyC** [comment]
I would say these are the worse...

https://github.com/joepuzzo/informed/blob/221423d65d7434fb32c65c3058b2743c85750fe3/src/hooks/useForm.js#L37
https://github.com/joepuzzo/informed/blob/e4f2a487ca26467867b5b003f492d5b09d6fcb84/src/hooks/useField.js#L217

For those debugging ones, I think fairly ok to wrap them in `process.env.NODE_ENV` check. Or [get inspired](https://github.com/mobxjs/mobx-react-lite/blob/master/src/staticRendering.ts). It's a much better solution to let user inform the informed that code is running in SSR.
