### ISSUE TITLE
Careful about React.useMemo

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#183]
https://github.com/joepuzzo/informed/blob/48cef77d80bab4365100f85c718384efb538d5f5/src/components/Scope.js#L39

As [the documentation](https://reactjs.org/docs/hooks-reference.html#usememo) states...

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

I recommend `useRef` instead, even though it doesn't have the nifty "lazy init", there are [a ways around it](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily).

**Comment by joepuzzo** [comment]
So if i used ref.. when would i rebuild and set `current`? Would that happen in an effect then?

**Comment by FredyC** [comment]
Honestly, I wasn't really investigating the purpose of that comment. Would it be bad to lose those variables over renders? It might be the first step to try it out. If you don't have tests for it, make some and see if it works without `useMemo`. In case it does work, then you can essentially keep it as it will serve well for optimization purposes. It might just recalculate from time to time.

**Comment by joepuzzo** [comment]
Yeah I have to read more into that semantic guarantee stuff lol
