### ISSUE TITLE
formApi.setValues() does not work when setting values to empty strings

### ISSUE THREAD

**Issue by chrischen** [joepuzzo/informed#186]
https://codesandbox.io/s/rlpj5o919m

```
// This does not work
formApi.setValues({ value1: "", value2: ""})

// This works
formApi.setValue("value1", ""); formApi.setValue("value2", "");
```
If you try to use setValues() to clear multiple values to be empty, it does not work. Calling setValue() multiple times to clear values does work.

#162

**Comment by joepuzzo** [comment]
Yup i think this line is the culprit!! https://github.com/joepuzzo/informed/blob/master/src/FormController.js#L235

**Comment by joepuzzo** [comment]
This works now in 2.3.0!! However you need to make sure you pass this! `allowEmptyStrings` to the `<Form />`. see this issue for reference https://github.com/joepuzzo/informed/issues/179
