### ISSUE TITLE
Allow stopping propagation of form submit event

### ISSUE THREAD

**Issue by tfussell** [joepuzzo/informed#19]
Hello. Thanks for the nice library. I would like to mention a problem I'm having and two possible solutions I've come up with. I can implement either and submit a pull request if either seem acceptable. I have a `form` containing a modal which itself contains a `form`. Nested forms are disallowed by HTML so I'm using a React portal to render the modal outside the form even though it is semantically a child of the parent form. This works fine. Unfortunately, submitting the child form also submits the parent form because the submit event bubbles upwards in React and I don't have control over this.

One way to solve this is to pass the event as a second argument to the Form `onSubmit` callback prop. This would allow the user to call `event.stopPropagation()` manually.

Another way to solve this is to use the same pattern as the Form `dontPreventDefault` prop. A new boolean prop called something like `stopPropagation` that, when set to `true`, would automatically call `event.stopPropagation()` just before or after the `event.preventDefault()` call.

Do either of these sound reasonable?

**Comment by joepuzzo** [comment]
They both sound reasonable.. however i find it strange that you cant have that modal render from outside the `<form>`?? That would also fix your issue and seems like the root cause.

**Comment by joepuzzo** [comment]
@tfussell whats the status on this? Have you looked into removing form from form?

**Comment by joepuzzo** [comment]
Updates or can i close ?

**Comment by tfussell** [comment]
Hi Joe. Sorry for the delay. I know I don't like to keep issues open on my repos either! For my project, it makes more sense for the parent form to contain the modal because the form holds the modal state (to allow the form to open and close the modal as needed). I agree that moving the modal outside of the form would be another solution if this weren't a requirement of mine. Thanks for your time in considering this.

**Comment by JaffParker** [comment]
Hi @joepuzzo 

I ran into the same issue now. I'm making a modal with another form inside a Field in the form. Everything goes well until I submit: the event just goes all the way to the parent form and submits it as well... Not even sure where to look for solution.

**Comment by PatrickLerner** [comment]
We ran into the same issue today as well. Seems like this project is once again unresponsive to reports. I think we will look into using different libraries for future projects.
