### ISSUE TITLE
dynamic arrayfield after add/remove initialValues are restored

### ISSUE THREAD

**Issue by slillo** [joepuzzo/informed#191]
I'm trying to use custom field inside ArrayField (with asField):

- [ ok ] initialValues are correctly setted up
- [ ok ] editing fields formState.values are correctly updated, 
- [ ko ] adding a field formState.values are restored to initialValues (1st problem)
- [ ko ] removing any field always last field is removed and all fields values are restored to initialValues (2nd problem)

Please take a look at this example on CodeSandbox: 
[![Edit Informed ArrayField Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3kpwynlv9?fontsize=14)

In the example there are 10 fields. Each field has as value its index (first field 0, second field 1, and so on). 

To replicate first problem just edit nth field and click on '+' button, a new empty field will be added, but nth field value will be restored to n-1.
To replicate second problem just edit nth field and click on a '-' button near any input field except the last one (or you can think it is working as expected). Always the last visible field will be removed and nth field value will be restored to n-1.
Re-adding field deleted, if the newly appended field is one the first 10, it will contain its initialValue.

**Comment by joepuzzo** [comment]
Good find i will work on fix!

**Comment by joepuzzo** [comment]
Ok so this is actually not an issue with informed. Its an issue with your code. I dont have time to dig into the specifics but you should NOT be using `asField` the way you are... you are attempting to define a new component on every iteration of every render! if you do that all hell will break loose as it has in your sandbox. Here is a sandbox with the native `Text` component and your example that works as expected :) https://codesandbox.io/s/mz19w791vy

**Comment by slillo** [comment]
I tried also to move Component definition outside App.
[![Edit Informed ArrayField Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3kpwynlv9?fontsize=14)

Does ArrayField works only with native field?

**Comment by joepuzzo** [comment]
I just looked at your sandbox and there is no issue ??

**Comment by slillo** [comment]
On add no problem, on remove and re-add deleted field there is always the same problem. 

[![Edit Informed ArrayField Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/321v5xv0qp?fontsize=14)

![https://i.imgur.com/N7nmBY9.gif](https://i.imgur.com/N7nmBY9.gif)

**Comment by joepuzzo** [comment]
Yup i see it now.. working on solution

**Comment by joepuzzo** [comment]
Just published V 2.3.2 this should now be fixed.
