### ISSUE TITLE
`validateFields` doesn't play nicely field level validations

### ISSUE THREAD

**Issue by ewingrj** [joepuzzo/informed#192]
If I have a field `myinput` that currently has an error and then press the submit button, `validateFields` will be called.

If I return `{myinput: undefined}` from `validateFields`, the error from my field level `validate` function will be set to undefined, and the form will be in a "valid" state and proceed with submission.

I think it would be more intuitive if the field level validation errors were respected.

**Comment by joepuzzo** [comment]
Im a little confused on the issue here.. it sounds like its working as intended?

**Comment by ewingrj** [comment]
If the field level `validate` function and the form level `validateFields` functions are responsible for the same error, then it is working as expected.

I would argue they should be separate and each be able to set an error on a field.

At the min, maybe the docs could be updated so this is more clear.

**Comment by joepuzzo** [comment]
Yeah its working as expected. Field takes precedence. Maybe i could update docs
