### ISSUE TITLE
setValue doesn't trigger onChange

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [joepuzzo/informed#193]
here the example https://codesandbox.io/s/38l2y95jom?fontsize=14, 
I use `setValue` to change field value but `onChange` handler doesn't trigger like you change by typing input. I am not sure that it's meant to be or a bug.

**Comment by joepuzzo** [comment]
So the onChange function is passed through and is intended to be used as the native `onChange`. That way users of informed can still get there "hands on" the native `event`. What you want is `onValueChange` see docs here https://joepuzzo.github.io/informed/?path=/story/inputs--intro

**Comment by kyawkyawsoezhu** [comment]
@joepuzzo thanks for quick response, your explanation make sense but `onValueChange` only provide value and I kind of need whole html element like `onChange` provide.

In this example if **City 3** is selected, I want both `value` and `country-id`

    <Select field="city">
        <Option data-country-id="1" value="1">City 1</Option>
        <Option data-country-id="1" value="2">City 2</Option>
        <Option data-country-id="5" value="3">City 3</Option>
        <Option data-country-id="3" value="4">City 4</Option>
    </Select>

**Comment by joepuzzo** [comment]
Right but because set value is an informed function. NOT a native dom one. Its not designed to give you the native event as its not a native function. You would have to simply store the ref if you want to do that

**Comment by kyawkyawsoezhu** [comment]
@joepuzzo thanks.
