### ISSUE TITLE
Missing webpack.dev.config.js for start script

### ISSUE THREAD

**Issue by joshball** [joepuzzo/informed#194]
The package.json "start" script requires a `webpack.dev.config.js`
```
    "start": "webpack-dev-server -d --config webpack.dev.config.js --port 4004 --hot",
```
But `webpack.dev.config.js` doesn't seem to exist anywhere in the repo?

Do you have a script we can check into the config directory?

Thanks.

**Comment by joepuzzo** [comment]
My bad... `npm run storybook` is the one used for development.. that start command should be changed

**Comment by joepuzzo** [comment]
Fixed
