### ISSUE TITLE
Freezing App, after clicking a link after submit

### ISSUE THREAD

**Issue by danrcoull** [joepuzzo/informed#195]
I have multiple foprms across the site, it submits data props through redux, 

but the minute i click any Link component the entire app freezes 

basePullAll@webpack-internal:///../../node_modules/informed/dist/esm/index.js:4089:7
pullAll@webpack-internal:///../../node_modules/informed/dist/esm/index.js:4119:7
apply@webpack-internal:///../../node_modules/informed/dist/esm/index.js:3723:20
overRest/<@webpack-internal:///../../node_modules/informed/dist/esm/index.js:3760:12
cleanup@webpack-internal:///../../node_modules/informed/dist/esm/index.js:4235:5
_delete@webpack-internal:///../../node_modules/informed/dist/esm/index.js:4204:7
deregister@webpack-internal:///../../node_modules/informed/dist/esm/index.js:4680:9
useField/</<@webpack-internal:///../../node_modules/informed/dist/esm/index.js:5406:7
callCallback@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:149:9
invokeGuardedCallbackDev@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:199:7
invokeGuardedCallback@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:256:3
safelyCallDestroy@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17203:5
commitUnmount@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17540:17
commitNestedUnmounts@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17584:5
unmountHostComponents@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17845:7
commitDeletion@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17904:5
commitAllHostEffects@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:18685:11
callCallback@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:149:9
invokeGuardedCallbackDev@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:199:7
invokeGuardedCallback@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:256:3
commitRoot@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:18913:7
completeRoot/<@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20418:5
unstable_runWithPriority@webpack-internal:///../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:255:12
completeRoot@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20417:3
performWorkOnRoot@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20346:9
performWork@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20254:7
performSyncWork@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20228:3
interactiveUpdates$1@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20495:7
interactiveUpdates@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:2170:10
dispatchInteractiveEvent@webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4882:3

**Comment by danrcoull** [comment]
Hi  Thanks for your response. ok it turned out it was breaking only with select boxes 

onSubmit at the end of the redux action i had to run this.formApi.reset() to stop it crashing.

**Comment by joepuzzo** [comment]
strange.. I really am not sure whats going on but this sounds like a bug on your end. Unless you can reproduce this issue in a code sandbox or provide some code i cant really help.

**Comment by joepuzzo** [comment]
ok so i can close this?
