### ISSUE TITLE
Form handlers (onSubmit, onChange, etc) not being updated if prop changes

### ISSUE THREAD

**Issue by adrianocola** [joepuzzo/informed#196]
After the initial `Form` component creation, you cannot change the event handlers like onSubmit or onChange.

Example:

```javascript
import React, {useState, useEffect} from 'react';
import {Form, Text} from 'informed';

export default () => {
  const [count, setCount] = useState(0);
  useEffect(() => {
    const interval = setInterval(() => setCount((prevCount) => prevCount + 1), 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <Form onSubmit={() => alert(`onSubmit count: ${count}`)}>
      <div>render count: {count}</div>
      <label>
        First name:
        <Text field="name" />
      </label>
      <button type="submit">Submit</button>
    </Form>
  );
};
```

- This component updates itself every 1s, keeping track of the number of renders (increment an internal state)
- When the users clicks the `Submit` button, an alert with the current render count should appear
- No matter how many time you click the `Submit` button, the same message appears (`onSubmit count: 3`, for example)

That happens because the callback function sent to `onSubmit` is never updated inside the Form component on subsequent component renders. If you only use the values provided to the `onSubmit` callback, you should be fine. But you may get the wrong information  if you try to access some props or state of your component (because of  javascript's closures).

This problem happens here: (those handler are never updated when the props changes):
https://github.com/joepuzzo/informed/blob/5277f80bceb4c5503fbc19f13c83e13ecb066edd/src/hooks/useForm.js#L36-L54

I'll try to fix that and make a Pull Request

**Comment by joepuzzo** [comment]
Ahh yes i need to add effect to deregister and reregister the events
