### ISSUE TITLE
Searchable Select

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [joepuzzo/informed#199]
I want to make my `Select` field to be searchable and I know this package is only to manage form, I would like to know which package would you want to suggest, so far I've tried https://github.com/JedWatson/react-select with `asField` as a custom field but It didn't work well because **react-select** require both **label** and **value** to `setValue()`, and others problem.

P.S. do you have plan to create first party pacakges, the packages that easy to integrate with informed e.g. informed-searchable-select, informed-file-uploader .

**Comment by joepuzzo** [comment]
Im dont know how to build what your trying to build off the top of my head and unfortunately dont know of any library's that may help you. I do not plan on creating any other libs. My goal is to maintain this simple interface and allow others to do that

**Comment by kyawkyawsoezhu** [comment]
@joepuzzo thanks for your quick response.
