### ISSUE TITLE
Name attribute missing on <input /> when using custom input

### ISSUE THREAD

**Issue by jochienabuurs** [joepuzzo/informed#204]
See: https://joepuzzo.github.io/informed/?path=/story/custominputs--creating-custom-inputs#what-if-i-want-more-control-

When using that code, no name prop is passed on to the input.
`...rest` does not include a name prop. To make this work, i had to set it myself like this:
`name={props.field}`

I would expect the name attribute to be set to the field value.

The name attribute is used by browsers to auto-fill fields so it would be nice to have that ;-)

**Comment by joepuzzo** [comment]
Yup so you have two options. 1. You need to do exactly what you are doing ( nothing wrong with this.. infact its how I do in for the default inputs ) 2. You pass `name=` into all of your inputs manually.. NOT fun.

**Comment by joepuzzo** [comment]
Because this is actually not an issue with informed im closing but feel free to ask more questions here.
