### ISSUE TITLE
maskedValue not applied to initialValue

### ISSUE THREAD

**Issue by mrfelton** [joepuzzo/informed#206]
**Description:**

`maskedValue` is not being applied to a field's `initialValue`. It only works when editing the field from its initial state

```
import { Form, Text } from 'informed';
const format = value => (value != null ? `$${value}` : value)
const parse = value => (value != null ? value.replace('$', '') : value)
return (
<Form>
  <Text field="name" format={format} initialValue="test" parse={parse} />
</Form>
```

**Observed behaviour:**
The mask is not applied to the initial form value, which shows as `test`. Typing in the field after the initial load correctly applies the mask.

**Expected  behaviour:**
The initial form value should have mask applied and show as `$test`.

**Comment by joepuzzo** [comment]
Working on it!

**Comment by joepuzzo** [comment]
@mrfelton This is fixed and is now in the latest version.

**Comment by mrfelton** [comment]
Hey @joepuzzo . This fix seems to work when `initialValues` is set on the `Form` component, but not when you set `initialValue` on an individual field.

**Comment by mrfelton** [comment]
The issue occurs when using `format` and `parse`.

`mask` works fine.

**Comment by joepuzzo** [comment]
Ahh ok my bad I forgot to fix this for format and parse i will give that a go

**Comment by joepuzzo** [comment]
@mrfelton I want to make sure im clear on what the expected outcome is.. suppose the format function simply added a `$` in front of the value typed as it does in the example in the docs. What would you set the initial value to if you wanted $400 to show up. Im assuming `initialValue="400"`? Are we on the same page there?

**Comment by joepuzzo** [comment]
This is done the way i have described above and is in the latest release.

**Comment by mrfelton** [comment]
Nice one. Yes, this is what I would expect.

**Comment by mrfelton** [comment]
Did you forget to release 2.7.8 with the fix for this @joepuzzo ? i see the version number was bumped but there is no new release tag on github or release on npmjs
