### ISSUE TITLE
Duplicate identifier 'Omit' in Typescript 3.5

### ISSUE THREAD

**Issue by lalau** [joepuzzo/informed#207]
Typescript 3.5 comes with the Omit helper now:
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#the-omit-helper-type

When compiling informed with that version of typescript, it results in Duplicate identifier error.
```
node_modules/informed/index.d.ts:7:6 - error TS2300: Duplicate identifier 'Omit'.

7 type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
       ~~~~

  node_modules/typescript/lib/lib.es5.d.ts:1469:6
    1469 type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
              ~~~~
    'Omit' was also declared here.
```

One fix could be for informed to remove the Omit helper but would require informed to add typescript as dependency.

Another fix could be to rename the Omit type in informed to something else so it doesn't collide with the one in Typescript 3.5. Then you wouldn't need to add typescript as dependency.

**Comment by ivansky** [comment]
What build libraries do you use? Webpack? Babel? Versions?
