### ISSUE TITLE
DynamicArrays with passed form field names

### ISSUE THREAD

**Issue by informvisu** [joepuzzo/informed#212]
```
const DynamicArrays = (fieldsFromServer) => {
  // Assume fieldsFromServer is an array of names with which we need to create form fields
  // Also, consider all those fields as one record and add more records to Submit
  return (
    <div>
      <Form>
      ...
      </Form>
    </div>
  )
}
```
All the fields are text fields, but cannot code the field names upfront.
Please provide sample code

**Comment by joepuzzo** [comment]
So it sounds like you want one of two things. 1. You want to create a field where the value is an array, and therefore, want to use array field. In this first case, you have values returned from a server that you want to populate into the array field. IF this is the case, you simply pass initial values. .... NOW for 2. Assuming the first case was not your intention what your actual goal is, is to Generate a form based on fields not values. IF this is the case then you simply generate the fields yourself via some mapper function. No different then if you have an array of data and use the array.map to return jsx elements

**Comment by informvisu** [comment]
Could you please take a look at it? https://codesandbox.io/s/react-informed-dynamicarrays-example-ie0cf

**Comment by joepuzzo** [comment]
Dont use array field.. just map over your fields and create `Text` inputs

**Comment by joepuzzo** [comment]
Im still not exactly sure what your goal is however. your array just has `firstName` and `lastName` do you want an array of siblings? do you want two fields `firstName` and `lastName`?

**Comment by informvisu** [comment]
Appreciated your time for looking into it. I made progress now when I pass fieldsFromServer like this
`const InformedForm = ({fieldsFromServer}) => {`
I am able to render the fields and 'add' the records, but getting ForwardRef error while 'remove'
Also, FormState should show values as an array, but overriding
[codesandbox](https://codesandbox.io/s/react-informed-dynamicarrays-example-ie0cf)
![image](https://user-images.githubusercontent.com/45706478/59120329-fc2c8d80-8909-11e9-8ae4-59d415ba15ed.png)

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/fejcm updated a few things

**Comment by informvisu** [comment]
I passed this step now. Thanks much Joe. Looks you are leaving onClick pop() and splice() up to us. I added 3 rows, when remove 2nd row it is resetting the subsequent row values. [codesandbox](https://codesandbox.io/s/react-informed-dynamicarrays-example-ie0cf)

**Comment by joepuzzo** [comment]
Thats not right... https://codesandbox.io/s/teex4 This should be what you want. Informed does take care of removing for you

**Comment by joepuzzo** [comment]
Can i close this ?
