### ISSUE TITLE
API getValues

### ISSUE THREAD

**Issue by redwallsolutions** [joepuzzo/informed#213]
Hello,

Firstly, I want to thank you for the incredible project.
I've beeing using it for at least 10 projects.

I didn't find a getValues method in the API, we need this because there's a form that is generated by dynamic fields and before submit these fields,  we need to check some values to our component mechanism.

How can we do this?

**Comment by joepuzzo** [comment]
getState().values

**Comment by joepuzzo** [comment]
Closing

**Comment by andtankian** [comment]
Thank you Joe.
