### ISSUE TITLE
Select field broken on Microsoft Edge

### ISSUE THREAD

**Issue by Jared-Frenzel** [joepuzzo/informed#215]
When selecting an option from a select field on Microsoft Edge, a TypeError with message "Invalid attempt to spread non-iterable instance" is thrown. From what I can tell, it is an issue with babel and this line https://github.com/joepuzzo/informed/blob/ac97d5819ce37098a9b98d99b8348b187bfc6630/src/components/form-fields/Select.js#L25 Cursory google led me to https://github.com/babel/babel/issues/8068, though I'm somewhat new to web development, so I'm unsure if this is the root cause.

Minimum Code for Reproduction:
https://codesandbox.io/embed/crimson-river-xezdc
```javascript
import React from 'react';
import { Form, Select, Option } from 'informed';

export const MalfunctioningSelect = () => (
    <Form>
        <Select field="sampleSelect">
            <Option value="value1">option1</Option>
            <Option value="value2">option2</Option>
            <Option value="value3">option3</Option>
        </Select>
    </Form>
);
```

Edge Version:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by joepuzzo** [comment]
I will look into this first thing tomorrow.

**Comment by Jared-Frenzel** [comment]
Looks like it's still working in https://joepuzzo.github.io/informed/?path=/story/form--complex, so it's likely a recent change. I'll see if I can pinpoint the breaking version.

**Comment by joepuzzo** [comment]
Ok yes try the latest release and let me know if its not working. Sorry i never got to this yesterday i got sidetracked by other issues.

**Comment by Jared-Frenzel** [comment]
No problem! Thanks for making such a useful library! Is there a version later than 2.11.1? That is the most recent I can see on NPM.

**Comment by joepuzzo** [comment]
Yup thats the latest so if its happening there then i need to look into it.

**Comment by joepuzzo** [comment]
But i'm confused because you said it works in the docs... making me think something is different in your code.

**Comment by joepuzzo** [comment]
I just tested this all in IE11 and it works there. Would be surprised if Edge did not support it.

**Comment by Jared-Frenzel** [comment]
It works on the Storybook site itself, but I tried running the code sample from https://joepuzzo.github.io/informed/?path=/story/form--complex and ran into the same error when using any informed version after 2.0.0. Here is another sandbox with the documentation example in it. https://codesandbox.io/embed/amazing-moser-wdorp. It appears the multiselect is also affected. Perhaps the github site is using a version prior to 2.0.0?

**Comment by joepuzzo** [comment]
Nope the github site is using the latest version.

**Comment by Jared-Frenzel** [comment]
I can't explain it then. Could you perhaps look at the code samples I provided and tell me if there is anything wrong with them? Both of them for sure won't work in Edge, but perhaps there is something wrong with the way I am using them...

**Comment by Jared-Frenzel** [comment]
You were correct, I pulled the project, and the storybook code worked perfectly. This leads me to believe that the issue is occuring somewhere in the building / uploading to npm (likely Babel?). I'll look into it some more tomorrow

**Comment by Jared-Frenzel** [comment]
@joepuzzo I found that if you replace https://github.com/joepuzzo/informed/blob/ac97d5819ce37098a9b98d99b8348b187bfc6630/src/components/form-fields/Select.js#L25 with
```javascript
let selected = Array.from((forwardedRef || selectRef).current)
```
the issue is resolved. I can create a PR if you think this is an acceptable solution!

**Comment by joepuzzo** [comment]
Sweet yeah shoot off a PR

**Comment by joepuzzo** [comment]
I just fixed it for ya 😄

**Comment by Jared-Frenzel** [comment]
Thanks so much!
