### ISSUE TITLE
ArrayField notifications

### ISSUE THREAD

**Issue by sheriffjohn** [joepuzzo/informed#216]
Hi joe, thank you for your excellent library!
One question though:

Is it possible to get the notifier field key to the target field?
In my case i have a arrayField and when i use notify="TARGET_FIELD"
I only get the value from the input and an array of all elements included in the notify targets. However I dont really know which field made the call so I cant really compare row by row such to speak. Or am I missing something?

Something like this: 

The validation function for the target field:

const passwordValidation = ( value, values, (key/ index) ) => {
console.log('value', value) //  input value from sender
console.log('values', values) // [{cat: "abc", dog: "efg"},  {cat: "qwe", dog: "rty", ...}]
console.log('key', key) // THE NOTIFIERS FIELD KEY
  return basicValidation(value) || matchValidation( value, values )
}

**Comment by joepuzzo** [comment]
Hmm interesting use case. Can you make a code sandbox for me and i can look into it?

**Comment by sheriffjohn** [comment]
Hi,
I apologize for this might be a really evil example. Its like a matrix of fields. That also is dynamic. But to demonstrate my use case where we have to validate fields horizontally and vertically I unfortanately had some problems.

Row 34 (matchValidation) is where the magic happens.
there is no way to know which index we are at, so we cant compare horizontal nor vertical row fields

https://codesandbox.io/s/silent-https-uqvzi

thanks 👯‍♂

**Comment by joepuzzo** [comment]
Ok i have solved your problem!! https://codesandbox.io/s/p10z4

**Comment by joepuzzo** [comment]
Remember you don't always have to rely on the library to accomplish your goals! Sometimes you can just "wrap" things up as i did in that sandbox!

**Comment by joepuzzo** [comment]
PS do you mind if I add your code as an example in informeds docs?

**Comment by sheriffjohn** [comment]
Oh wow, cool man! I didnt realize you could pass in parameters. This is brilliant! Guess I got one tracked by the examples. Really nice to know you have control over the validtion functions!  

validate={(value, values) => matchValidation(value, values, i)

Of course you could use the examples in the docs. Its your solution :D I am glad we could help others having these use cases. 

But really, thanks man! Knowing you can pass in parameters like that it will open up for alot of solutions imho.

the racoons are pleased!

**Comment by joepuzzo** [comment]
LOL nice! Also just a heads up. check out the gotchas section of the docs http://localhost:9001/?path=/story/gotchas--unnecessary-rendering because the only downside to this solution is excess re-rendering due to regenerated validation functions. There are ways to optimize this but really it should not be a big deal... Just want to make sure you're aware!

**Comment by joepuzzo** [comment]
Oh also i think raccoon is spelled with two c's LOL. I noticed it was one in your code.

**Comment by joepuzzo** [comment]
```
const matchValidation = (value, values, i, other) => {
  const racoons = values.racoons;

  return values.racoons &&
    values.racoons[i] &&
    value === values.racoons[i][other]
    ? 'Items cannot be the same'
    : undefined;
};
```

Update your function to be this ^^^^^ before there was small bug

**Comment by joepuzzo** [comment]
`other` is the other field so for `item1` other would be `item2`

**Comment by sheriffjohn** [comment]
Hmm, I thought item2 was included in values. So you mean other is the notify value?

**Comment by joepuzzo** [comment]
Its the field name. Check out the function from above

**Comment by joepuzzo** [comment]
Because the issue with the previous solution is that values.valueThatJustChanged. Is not the current value. `value` the first parameter to the function is the current value. Currently with the old solution its off by one render. And you have to blur to get the errrors to update

**Comment by sheriffjohn** [comment]
I dont really get that problem though. But then again I do let field item1 and item2 both notify a third field. Then I get all current values. 

But similar thing should happen if I let item1 and item2 notify each other and use same validator or am I missing something?

**Comment by joepuzzo** [comment]
Ok so heres the scenario. You type the letter `a` into `item1` text field. What happens? 

The `matchValidation` function is called with the following parameters
`value = 'a'` `values = { }` 

Do you see the issue from above ?? if you just check `values` then your valdation function will be wrong because `values.racoons[0].a` is not yet set! its not set until after. So you cant rely on getting the `value` of the field that was changed being correct in the `values` object... BUT you CAN rely on the `value` being correct

**Comment by sheriffjohn** [comment]
Thats very weird, for me when I type in a, in field item1 i get value = "a" and values =  {raccoons: [{item1: "a"} ]} in my console.log(value, values)

**Comment by joepuzzo** [comment]
Ahh you should not lol.. maybe you are getting some extra render that is solving the issue. Regardless i would make sure you code it the way described above lol because it should not be working the way it is for you.

**Comment by joepuzzo** [comment]
Also https://joepuzzo.github.io/informed/?path=/story/validation--complex-array-field-validation 

CHECK IT OUT ^^^^^

**Comment by sheriffjohn** [comment]
Haha wow! The raccoons are so happy!  ^^^^
