### ISSUE TITLE
useFieldState gives formApi.value error

### ISSUE THREAD

**Issue by aej11a** [joepuzzo/informed#218]
When I try to use `useFieldState` like this:

```    
import { Form, Text, useFormState, useFieldState } from 'informed'
const isValidPassword = () => {
        const { value: pwd } = useFieldState('pwdField');
        const { value: cpwd } = useFieldState('cpwdField');
        return pwd === cpwd;
    }
```

I get `"Uncaught TypeError: formApi.getValue is not a function"` This usage is almost exactly like the example given. Any ideas?

**Comment by joepuzzo** [comment]
So it looks like your trying to use a hook in a validation function.. this will not work. Instead just use the second parameter to the validation function ( `values` )

**Comment by aej11a** [comment]
The same error happens with `console.log(useFieldState('pwdField'));`, in a function component, outside of the return statement

**Comment by joepuzzo** [comment]
Is the functional component rendered in a form? And does a field with that name actually exist ?

**Comment by Richacinas** [comment]
> Is the functional component rendered in a form? And does a field with that name actually exist ?

In my case, yes.

I have a `Text` inside a `Form`, with a name `whatever`.

However, when I try `useFieldState('whatever')`, I get an error because at the beginning there is no value for this field so the hook tries to get it and it doesn't exist (returns undefined).

**Comment by joepuzzo** [comment]
Hmm it shouldn’t. Can u reproduce in a code sandbox?

**Comment by Richacinas** [comment]
> Hmm it shouldn’t. Can u reproduce in a code sandbox?

Ok I will. Do you happen to know of a kind of Codepen where I can work with ES6 and import NPM modules?

Please let me know, thanks a lot
