### ISSUE TITLE
ArrayField inside a Scope does not render initial values

### ISSUE THREAD

**Issue by jproffitt** [joepuzzo/informed#219]
The example in the docs (https://joepuzzo.github.io/informed/?path=/story/arrays--nested-form) shows an `ArrayField` in a form with initial values, and it works great. 

But if the `ArrayField` is inside of a `<Scope>`, then it does not render the fields initially. Something is half-working because when you click the add button, the initial values are in the inputs, it's just that the array field does not show the list of fields initially.

Here is an example: https://codesandbox.io/s/informed-arrayfield-in-scope-issue-7bfjp

**Comment by joepuzzo** [comment]
So i would suggest not using scope and instead using `field="scope.fieldName"`. I have been thinking of deprecating scope anyway because its achievable this other way and while its slightly more code its cleaner behind the scenes

**Comment by jproffitt** [comment]
Ah, that would be a bummer. I use `<Scope>` all the time, and love how it abstracts out the naming of fields. Here's a pattern I have done a few times: have a reusable react component with a list of fields, for example, address fields. Then I use that component inside scopes in multiple different places. Maybe its in a "customer_address" scope, or a "store_location" scope, etc.

**Comment by jproffitt** [comment]
Currently, I have a list of records in a table to edit, and each record has a list of sub line items. So I use a couple scopes. Without scopes, the field names for the line items would be something crazy like "data[0].line_items[0].field_name"

**Comment by joepuzzo** [comment]
Hmm yeah i see what that would do. I either need to get rid of them or update how they work. Its kind of dirty the way i implemented scope atm.

**Comment by joepuzzo** [comment]
Ok so i got you! Im working on a solve now!

**Comment by joepuzzo** [comment]
Ok this is solved!!! Pull latest release

**Comment by jproffitt** [comment]
Awesome! Thanks so much
