### ISSUE TITLE
How to trigger mapStateToProps on onChange event of the form?

### ISSUE THREAD

**Issue by nidamunir** [joepuzzo/informed#222]
I am rendering form in an inner component and accessing the state outside the form component using getApi and onChange. Now if I want to store the updated formState in redux store so that it triggers mapStateToProps in the outer component, which, in turn, receives the updated props. Will I have to dispatch the necessary actions manually or does your library provide support for that?

**Comment by joepuzzo** [comment]
Using redux via on change defeats the purpose of informed. From the docs : `"informed takes care of managing form state so you don't have to!"` There are no hookups further than onChange.
