### ISSUE TITLE
Object in Scope is converted to array if field names are numeric

### ISSUE THREAD

**Issue by mattzeunert** [joepuzzo/informed#223]
I have a form field like this:

```
 <Scope scope="obj">
  <label>
    <Checkbox field={"1000"} initialValue={false} /> Check
  </label>
</Scope>
```

I'd expect the form value to be `{obj: {"1000": false}}`, but instead `obj` is an array with 1000 items.

Repro link: https://codesandbox.io/s/numeric-field-name-ob1n5

**Comment by joepuzzo** [comment]
Hahaha. Yes so heres the deal. You need to change your field name lol. Internally I use lodash's set and get functions. It will always turn `foo.1` into `foo[1]`. This is shown in the docs here http://localhost:9001/?path=/story/inputs--intro in the `field syntax` section.

**Comment by mattzeunert** [comment]
Thanks for your reply Joe!

Do you think there's anything that can be done to detect this and show a warning message? Maybe if the field is a number and `obj.length === undefined`?

**Comment by joepuzzo** [comment]
I don't want to throw warnings for this because its an expected use case. Some people might want to use the syntax `foo.1`. And the objects value is determined by what its getting set to, not the field name.

**Comment by mattzeunert** [comment]
Yeah I think keeping the `foo.1` syntax makes sense and doesn't need a warning. I was wondering if there's a way to detect when that syntax is used on a mostly empty array, because when the component unmounts/deregisters it iterates over that array again and again, freezing the UI. As long as your indices are pretty low you wouldn't notice the issue and think everything is fine.

**Comment by joepuzzo** [comment]
What do you mean by "It iterates over that array"? Can you elaborate on it and where in the code.

**Comment by mattzeunert** [comment]
Sure, [here's a demo](https://codesandbox.io/s/numeric-field-name-2b396). Try clicking "hide form".

![Screenshot 2019-07-01 at 17 29 45](https://user-images.githubusercontent.com/1303660/60452238-05b5c680-9c26-11e9-95f0-634b6332e25b.png)

The pull call happens [here](https://github.com/joepuzzo/informed/blob/959ea41ddd3926a46cc17ea15609a9851112759e/src/ObjectMap.js#L89).
