### ISSUE TITLE
selectionDirection/Start/End throwing errors for <Input type="file" />

### ISSUE THREAD

**Issue by MattBorowiec** [joepuzzo/informed#224]
Hello, want to start off thanking you for your work, it's been a pleasure using Informed thus far. And also I know this isn't really an Informed problem, but I was wondering if you had any thoughts or advice about using Informed in my current situation.

I've created a custom field to use as a file uploader. It works great in Firefox and Chrome, but blows up on Safari. From what I can tell, the issue is that the `selectDirection/Start/End` attributes are not relevant to a file input, and should set those attributes to `null`, but Safari throws an error instead. I believe it is related to this open issue: https://bugs.webkit.org/show_bug.cgi?id=156500

I've confirmed the behavior outside of my React app and Informed, safari always throws an error for <input type="file" /> in those attributes : 
![image](https://user-images.githubusercontent.com/6430960/60463894-00468500-9c02-11e9-82f5-7238587d2508.png)

So far, all this has nothing to do with `Informed`, but since Safari is being naughty and not following the spec, the `setValue()` function blows up at this conditional:
```
if (e && e.target && e.target.selectionStart) {
  setCursor(e.target.selectionStart);
} // Now we update the value
```

Any ideas for ways to work around this? I can provide more detail or some of my code if needed.

Thanks again!

**Comment by joepuzzo** [comment]
Hmm yeah this looks like a fun one lol. So unfortunately I have not worked to much with file inputs yet myself so google will probably be more helpful then me on this one haha.

**Comment by MattBorowiec** [comment]
Ha, yea figured it was a long shot, but thanks for the quick response!

**Comment by joepuzzo** [comment]
Please put solution if you figure it out tho!
