### ISSUE TITLE
Initial values should not cause validation at first form render

### ISSUE THREAD

**Issue by ivansky** [joepuzzo/informed#225]
Even initial values are invalid, fields are not touched.

```jsx
const validate = value => {
    return !value || value.length < 5
        ? "Field must be at least five characters"
        : undefined;
};

<Form initialValues={{ color: "" }}>
    <Text field="color" validate={validate} validateOnChange={true} />
</Form>
```
Actual result:
```
"errors": {
    "color": "Field must be at least five characters"
}
```

Expected  result:
```
"errors": {}
```

Live Example:
https://codesandbox.io/s/informed-error-right-after-init-d65gr

Formik Example:
https://codesandbox.io/s/formik-validation-example-slhgv

**Comment by joepuzzo** [comment]
Yup your right.. i need to look into this. Its the combination of initial values and `validateOnChange`

**Comment by ivansky** [comment]
The current workaround is to use touched status to avoid showing error instantly.
But it doesn't look right.

**Comment by joepuzzo** [comment]
So if you use field level initial value it also works. Do that for now and i can look into this bug

**Comment by joepuzzo** [comment]
Never-mind i just fixed it 😄 pull the latest.
