### ISSUE TITLE
allowEmptyStrings is not working

### ISSUE THREAD

**Issue by dicardopegb** [joepuzzo/informed#227]
Either that or I don't know how to use it.

I'm using the latest version and react-testing-library (also latest version)

This is what I've in a test:
```
const { getByLabelText, getByTestId, container } = render((
<Form onSubmit={jest.fn()} allowEmptyStrings>
  <label htmlFor="text3">
     Text3
     <Text field="text3" id="text3" />
   </label>
</Form>
(...)
const textField = getByLabelText("Other");
fireEvent.change(textField, { target: { value: "124" } });
const submitBtn = await waitForElement(() => getByTestId("btn_save_entityName_1"));
expect(submitBtn.disabled).toBe(false);
fireEvent.change(textField, { target: { value: "123" } });
expect(submitBtn.disabled).toBe(true);
const textField3 = getByLabelText("Text3");
fireEvent.change(textField3, { target: { value: "2345" } });
fireEvent.change(textField3, { target: { value: "" } });
expect(submitBtn.disabled).toBe(false);
```

The last expectation fails. I've code that checks whether the form is actually changing the initial values before it enables the submit button, but the code is only considering properties that have CHANGED not properties that simply don't exist. This is what I see when I log the current values at the end:

`
changes: { text2: '123', amount: 2.2 } original: { text2: '123', amount: 2.2, text3: '234' }
`

I'd expect 'text3' to be '', but is simply not there.

Am I missing something?

**Comment by dicardopegb** [comment]
So I started to look at the source code again and discovered that the correct prop name at the field level is "allowEmptyString" not "Strings", could it be that this is not working at the Form level because the prop is not being passed down to the fields using the correct plurality?

**Comment by joepuzzo** [comment]
Hmm it should work both ways but i will look into it it after the holidays

**Comment by joepuzzo** [comment]
This is now fixed
