### ISSUE TITLE
Example of submitting data to an API

### ISSUE THREAD

**Issue by fjcero** [joepuzzo/informed#229]
There is an example on how to submit all the data to an endpoint, or controlling the submitting function outside the Form controller?

**Comment by joepuzzo** [comment]
Just make an ajax call in the onSubmit function

**Comment by fjcero** [comment]
@joepuzzo Form `onSubmit` is overriden here https://github.com/joepuzzo/informed/blob/master/src/components/Form.js#L43, or there is another form to declare the funcion

**Comment by joepuzzo** [comment]
You pass an onSubmit function to the `<Form onSubmit={...yourfunctionhere}>`
