### ISSUE TITLE
How to reset a form on submit with hooks?

### ISSUE THREAD

**Issue by cloudsociety** [joepuzzo/informed#230]
Hi Joe,

I found this issue: https://github.com/joepuzzo/informed/issues/76

I tried to make `getApi` work in a functional component and it doesn't work. I also tried to use hooks, but they're being fired outside the `Form` element and seem to be failing too.

```
import React, { useState } from "react";
import { Form, FormValues } from "informed";
import fetch from "isomorphic-unfetch";

import { isRequired } from "../validators";
import InputType from "../components/FormElements/Input";

const ResetPassword = () => {
  const [message, setMessage] = useState("");

  const handleFormSubmit = async (form: FormValues): Promise<void> => {
    console.log(form, test)
    try {
      const response: Response = await fetch(
        `${process.env.API_URL}/customer/lost-password`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ user_login: form.accountName })
        }
        );
      const json = await response.json();
      setMessage(json.message);
    } catch (err) {
      setMessage(err.message);
    }
  };
  return (
    <>
      <h1>Recover your account.</h1>
      <hr />
      <Form onSubmit={handleFormSubmit} >
      {({ formState }) => (
        <>

        {message !== "" && <span>{message}</span>}
        {Object.keys(formState.errors).length > 0 ? (
          <span>
            Please review the errors and try again.
          </span>
        ) : null}
        <InputType
          label="What is your username or email?"
          field="accountName"
          validate={isRequired("username or email required.")}
          validateOnBlur
        />
        <button type="submit">Recover account</button>

        </>
      )}
      </Form>
    </>
  );
};

export default ResetPassword;
```

The specific place I want the reset to trigger is inside the `handleFormSubmit` function when the fetch succeeds. Everything in here is working, but I don't know how to clear the form.

Appreciate any ideas or pointers on getting it to work.

**Comment by joepuzzo** [comment]
getApi will work.. create a codeSandbox of your scenario where it does not

**Comment by alaycock** [comment]
As a further explanation, you can still use `getApi`, but you need to store the formApi somewhere. You can't just do `this.formApi` like you could with classes. Instead, you have to use `useRef` to create a "box" where you can put the formApi.

See this example here: https://codesandbox.io/embed/informed-getapi-s18v3

One thing worth noting about that example, it might seem like you can change this line
```
const onClick = () => formApiRef.current.reset();
```
to this
```
const onClick = formApiRef.current.reset;
```
At first glance. Except you can't do that, since `formApiRef.current` hasn't been defined until after the first render is complete. 

Similarly, you aren't able to do the follow, for the same reason
```
<button onClick={formApiRef.current.reset}>Reset the form</button>
```

**Comment by joepuzzo** [comment]
Yes @alaycock is correct just `useRef`

**Comment by cloudsociety** [comment]
Nice! Thank you both! @alaycock: Thanks for the demo too. Very helpful.
