### ISSUE TITLE
Switching language using i18next doesn't refresh labels in form.

### ISSUE THREAD

**Issue by ppinel** [joepuzzo/informed#233]
Hello,

I am using `i18next` for translation. I am using it before and after a form.
Everything around the form re-render properly when I hit the switch language button. Labels inside the form aren't.

I feel like for optimisation, `Form` only re-render when necessary.
How can I force in a good way, the labels to refresh ?

**Comment by joepuzzo** [comment]
Hmm the labels should still refresh.. can you create a code sandbox for this issue?

**Comment by ppinel** [comment]
Hello @joepuzzo ,

Indeed it works on [code sandbox](https://codesandbox.io/embed/interesting-mendeleev-q6601).
I didn't reproduce the same file structure: I use lerna with several packages.
I'll try to investigate further and post any solution here.

Thanks !

**Comment by ppinel** [comment]
I found the issue. Both `ui` package and `react app` had `react-i18next`.
I removed it in `ui` package used by the react app and it fixed the issue.
