### ISSUE TITLE
Number input is failing silently

### ISSUE THREAD

**Issue by cloudsociety** [joepuzzo/informed#236]
I have a _number_ input inside of storybook. If I inspect it and click on the stepper, I can see the value increase in the inspector, but the input doesn't display a value. For a reduced, test case, I copied the number example from the Informed docks as this:

```
import React from "react";
import { Form, Text } from "informed";
import { storiesOf } from "@storybook/react";

storiesOf("Atoms/Form", module)
  .add("Input Number", () => (
    <Form>
      <label>
        Age:
        <Text field="age" type="number" />
      </label>
      <button type="submit">Submit</button>
    </Form>
  ));
```

I was on version 2.11.6 and updated to 2.11.8 with no effect. It is failing silently and I get no console logs or other things indicating an error.

Could someone confirm is this is failing everyone or just me? Thanks.

**Comment by cloudsociety** [comment]
Regular text inputs are working (text, checkbox, radio). I'm now testing with other input types.

**Comment by joepuzzo** [comment]
Im not seeing an issue with this. Can you create a code sandbox?
