### ISSUE TITLE
FormState is not updated

### ISSUE THREAD

**Issue by MrFranke** [joepuzzo/informed#238]
Hi! I have some trouble with validation match passwords. Form state is not updated after fill two passwords fields.
Look at error in sandbox
https://codesandbox.io/s/rough-dust-ghpym?fontsize=14

**Comment by joepuzzo** [comment]
hmm let me look into this. my apologies for taking so long to respond.

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/informed-validation-error-43hog

**Comment by joepuzzo** [comment]
I updated docs. Totally my fault as the docs were out of date
