### ISSUE TITLE
How to access field config within custom field implementation

### ISSUE THREAD

**Issue by mrfelton** [joepuzzo/informed#239]
Hi,

I'm creating a component using `asField` and I'd like to be able to access the field config. Specifically, to know wether `validateOnChange` or `validateOnBlur` has been set. I can't find a way to access these though as they are not available in `fieldState` or `formApi` and get stripped out of the props before being passed to my component.

**Comment by joepuzzo** [comment]
Hmm yeah that was intentional. I dont expose those because i want users to be abke to focus on there inputs and have ability to do ...props to pass down any additional native input props

**Comment by mrfelton** [comment]
I see. Well, there is probably a way to work around it by wrapping the component in a HOC which forwards the props that I need under some other name. However, I think it would be nice if you could access the form/field config via the apis. Perhaps at `formApi.config` and `fieldApi.config`
