### ISSUE TITLE
The values passed to onSubmit aren't immutable 

### ISSUE THREAD

**Issue by alaycock** [joepuzzo/informed#24]
**Reproduction steps:**
1. View: https://codesandbox.io/s/53y9kroy8n
2. Enter data into the text area
3. Click 'Submit', the submitted value should be populated
4. Click 'Toggle visibility' twice.

**Expected result:**
I would expect the object `this.value` to not change, since only the internal state of the form that has changed, and `onSubmit` has only been run once.

**Observed result:**
`this.value` is cleared.

It looks like the value passed to the `onSubmit` prop of the form isn't a clone of the values, it's the actual values themselves. When the values are cleared internally, they have also been cleared anywhere they are used directly.

A workaround is to deep-clone the `values` passed to the `onSubmit` prop, but I would expect informed to handle that for me.

**Comment by joepuzzo** [comment]
Hmm this is a good point. I can update onSubmit to pass a clone thanks for this catch

**Comment by joepuzzo** [comment]
Ok this is fixed in the latest version 1.3.9
