### ISSUE TITLE
Checkbox with value but not checked

### ISSUE THREAD

**Issue by MKostiantyn** [joepuzzo/informed#243]
Hi. I'm trying to create a Checkbox input with a set value but checkbox always "checked". Is there a possibility to implement it?

**Comment by MKostiantyn** [comment]
@joepuzzo Are you sure about "checked" props https://github.com/joepuzzo/informed/blob/master/src/components/form-fields/Checkbox.js ?

**Comment by MKostiantyn** [comment]
@joepuzzo 
https://codesandbox.io/s/zen-field-xmthr
I have a few more questions:
1. Why props "checked" doesn't work?
2. Could I get on submit action `data = {"checkbox": "value"}` because now I am getting `data = {"checkbox": true/false}` ?

**Comment by joepuzzo** [comment]
Checkboxes are boolean values always. So when you set it the field name will be either true or false.

**Comment by joepuzzo** [comment]
In other words. You dont need the “value” prop here. Just use the field name
