### ISSUE TITLE
useArrayField - formApi.getInitialValue is not a function

### ISSUE THREAD

**Issue by kallrobin** [joepuzzo/informed#244]
When trying to use the hook `useArrayField` i constantly get an error message `formApi.getInitialValue is not a function`
And when i debug the code i see this 
![Screenshot 2019-08-28 at 16 57 44](https://user-images.githubusercontent.com/23083052/63867492-38c1cf80-c9b5-11e9-96e0-aeff8a55be0b.png)

**Comment by kallrobin** [comment]
Nevermind, i was using `useArrayField` in the same component as `Form` instead of inside it.
Although i was very confused with the error message since some of the other properties on `formApi`exists.

**Comment by joepuzzo** [comment]
Yeah this is a classic outside of context issue lol. Glad you figured it out
