### ISSUE TITLE
validateOnBlur missing

### ISSUE THREAD

**Issue by imKKK** [joepuzzo/informed#248]
hi,  am trying to get my form validated using validate a form using `validateOnBlur` inbuilt method of informed. But that method seems missing, i tried updating the package and still the same issue persists,, I tried consoling the field props, in that too, its missing. can anyone plz help me out of this.

**Comment by joepuzzo** [comment]
So validate on blur is not a method. its a boolean flag to tell the form to perform validation on a blur event
