### ISSUE TITLE
Text with type="date" gives InvalidStateError in Edge

### ISSUE THREAD

**Issue by wenche** [joepuzzo/informed#249]
We want to use the native date type, but that doesn't work with Edge. It seems like it struggles with selectionStarts somehow.
![image (1)](https://user-images.githubusercontent.com/1568252/65120147-78486e00-d9ed-11e9-8523-df85d3fc3a7f.png)

Minimal example:
https://codesandbox.io/s/misty-snow-fwj8y

Using React Datepicker etc is not an option because of a11y issues.

**Comment by joepuzzo** [comment]
Apologies as i never saw this issue before. when I get a chance I will try opening in edge.

**Comment by joepuzzo** [comment]
I dont see this issue. Recreate in v4 if its still issue that you can re create
