### ISSUE TITLE
Why no wrapped Text, TextArea, Checkbox, Radio, RadioGroup and Select is not exported?

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [joepuzzo/informed#25]
I want to implement custom input. It may be very helpful if the no wrapped version of `Text` and etc. will be exported. Then I will be able to reuse no wrapped `Text` and implement custom input as kind of:
```javascript
const CustomInput = ({ fieldApi, fieldState, customProp, ...props  }) => {
  return (
    <div className={fieldState.error ? 'error' : ''}>
    {/*...*/}
      <NoWrappedText {...props} fieldApi={fieldState} fieldState={fieldState} />
    {/*...*/}
    </div>
  )
}

export default asField(CustomInput);
```

**Comment by joepuzzo** [comment]
Im confused as to what you are looking for.. I think what you want is to use the `asField` HighOrderComponent to create your own custom Text Input.

**Comment by dzwiedziu-nkg** [comment]
Yes but `Text`, `TextArea` and etc. have some code that can be reuse. Currently I must implement my custom input as:

```javascript
const CustomInput = ({ fieldApi, fieldState, customProp, ...props  }) => {
  const {
    value
  } = fieldState;
  const {
    setValue,
    setTouched
  } = fieldApi;
  const {
    onChange,
    onBlur,
    forwardedRef,
    ...rest
  } = props;
  
  return (
    <div className={fieldState.error ? 'error' : ''}>
      {/*...*/}
      <input
        {...rest}
        ref={forwardedRef}
        value={!value && value !== 0 ? '' : value}
        onChange={e => {
          setValue(e.target.value);
          if (onChange) {
            onChange(e)
          }
        }}
        onBlur={e => {
          setTouched();
          if (onBlur) {
            onBlur(e)
          }
        }}
      />
      {/*...*/}
    </div>
  )
};

export default asField(CustomInput);
```

Do you see how many code can be reuse when you export `const Text ...`?

**Comment by joepuzzo** [comment]
Im sorry but i dont?

**Comment by joepuzzo** [comment]
Maybe an example would help

**Comment by joepuzzo** [comment]
Also it looks like you have two issues out for the same thing.. can we delete one and consolidate.

**Comment by joepuzzo** [comment]
Ok you may have convinced me however i want to try somthing before i do this.. im not at my comp atm but will be in an hour and i can let ya know

**Comment by dzwiedziu-nkg** [comment]
It's works but see please: you create new component in each render! You lost any React's optimizations!

**Comment by dzwiedziu-nkg** [comment]
https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method

**Comment by joepuzzo** [comment]
Ok i think you have convinced me

**Comment by joepuzzo** [comment]
This is in the latest version! Will add better docs soon but you can check out the custom inputs section that i added
