### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by mattbasta** [joepuzzo/informed#250]
- `touched` isn't a good proxy for knowing whether the form has changed. Currently I use a `useEffect` on `JSON.stringify(formState.values)`, but that doesn't give a good signal for whether any of the values in the form differ from those provided to `initialValues`.
- As far as I know, without iterating `formState.touched` and calling `setTouched(key, false)` on each truthy member, it's not possible to reset touched on all fields.

I'm building a system to allow the user to create drafts, and loading a new draft would reset `touched` on any fields. Knowing whether anything has changed from the default would allow me to disable/enable the "Save draft" button appropriately.

Thanks for your time working on this project. Are these changes something you'd be open to receiving PRs for?

**Comment by AntowaKartowa** [comment]
Totally agree. Don't understand the meaning of that property if it doesn't show whether value differes from initial or not. From my experience such property broadly used almost in every project and it is included in Angular reactive forms and in Redux form. Informed my favorite form library, and it is the only disadvantage that forces me to write cumbersome custom comaprison logic. Whyyy? Also as far as I know touched became true for all fields after submit. Logic behind this also not clear for me. 

This question already been raised about a year ago. And for some reason authors treat it as a feature.

**Comment by joepuzzo** [comment]
I am the author and this is a feature. In order to be backwards compatible and support this request i need to add a new flag that is neither “dirty” or “touched” that is specific to initial values.
