### ISSUE TITLE
TypeScript: useField, asField

### ISSUE THREAD

**Issue by AntowaKartowa** [joepuzzo/informed#252]
Hi. In definition for `useField` missed second parameter `ref`.

And maybe someone could point me to the right direction. When I am writing custom Input blocks with help of `asField` HOC I am using `fieldState` parameter. Just like in tutorial about ErrorText. And if I define props as `MyCustomProps & BasicFieldProps<...` than on the pages TypeScript highlights my components because I don't pass `fieldState` and `fieldApi`. If I remove or make optional `BasicFeildProps<..` than TypeScript starts warning me inside my custom input component because of use `fieldState`. 

Thank you.

**Comment by andtankian** [comment]
Hello @AntowaKartowa 
I tried to reproduce your error and couldn't get to a solution for this issue.

You can workaround it by switching to `useField` hook instead `withField` HOC.

I did something like this:

```
interface CustomProps {
    //your custom props
    field:string,
    initialValue:any
}
```
Notice that I 'overloaded' a few required informed input props to `useField` hook to work properly. The `field` and `initialValue` props are some of them. There's more like, `mask`, `validation` etc. It will depend on your requirement component.

And then...

```
const MyField:React.FC<CustomProps & InputHTMLAttributes<HTMLElement>> = ({
    //your custom props,
    field,
    ...rest
}) => {
    const {fieldState, fieldApi, ref, render} = useField({field, initialValue})
    return render(
        <input {...rest} ref={ref}/>
    )
}
```
No errors in the component neither in the other files that use it. :)

Hope it helps.
