### ISSUE TITLE
Validation on ArrayField does not remove errors from state

### ISSUE THREAD

**Issue by MKostiantyn** [joepuzzo/informed#256]
Hi @joepuzzo 
You could reproduce it on your site https://joepuzzo.github.io/informed/?path=/story/validation--complex-validation
Steps to reproduce:
1. Submit empty form. You will see several errors.
2. Fill each field.
3. Submit form again. You will see that errors of ArrayFields does not remove from state.

**Comment by joepuzzo** [comment]
Can confirm this is an issue and I will look into it

**Comment by joepuzzo** [comment]
This is now fixed!!!!
