### ISSUE TITLE
ArrayField - empty items fading after deleting it

### ISSUE THREAD

**Issue by DenisBelkin** [joepuzzo/informed#258]
Hello! 
I found a problem which is similar to this issue [#240 ](https://github.com/joepuzzo/informed/issues/240)

**Problem**:
After deleting empty field, also can be deleted other empty ones 
+the last existing one will be duplicated(not always, but in situations like my example it does) 

**Example**:
I found it on your [Dynamic Arrays](https://joepuzzo.github.io/informed/?path=/story/arrays--dynamic-arrays) docs page

**How to find it**:
As default we have 3 sub-fields.

-  Create 3 more
-  For better experience fill them like this: 
   // '' - it means i didn't fill it at all. In your example it will be written like 'null'
   0: 0,
   1: 1,
   2: '' ,
   3: 3,
   4: '',
   5: 5

- Click on Remove button under '4'
- Finish. You got it. On removing '4' app removed '2' from values too 
+'5' was duplicated

**Comment by joepuzzo** [comment]
Try adding allowEmptyStrings to the form. Its a prop

**Comment by DenisBelkin** [comment]
Yeah, it's worked...but...
I found another problem:

My example: https://codesandbox.io/s/happy-bose-xzjze

1. Create 4 more items
2. Fill the 5th 
3. Delete the 4th

Value of 5th field was removed

**Comment by DenisBelkin** [comment]
When i removed the '0' item, values of all items were removed too

**Comment by joepuzzo** [comment]
Your problem is the key needs to be on the div!

**Comment by joepuzzo** [comment]
You have the key on the label. This is a simple fix and a react thing :)

**Comment by DenisBelkin** [comment]
You right
Now all things are working)

Thank you for your time :)
