### ISSUE TITLE
ArrayField - Duplication of the last item on remove

### ISSUE THREAD

**Issue by DenisBelkin** [joepuzzo/informed#259]
[#258 ](https://github.com/joepuzzo/informed/issues/258)
> Finish. You got it. On removing '4' app removed '2' from values too
+'5' was duplicated

Hi again :)

I found the way how to reproduce bug with duplication of the last field.
Example: https://codesandbox.io/s/gallant-rosalind-11nw9
1. Create 4 more items
2. Fill 6th and 4th
3. Remove 5th
4. We can see the duplicate in console.log

**Comment by joepuzzo** [comment]
Sorry just getting back to this.. yup im seeing the issue too. Will look into it

**Comment by joepuzzo** [comment]
Ok so funny story. This caused me to write a V3 that is 100% backwards compatible but fixes this issue lol. Will release soon!

**Comment by joepuzzo** [comment]
V3 is out and this is fixed
