### ISSUE TITLE
Using  number for field name ends sending the value as empty array

### ISSUE THREAD

**Issue by yossiHav** [joepuzzo/informed#260]
First great package ...
one problem I've come with, when the field name is a number then the value i'm getting is an empty array
for example:

<Checkbox ...
 field='123456'
....
/>

I've bypass it adding string as prefix before the name, which forcing me to run over the values when sending them to the server in order to clean the prefix and run over when returning in order to select the relevant checkboxs. in this is for case that i'm coming for other route for example

Thanks

**Comment by joepuzzo** [comment]
Yeah this is a limitation of informed's design. Numbers are not supposed to be used as field names unless they are in array fields. I would double check your design to make sure its correct. If you start building fields like `siblings.1 siblings.2` etc.. then you should prob be using array field

**Comment by yossiHav** [comment]
It’s a mix of fields coming from the server most of them are strings but some are long numbers,
Can u send me an example for fields array, it is not clear

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?path=/story/arrays--array-of-fields

https://joepuzzo.github.io/informed/?path=/story/arrays--dynamic-arrays
