### ISSUE TITLE
Getting errors in form api hooks

### ISSUE THREAD

**Issue by victorbf** [joepuzzo/informed#261]
I'm getting this error every time i try to use a function in formApi hooks
`Uncaught TypeError: formApi.setValue is not a function`

Here is what i'm getting by consoling logging it:
<img width="331" alt="Screen Shot 2019-12-19 at 18 22 14" src="https://user-images.githubusercontent.com/7563794/71210869-b1aea500-228c-11ea-8db5-191695ca3dc1.png">

Here is my code:
<img width="955" alt="Screen Shot 2019-12-19 at 18 29 01" src="https://user-images.githubusercontent.com/7563794/71211238-7365b580-228d-11ea-9044-cbd083e7f34c.png">

I'm using version **2.3.0** but i already tried to upgrade it.

**Comment by CRGavrila** [comment]
You can try this insteand of useFormApi:

`
                   <Form>
                    {
                        ({ formState, formApi }) => (
                          <>
                               <Field field="fieldName"/>
                               <button
                                   onClick={ev => {
                                      formApi .setValue('fieldName', 'test');
                                      // or
                                      // formApi .setValues({ 'fieldName': 'test' });
                                   }}
                               >
                                   click button
                               </button>
                          </>
                        )
                    }
`

**Comment by victorbf** [comment]
Thanks that work it! But i solved as well, hooks works only in the children component not in the one who is calling the FORM component. Sorry about that.

**Comment by joepuzzo** [comment]
^^^^ @victorbf yes you cant use hooks outside of the `<Form />`

**Comment by brendanfalkowski** [comment]
Got stuck on this too. Maybe the docs for `useFormApi` and `useFieldApi` aren't the best examples.

Almost all our forms (so far) are fully contained in one-file/one-component for simplicity (ex: contactForm.js). I wouldn't have figured it out without the comment from @CRGavrila.

Re-posting that code with formatting for future reference.

```jsx
<Form>
    {({ formApi }) => (
        <Fragment>
            <Field field="fieldName"/>

            <button onClick={() => formApi.setValue('fieldName', 'go bananas')} >
                click button
            </button>
        </Fragment>
    )}
</Form>

```

**Comment by joepuzzo** [comment]
This ^^^ is in the docs on the first page
