### ISSUE TITLE
Informed notify undefined for debounced field

### ISSUE THREAD

**Issue by CRGavrila** [joepuzzo/informed#262]
Typecheck of notifier.notify where component with field name has been unmouted. Maybe needs to be if (notifier && notifier.notify)?

To reproduce: 

0. open console from web developer toolbar
1. go to: https://codesandbox.io/s/informed-notify-undefined-z6z79
2. click button
3. write in text input something
4. in less than 2 seconds click outside of dialog
5. check console
![Capture222](https://user-images.githubusercontent.com/23153291/71241193-b23e4e80-2313-11ea-8afa-95eae32f3de4.PNG)

**Comment by joepuzzo** [comment]
This is a good point. Im currently working on an internal rewrite and will put in this fix when i do

**Comment by joepuzzo** [comment]
This is fixed in V3. Will release soon!
