### ISSUE TITLE
Clarify docs about "values" parameter from onSubmit is NOT a POJ (plain old object)

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#263]
Using like this:

```javascript
        <InformedForm
          className="ui form"
          initialValues={loadedConnection}
          onSubmit={values => {
            saveConnection(values);
          }}
          getApi={setFormApi}>
```

Is wrong if `saveConnection` expects a POJ simple object; as values is NOT a POJ.

I was stuck on not understanding why Axios was not serializing my data (from values) to the server; I've solved it by doing this:

```javascript
        <InformedForm
          className="ui form"
          initialValues={loadedConnection}
          onSubmit={values => {
            const newObj = Object.assign({}, values); // Create a POJ from receives `values` thing...
            saveConnection(newObj);
          }}
          getApi={setFormApi}>
```

Maybe some clarify on the docs would save some other developers this headache.

**Comment by joepuzzo** [comment]
Values is absolutely a plain old js object. You should not have to Object.assign ... something else must be wrong
