### ISSUE TITLE
Touched property doesn't get updated after release v2.0.0

### ISSUE THREAD

**Issue by bohdanbirdie** [joepuzzo/informed#264]
Basically `touched` prop from the form state is always an empty object starting from version 2.0.0

Is this by the design?
Looks like here it is alright
https://joepuzzo.github.io/informed/?path=/story/hooks--useformstate

**Comment by CRGavrila** [comment]
@2.11.16 works, if you have to use fieldApi.setTouched(true) if you are using asField for custom fields

**Comment by bohdanbirdie** [comment]
@CRGavrila thanks

**Comment by bohdanbirdie** [comment]
Hmm, probably this is not what I'm expecting
it works ok in the V1, even with custom inputs

**Comment by CRGavrila** [comment]
You should make a sandbox, codepen

**Comment by joepuzzo** [comment]
Create a code sandbox so i can see if there is an issue.

**Comment by joepuzzo** [comment]
Closing as this does not seem to be an issue. Reopen if you have sandbox
