### ISSUE TITLE
Issue with v2.11.17

### ISSUE THREAD

**Issue by aballister** [joepuzzo/informed#267]
There is some issue with new version. My whole app get stuck when trying to put some value to the inputs

**Comment by joepuzzo** [comment]
Are there any logs in your browser?

**Comment by joepuzzo** [comment]
Also can you recreate in code sandbox?

**Comment by aballister** [comment]
No, there are nothing in logs. Looks like the problem is with validation
https://codesandbox.io/s/strange-night-gz57c?fontsize=14&hidenavigation=1&theme=dark

**Comment by joepuzzo** [comment]
That code sandbox is the default sandbox?

**Comment by joepuzzo** [comment]
And looking into it now! stand by

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/informed-issue-267-fg9t4

**Comment by joepuzzo** [comment]
I created a sandbox and it seems to be working fine. Can you manipulate that sandbox to recreate issue?

**Comment by joepuzzo** [comment]
As a heads up I'm also releasing V3 today ( 100% backwards compatible ) Its just a more streamlined code. Will continue to track this and fix in that version if it turns out to be an issue

**Comment by aballister** [comment]
If i define form body through "component" prop it still breaks 
https://codesandbox.io/s/informed-issue-267-vsigx?fontsize=14&hidenavigation=1&theme=dark

**Comment by joepuzzo** [comment]
Found the issue. It was an update that came in that version. I will remove that update and rethink it.

**Comment by joepuzzo** [comment]
This should be fixed now

**Comment by aballister** [comment]
It works! Thanks.
