### ISSUE TITLE
After trigger validate() (Form Api) it always try to submit form

### ISSUE THREAD

**Issue by mathiasms14** [joepuzzo/informed#268]
I am working on some MultiStep Form, I mean a way to have several pages (forms) to then submit all the values at the end. I am trying to validate the current Form everytime that the user click the button "continue". The idea is to only allow the user to move forward if the current Form is valid. So my idea is to trigger the validate() method everytime the user press the "continue" button, the problem is after the first validate() then the form try to submit without any reason (instead of going to my next page). My questions is .. Is any way to cancel that submit after the validate() ?

**Comment by joepuzzo** [comment]
Ok so yes! What you need to do first is NOT make the "NEXT" button a submit button. Each step in the multistep form should simply trigger validate manually via `formApi.validate()` and then decide based on the form state if it should move on.

**Comment by joepuzzo** [comment]
@mathiasms14 you have inspired me to add a feature to informed!!!! I just solved all the annoying problems of multistep forms!!!! I will now expose a `next` and `back` function from `formApi` and also a `step` state in `formState`. Working on docs now!

**Comment by mathiasms14** [comment]
Great @joepuzzo ! let me know when you finish that feature!! really excited to use that feature :)

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?path=/story/multistep-forms--basic-multistep Done!!!

**Comment by mathiasms14** [comment]
great job !!! I will start working with this on the next days ! thanks man :)
