### ISSUE TITLE
form does not update values with `formApi.setValues` when called inside getApi

### ISSUE THREAD

**Issue by DeadIine** [joepuzzo/informed#269]
Hi there,

I'm currently working on and older project where I tried to update all dependencies. One dependency was `informed` from `v1.x ` to the current `v3.x`. Following functionality seems to work differently:

```javascript
 
  setFormApi = (formApi) => {
    this.formApi = formApi;
    const filters = this.getFilterValuesFromUrl();  // {.. some object with keys matching my field names (retrieved from url params) ...}

    this.formApi.setValues(filters);
    this.filtersUpdated(this.formApi.getState());
  };

[... more code ...]

return  <Form getApi={this.setFormApi}> [..fields..] </Form>
```

**Previous behavior:**
Once `this.formApi.setValues(filters);` was called, the next line with `this.formApi.getState()` returned the state with the values that where set correctly. 

**Current behavior:**
Once `this.formApi.setValues(filters)` is called, the next line with `this.formApi.getState()` returns the state but the values are empty. 

To me it seems like `setValues` is called, before the Fields/Inputs are actually registered to the Form and therefore can't be set properly? So `getApi` is called, before the Form is done rendering/registering the fields.

This is also comfirmed by an error output when I specifically set `this.formApi.setValue("operator", "Foo")`. The output says, that the Field `"operator"` was not found although it's part of the Form
```javascript
<Form> [..operator field here ..]</Form>
```

Codesandbox to reproduce this: https://codesandbox.io/s/silly-mclean-xg1ev?fontsize=14&hidenavigation=1&theme=dark

**Comment by joepuzzo** [comment]
Yup so setting values and instantly attempting to get them will not work as it takes time to propagate up to the form state. 

With regard to the second part. You should not attempt to set a value "onMount" if you need that functionality then you should use `initialValues`

**Comment by joepuzzo** [comment]
Basically I think this is an easy fix. I think all you need to do is call this `const filters = this.getFilterValuesFromUrl()` and then pass filters into the `<Form />` as `initialValues`

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/eager-heisenberg-ie8ge

**Comment by DeadIine** [comment]
Thanks for your quick response!

Unfortunately this wont work for my use case, as we are doing some more stuff with the values inside `  this.filtersUpdated(this.formApi.getState());` (e.g. dispatch events/actions to unset loading)

I was just trying to figure out if this is intended or not, because if this is the behavior of `v3`I'll need some bigger refactoring of the whole logic. Hasn't been updated in a while 😄 

But I guess this will give us reason now to do so. Thanks again !

**Comment by joepuzzo** [comment]
No problem.. and sure but i think it would be easy to refactor you code to call your filtersUpdated function and then set the values. I would need to see the code more.

**Comment by DeadIine** [comment]
Yea, I'm sure I'll finde a solution. Thanks! I'll close this.
