### ISSUE TITLE
Parsing a single text box into multiple fields

### ISSUE THREAD

**Issue by zenithlight** [joepuzzo/informed#270]
Say I had a single text box, and I would like to parse its value and assign the result to several fields in my form. Is that possible?

Something along these lines:

    class OrderForm extends React.Component {
        parseAddressLine1 = (addressLine: string) => {
            // some logic to parse an address
            return [houseNumber, streetName];
        }

        render() {
            return (
                <Form>
                    <Text field={["house_number", "street_name"]} parse={this.parseAddressLine1} />
                </Form>
            );
        }
    }

**Comment by joepuzzo** [comment]
Ok so yes.. you could add an on change to the text field. Then call your parse function. Then call setValue on each of the several fields.

**Comment by joepuzzo** [comment]
You would need to get access tot he formApi to call the setters but thats easy and can be done with the `useFormApi` hook or the `apiRef` You can see both those use cases in the intro on docs

**Comment by zenithlight** [comment]
Thank you for such a quick response! I will give it a try.

**Comment by joepuzzo** [comment]
Let me make a code sandbox. This sounds like fun stand by :)

**Comment by joepuzzo** [comment]
@zenithlight Here you go! 

Type this in the address field: `111 Whoville dr, WhoVille, NH, 12345`

https://codesandbox.io/s/adress-informed-issue-270-oct4s
