### ISSUE TITLE
Add types for multi-step form 

### ISSUE THREAD

**Issue by joykliu** [joepuzzo/informed#271]
No types definition for `back`, `next`, `step`, and `setStep` in form state or form API - 

![Screen Shot 2020-02-18 at 3 09 25 PM](https://user-images.githubusercontent.com/7015521/74773865-b4b01c80-5260-11ea-84e4-28708b2a3257.png)
![Screen Shot 2020-02-18 at 3 09 34 PM](https://user-images.githubusercontent.com/7015521/74773866-b4b01c80-5260-11ea-92a3-e29d64e57c89.png)

**Comment by joepuzzo** [comment]
This is now fixed thanks

**Comment by joykliu** [comment]
@joepuzzo Amazing thank you!!!
