### ISSUE TITLE
Questions when using multiStep form with dynamic steps/pages

### ISSUE THREAD

**Issue by KLC215** [joepuzzo/informed#273]
Hi,

I am creating a multi-step form with dynamic steps/pages and facing some problems.

Here is the simplify code. https://stackblitz.com/edit/react-kw8ntc

The scenario of my case is

1. Fill `Reference No.`,
2. Check `Step 3`, then click `Next`
3. Fill all fields, then click `Previous`
4. Uncheck `Step 3`, check `Step 4`, then click `Next`
5. Fill all fields, and click `Submit`.

The form cannot be submitted. I think it keeps `Step 3` error status.

I tried to remove the statuses by using `setValue`, `setTouched`, `setError` but it seems not working.

My questions are:

1. Is it a correct way to reset status(values and errors) for specific fields?
2. Is there any simple way to remove the whole (step/page)'s values?
3. Is there any way to set `keepState` to the `Step/Page` instead of fields?
4. What is the purpose of setting `step` on the field?

Sorry to bother you with so many questions, but thank you for your patience.

**Comment by joepuzzo** [comment]
So first your not using the step field correctly. The step field should be a static number that lets informed know what step that field is on. That was it knows if it needs to validate the field

**Comment by joepuzzo** [comment]
Also the use case is interesting. Its basically dynamic steps. I need to look into this and build an example.

**Comment by KLC215** [comment]
> So first your not using the step field correctly. The step field should be a static number that lets informed know what step that field is on. That was it knows if it needs to validate the field

I see...

> Also the use case is interesting. Its basically dynamic steps. I need to look into this and build an example.

Thanks. I will wait for your example.

**Comment by joepuzzo** [comment]
Ok so I got you! I have refactored and added some cool shit! Stand by for another 20 minutes and I will update the docs!

**Comment by joepuzzo** [comment]
Done! https://joepuzzo.github.io/informed/?path=/story/multistep-forms--complex-multistep

**Comment by KLC215** [comment]
Thank you so much and I will give it a try tomorrow :))

**Comment by KLC215** [comment]
Finally, I implemented this approach into my project and it works pretty well.

I really like the `setCurrent` function, it's so handy with my step navigation menu.

Thank you so much.

**Comment by joepuzzo** [comment]
Glad I could help!

**Comment by PhilObi** [comment]
> Done! https://joepuzzo.github.io/informed/?path=/story/multistep-forms--complex-multistep

Is this functionality still available I get redirected whenever I use the link.
i
