### ISSUE TITLE
Radio without RadioGroup

### ISSUE THREAD

**Issue by brendanfalkowski** [joepuzzo/informed#274]
We have several UIs that use radio inputs and that don't fit the `RadioGroup` concept (a visually grouped field with three options). 

## The error 

Importing `Radio` without using `RadioGroup` returns this error:

```
Uncaught TypeError: Cannot read property 'radioGroupApi' of undefined
```

## Example UI Screenshot

The radio options themselves are scattered within the UI, or in other contexts they reveal sub-forms when selected.

![Screen Shot 2020-02-26 at 2 08 23 PM](https://user-images.githubusercontent.com/214924/75392734-81454180-58a1-11ea-815e-e08d4883ae3d.png)

## Question

I'd like to be able to just associate the fields manually by `name` prop and ignore `RadioGroup`.

Is it possible to use `Radio` this way? Or is a custom component needed?

**Comment by joepuzzo** [comment]
So you would have to create a custom radio. This is simple to do tho. Just check out the custom fields section of the docs. I would be careful however. Typically using radios as checkboxes is not an accessible way of implementing a form. Radios are, by design, supposed to be used as a group. So I always ask when this question comes up, “why not just use a checkbox”? :)

**Comment by brendanfalkowski** [comment]
Thanks for the quick reply, I'll go down that path.

We are always using them as a group (per how the `name` attribute works in HTML) but they're not visually a group in close proximity.

Ex: in the screenshot, you can only select one default account. Alternative UI: selecting among payment methods which reveals sub-forms per method. These are the major UI cases we're trying to support.

**Comment by joepuzzo** [comment]
Yup that is totally fair. I would in that case render a checkbox in one case and radio group in the other.

**Comment by brendanfalkowski** [comment]
I think I'm pretty close with a custom component, but not really sure how `fieldState` works in this case.

Component definition:

```js
import React from 'react';
import PropTypes from 'prop-types';
import { asField } from 'informed';

import css from './radioSingle.css';

const RadioSingle = asField(({ fieldState, fieldApi, ...props }) => {
    const { value } = fieldState;
    const { setValue, setTouched } = fieldApi;

    const {
        defaultChecked,
        forwardedRef,
        id,
        isDisabled,
        label,
        onBlur,
        onChange,
        type,
        ...rest
    } = props;

    const rootClass = (isDisabled) ? css.root_disabled : css.root;

    console.log(fieldState);
    return (
        <label className={rootClass} htmlFor={id}>
            {/* "type" must arrive via props, or Informed will set "undefined". */}
            <input
            className={css.input}
            checked={true}
            id={id}
            onBlur={e => {
                setTouched(true);
                if (onBlur) {
                    onBlur(e);
                }
            }}
            onChange={e => {
                setValue(e.target.value);
                if (onChange) {
                    onChange(e);
                }
            }}
            ref={forwardedRef}
            type={type}
            value={value}
            {...rest} />

            {(fieldState.value) ? <div className={css.icon} /> : null}

            <span className={css.label}>
                {label}
            </span>

            {fieldState.error ? (
                <div>{fieldState.error}</div>
            ) : null}
        </label>
    );
});

RadioSingle.propTypes = {
    defaultChecked: PropTypes.bool,
    id: PropTypes.string.isRequired,
    isDisabled: PropTypes.bool,
    label: PropTypes.node.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.string,
    value: PropTypes.node.isRequired
};

RadioSingle.defaultProps = {
    defaultChecked: false,
    id: null,
    isDisabled: false,
    label: null,
    name: null,
    type: 'radio', // Must pass this way, or Informed will set undefined.
    value: null,
};

export default RadioSingle;
```

Using it:

```jsx
<RadioSingle
checked={true}
id="radio-single-1a"
label="Alpha"
name="radio-single-1"
value="alpha" />
```

When I click on the input it logs:

```js
{
    value: undefined,
    error: undefined,
    touched: true,
    maskedValue: undefined
}
```

I'm not really sure why `value` is undefined or how to determine if the input is checked using state. Weirdly, unless I explicitly passed a `defaultProp` for `type = radio` I couldn't get the HTML to render without stripping the `type` attribute.

**Comment by joepuzzo** [comment]
Make the input type=“checkbox” then style the checkbox. Look at the source code on my github for the checkbox form field. Only difference is that you will style it but 1. Hiding the default checkbox. And 2. Adding a round looking one!
