### ISSUE TITLE
`preventEnter` not part of BasicFormProps

### ISSUE THREAD

**Issue by joykliu** [joepuzzo/informed#276]
Per title - `preventEnter` should be part of `BasicFormProps`

<img width="328" alt="Screen Shot 2020-03-02 at 9 35 29 AM" src="https://user-images.githubusercontent.com/7015521/75685785-2331a900-5c69-11ea-94e8-86f9b29855a4.png">

current `BasicFormProps` - 

```ts
  export interface BasicFormProps<V = FormValues> {
    allowEmptyStrings?: boolean
    onSubmit?: (values: V) => void
    preSubmit?: (values: V) => V
    initialValues?: V
    onChange?: (formState: FormState<V>) => void
    onValueChange?: (values: V) => void
    dontPreventDefault?: boolean
    getApi?: (formApi: FormApi<V>) => void
    onSubmitFailure?: (errors: { [key in keyof V]: FormError }) => void
    validate?: (values: V) => FormError
    validateFields?: (values: V) => { [key in keyof V]: FormError } | undefined
  }
```

**Comment by joepuzzo** [comment]
Yup sorry thats a mistake. Im currently traveling but will fix and get a new version out as soon as i can!

**Comment by joepuzzo** [comment]
To clarify i will fix by end of day :)

**Comment by joykliu** [comment]
thank you! @joepuzzo

**Comment by joepuzzo** [comment]
This is now fixed and in the latest release

**Comment by joykliu** [comment]
works! thank you :)
