### ISSUE TITLE
useFieldState does not work when FieldArray contains objects

### ISSUE THREAD

**Issue by amitava82** [joepuzzo/informed#280]
Here is a simple example: https://codesandbox.io/s/cranky-bush-l9cvc?fontsize=14&hidenavigation=1&theme=dark

Form state looks like ```{ siblings: [{ name: "foo" }, { name: "bar" }] }```. If siblings is simple array then it works.

I'd like to render dynamic form based on value of each sibling so I need to get hold of the value. Don't want to use formState for performance and for the fact that I'll have nested FieldArray.

**Comment by createadrln** [comment]
I think I have the same issue. `useFieldState()` on field id throws warnings because it hasn't been rendered yet. Still "works" but throws warnings (can't find field) and has poor performance. Prior to the update the hook would still recognize all the fields in the array even if they hadn't met the dynamic conditions.

**Comment by joepuzzo** [comment]
Sorry im just seeing this.. been busy. Hmm so yes this is very interesting use case and somthing that i think should be supported. But this may not be easy as the useFieldState current gets the field from the FormControllers fields map. And at the the time the array field itterates that field does not exist 🤔

**Comment by createadrln** [comment]
Yes that is what I've noticed. It seemed like the update was because it needed to work with newer versions of React. So I get that, I'm just a little blocked on how to work around the issue.

**Comment by joepuzzo** [comment]
This actually works your sandbox has the wrong field name

**Comment by joepuzzo** [comment]
`const { value } = useFieldState(field);`
Should be 
 ` const { value } = useFieldState(`${field}.name`);`

**Comment by joepuzzo** [comment]
The latest version is now optimized to also limit these warnings with array fields ( only happens on first render )

**Comment by amitava82** [comment]
Cool!
