### ISSUE TITLE
How to use initialValues from useState

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#281]
I’m loading some API data on a useState var, and then trying to put that on an Informed form via initialvalues

But it is not working. I suspect that the form is not re-rendering on initialvalues change?

**Comment by joepuzzo** [comment]
Initial values are meant to be just that: initial values. Technically i think there is an internal useEffect that would allow for your use case.. however it sounds like you may also want to consider using `setValues` api function.

**Comment by joepuzzo** [comment]
https://github.com/joepuzzo/informed/blob/master/src/hooks/useForm.js#L28 

See here ^^^ where i memoize the creation of form options and then below use a `useEffect` to update the `"options"`. It wound work if the state object you have is the same each render.

**Comment by jacargentina** [comment]
@joepuzzo 

Please take a look, very simple example I've put on my fork.

Simple demo on the Basic Form story. Form shows with "First name = hello1" and then after 2 secs _it should_ show with "First name = hello2"

**Comment by jacargentina** [comment]
@joepuzzo have u looked at this?

**Comment by KevinHewson** [comment]
I wouldn't expect the Text field to be updated by changing `initialValues` since it's not an initial value anymore.  I believe that prop is intended for the first render of the form.  I think in this case you would want to use the API to set the values on the form.

**Comment by jacargentina** [comment]
@KevinHewson in react development, almost normally, when you load data from an API, the Form can have a *first render* and the later (when data arrives) there will be the *"form is no ready with actual some data to edit" render*

In short, `initialValues` are not there on the first pass, and will be available a little later.

Your solution is Ok, but would be nice if this use case (loading data for that Form) is much direct/intuitiv/easier to program as it is now.

**Comment by joepuzzo** [comment]
V4 is out. All new issues need to be re logged if they are still issues
