### ISSUE TITLE
Is it possible to disable (or enable) a field by the API ?

### ISSUE THREAD

**Issue by gitfreud** [joepuzzo/informed#283]
I didn't find the easy way to disable dynamically an input field. Does something exist with the formApi ?

`<Text field="name" disabled />`

**Comment by joepuzzo** [comment]
disabled is a dom property so you need to pass it to the input like you're doing above.

**Comment by gitfreud** [comment]
So, I have to use the props to change its value ?

`<Text field="name" disabled={ props.isDisable} />`

**Comment by joepuzzo** [comment]
Yeah it has nothing to do with informed. Its a dom property :)
