### ISSUE TITLE
Basic multistep form example throws "React state update" warning in NextJS

### ISSUE THREAD

**Issue by dave-cross** [joepuzzo/informed#285]
Hi Joe, 

I'm trying to get your Basic Multistep example working in NextJS. It seems to work, but I get the following warning and don't know how to clear it. The error shows up for me after the second step is completed (the "lastname" step, but I've tried the complex example and get it after the "allergies" step too). We've used Informed on a few other projects and never seen this warning until now.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in asField(Text) (at newflow/index.tsx:20)
    in label (at newflow/index.tsx:18)
    in div (at newflow/index.tsx:17)
    in FirstName (at newflow/index.tsx:89)
```

NextJS@9.3.6
React@16.13.1
Informed@3.8.0

Any ideas? I don't think it's the SSR part of Next since it only happens after the second step and by then, the app has hydrated, but I'm open to any suggestions.

Thank you.

**Comment by joepuzzo** [comment]
Hmm I dont use next and cant seem to reproduce. Can you try reproducing in a code sandbox?

**Comment by cloudsociety** [comment]
Codesandbox was doing some weird caching and breaking things worse when I tried to create a demo there. They run NextJS in a container.

I created a small repo with Next, Typescript, and Informed. https://github.com/cloudsociety/next-informed

It has two pages:
- `localhost:3000/` is kind of where I'd like to go with this. Some controls that are disabled if the user hasn't hit that step yet.
- `http://localhost:3000/basic` is the basic example copied from your repo.

In both cases, you'll see the warning message appear in the browser console when moving through the steps. The warning messages don't appear in production builds, but I'm worried that ignoring them will lead to bugs down the line.

Hopefully, I'm just missing something. Please let me know if I am.

**Comment by jacargentina** [comment]
@joepuzzo NextJS as nothing to do with it. I could reproduce it with current master sources, using `yarn start`

Simply do this: 
1. go to `http://localhost:9001/?path=/story/multistep-forms--basic-multistep`
2. Fill the entry with something that validates OK
3. Clic NEXT without any value on the second step entry.
4. Look at the console

<img width="990" alt="Captura de Pantalla 2020-06-30 a la(s) 16 39 41" src="https://user-images.githubusercontent.com/517228/86169728-6e14dd80-baf0-11ea-8c9f-d09ceea12c5e.png">

**Comment by joepuzzo** [comment]
You must not be running the latest code ;)

**Comment by jacargentina** [comment]
# I'm with latest sources, directly from current master on Github

My clone:
<img width="736" alt="Captura de Pantalla 2020-06-30 a la(s) 17 13 28" src="https://user-images.githubusercontent.com/517228/86172640-19c02c80-baf5-11ea-8ac1-7c1910371b72.png">

Github:
<img width="402" alt="Captura de Pantalla 2020-06-30 a la(s) 17 13 21" src="https://user-images.githubusercontent.com/517228/86172659-22186780-baf5-11ea-88da-35a0dad7e250.png">

I've found the code around the warning, is getting the `step` from useField `fieldProps`:

<img width="551" alt="Captura de Pantalla 2020-06-30 a la(s) 17 08 29" src="https://user-images.githubusercontent.com/517228/86172755-4411ea00-baf5-11ea-87b1-b02a8d7804e7.png">


<img width="625" alt="Captura de Pantalla 2020-06-30 a la(s) 17 09 04" src="https://user-images.githubusercontent.com/517228/86172809-568c2380-baf5-11ea-85e7-297b50ad8452.png">

@joepuzzo

**Comment by joepuzzo** [comment]
Try now in V4
