### ISSUE TITLE
Attempting to get field {field} but it does not exist

### ISSUE THREAD

**Issue by CRGavrila** [joepuzzo/informed#287]
Hy
Only when editing a form, in dev tools displays the message: "Attempting to get field {field} but it does not exist". I have some logic when to dispaly/hide fields. Also I tested the form and it works properly and I'm wondering if this is not will fail in future.

**Comment by joepuzzo** [comment]
So thats just a warning saying you are trying to access a field that is currently not on the page. It will work fine.

**Comment by CRGavrila** [comment]
Thanks for your thoughts. Cheers!

**Comment by MartijnHols** [comment]
I am getting this on initial render for all my fields wrapped in a wrapper that takes care of error handling and other stuff so I made a workaround to disable the warning when it's useless:

```tsx
const useNonSpammyFieldState = (field: string) => {
  // If the field is a part of this component's children, useFieldState will
  // throw a warning on the initial render:
  // `Attempting to get field {name} but it does not exist`.
  // This is because this hook is called before this component's children's are,
  // so they haven't had time to register yet. After registering, this will
  // re-render and the warning will not reappear.
  // Because we **hate** useless warnings, we disable warnings on the initial
  // render.
  const [isInitialRender, setIsInitialRender] = useState(true)
  useEffect(() => {
    setIsInitialRender(false)
  }, [])
  const warn = console.warn
  if (isInitialRender) {
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    console.warn = () => {}
  }
  const fieldState = useFieldState(field)
  if (isInitialRender) {
    console.warn = warn
  }

  return fieldState
}
```

**Comment by Aryaman73** [comment]
What is the consensus on this issue? Is this an issue with Informed itself, or with the way we are implementing `useFieldState`?

 @MartijnHols has a decent work around, but it actually catches some other errors as well ,which can impact debugging. You can make it so that it only catches errors that begin with `"Attempting to get field..."` but it still isn't ideal, in my opinion.
