### ISSUE TITLE
Can't update field as per example: formApi.setValue is not a function

### ISSUE THREAD

**Issue by jfaligent** [joepuzzo/informed#288]
As far as I can tell I'm following the `useFormApi` example pretty closely, but no `setValue` function is being set up in my form's formApi which has me scratching my head on how to update my field's value from another form element. Here I'm just trying to set up a simple incrementer button.

Here's the relevant bits of my component, which is getting rendered inside a `<Form>`:

```
import { Text, useFormApi } from 'informed';

const Quantity = props => {
    const initialQuantity = 1;
    let quantity = initialQuantity;
    const formApi = useFormApi();

    return (
        <div>
            <Text
                field="quantity"
                type="number"
                initialValue={initialQuantity}
            />
            <button onClick={() => {
                quantity = quantity + 1;
                formApi.setValue('quantity', quantity);
            }}>Increment</button>
        </div>
    );
};
```

Clicking on the button gives me: `Uncaught TypeError: formApi.setValue is not a function`

Where am I going wrong here? Thanks!

**Comment by joepuzzo** [comment]
A lot of things going on here. 

1. You should never do `    const initialQuantity = 1;` in react as every render you will set that value back to the number 1. 
2. You can only use `useFormApi` from the context of a `<Form />` .. So make sure to wrap that text field OR the `Quantity` component in a `Form`
3. Never put `button` without a `type="button"` as it will act as a submit button.

**Comment by jfaligent** [comment]
Yeah, the initialQuantity thing's just temporary code while I was getting things working (but immediately hit this useFormApi road block). So this Quantity component _is_ inside a `<Form />`, that's why I was confused. Do I need to do something to provide useFormApi with the right context since I'm calling it inside the component?

Thanks for the reminder about `type="button"`, I keep forgetting that one.

**Comment by KevinHewson** [comment]
I took the example code as written and threw it into a [code sandbox](https://codesandbox.io/s/upbeat-snowflake-g8n2w).  When I didn't have the component wrapped with `Form`, I would get the error that `formApi.setValue is not a function`, however, with the component wrapped in `<Form>` (in App.js), it behaves how you want it to.

You might also want to consider maintaining the Component's state using React's `useState` hook and updating the value of the Text field using Informed's `useFieldApi` too.  I have an example [here](https://codesandbox.io/s/competent-shockley-mwcoc?file=/src/Quantity.js).  

Not sure what your use case is, but was just playing around.

**Comment by jfaligent** [comment]
Just popping back in to say I solved this puzzle. Anticlimax, was just a versioning issue - the repo this relates to was using an outdated version (2.1.13!) and bumping that fixed the problem. Things were slightly obfuscated as some of the other devs on the project must have bumped the version locally for unrelated reasons so weren't seeing the issue, but hadn't committed the change to package.json.

For reference, here's an abridged version of the parent component just to prove I was using a Form component to wrap it the whole time:
```
<Form>
    <Quantity
        initialValue={quantity}
        onValueChange={handleSetQuantity}
    />
    <Button
        onClick={handleAddToCart}
        disabled={isAddToCartDisabled}
    >
        Add to Cart
    </Button>
</Form>
```

Anyway, thanks guys, nothing to see here!
