### ISSUE TITLE
Informed github page has broken SEO

### ISSUE THREAD

**Issue by bever1337** [joepuzzo/informed#289]
I was trying to look up documentation today and found this Google result:

> Storybook - Joe Puzzo
> joepuzzo.github.io › informed
> Informed. loading story. loading story. loading story. loading story. loading story. loading story. loading story. loading story. loading story. loading story.

![image](https://user-images.githubusercontent.com/28774413/82830494-e3ebb080-9e83-11ea-9976-f120b80057a3.png)

I was unable to find the documentation using duckduckgo for comparison.

**Comment by joepuzzo** [comment]
This should not be issue
