### ISSUE TITLE
HOC for reusable codes from Text, TextArea etc.

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [joepuzzo/informed#29]
You have:

```javascript
const Text = ( { fieldApi, fieldState, ...props  } ) => {
  const {
    value
  } = fieldState;
  const {
    setValue,
    setTouched
  } = fieldApi;
  const {
    onChange,
    onBlur,
    forwardedRef,
    ...rest
  } = props
  return (
      <input
          {...rest}
          ref={forwardedRef}
          value={!value && value !== 0 ? '' : value}
          onChange={e => {
            setValue(e.target.value)
            if (onChange) {
              onChange(e)
            }
          }}
          onBlur={e => {
            setTouched()
            if (onBlur) {
              onBlur(e)
            }
          }}
      />
    )
};

export default asField(Text);
```

But when you refactor it to kind of:
```javascript

export const asText = (Input) => (
  ( { fieldApi, fieldState, ...props  } ) => {
    const {
      value
    } = fieldState;
    const {
      setValue,
      setTouched
    } = fieldApi;
    const {
      onChange,
      onBlur,
      forwardedRef,
      ...rest
    } = props
    return (
      <Input
        {...rest}
        ref={forwardedRef}
        value={value}
        onChange={e => {
          setValue(e)
          if (onChange) {
            onChange(e)
          }
        }}
        onBlur={e => {
          setTouched()
          if (onBlur) {
            onBlur(e)
          }
        }}
      />
    )
  }
);

const DefaultText = ({value, onChange, onBlur, ...rest}) => (
  <input
    {...rest}
    value={!value && value !== 0 ? '' : value}
    onChange={e => {
      onChange(e.target.value)
    }}
    onBlur={e => {
      onBlur(e)
    }}
  />
);

export default asField(asText(DefaultText));
```

It will be easy to implement custom input wrapped by asField and with reuse of code. It is supplement to #25. In #25 we can implement custom input with reuse of code in layer above the binding of form state. In this issue we can implement custom input in layer below the binding of form state.

So we get these layers:

1. `asField` layer.
2. #25 custom input layer.
3. `fieldApi`/`fieldState` binding layer.
4. This issue custom input layer.
5. Raw HTML element layer.

**Comment by joepuzzo** [comment]
Hmm i guess i dont see to much value here the as field already does so much for you and you typically only need to write these components once for your custom input... For example, if you wanted to show a `<small>{error}</small>` after your `<input/>` you would still need to use asField to do so. Its really not that big of an inconvenience to a dev

**Comment by dzwiedziu-nkg** [comment]
Ok, 5.layers is too complicated. If somebody want it then implement. But #25 is trivial and I fink that not exporting of no wrapped by `asField` is an unnecessary limitation of functionality your library, which is nevertheless very simple and very functional :)

**Comment by joepuzzo** [comment]
Conversation to continue in 25
