### ISSUE TITLE
Pattern to validateOnBlur with useField?

### ISSUE THREAD

**Issue by absolutelysimon** [joepuzzo/informed#291]
I was unable to find a mention of this in the documentation and useField does not seem to pass down the validateOnBlur prop down. I have tried it as an argument on the calling component, and as an argument to the useField function. Neither seem to have an effect.

I'm pretty new to React so this is probably my error, but I can't find it.

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?path=/story/validation--validation-control These docs show the use

**Comment by absolutelysimon** [comment]
Forgive me if I'm missing something, but I think the linked docs only show how to use validateOnBlur with built-in components. I can't replicate the desired behaviour with my custom components.

To illustrate what I mean:

https://codesandbox.io/s/damp-browser-xqpiz?file=/src/App.js

**Comment by joepuzzo** [comment]
Take another look at the docs here https://joepuzzo.github.io/informed/?path=/story/custominputs--creating-custom-inputs You will se that the difference is that you dont have the fields on blur hooked up. 

```jsx
onBlur={e => {
          setTouched(true);
          if (onBlur) {
            onBlur(e);
          }
        }}
```

**Comment by absolutelysimon** [comment]
Awesome, thanks. Definitely missed that!
