### ISSUE TITLE
Multiple validation to single field

### ISSUE THREAD

**Issue by andtankian** [joepuzzo/informed#293]
Hi @joepuzzo 

I've been saying this lib is amazing. Thank you for that.

I've built a form component as a wrapper of _informed_.
It has some props that define default validations without explicitely set a validaton function (e.g the required prop defines an internal validation that check for empty string, undefined etc)

Today I wondered if should it be difficult to implement multiple validation mechanism to a single field?
I mean, it would be nice to be set a list of validation and execute each one in a defined order. In this way, I would keep the internal required default validation beside allow users to set theirs custom validations.

Does it make sense?
What do you think?

**Comment by joepuzzo** [comment]
Yes! In fact I have already built something similar in the past. Just never added it to the library.

**Comment by andtankian** [comment]
It would be nice to have this functionality this functionality in hands.
I appreciate your time, thanks @joepuzzo .

**Comment by joepuzzo** [comment]
So for now, since I have been really busy. It would be very easy to build this on your end. 

Just write a helper function that calls multiple validation functions... then pass that to the `validate` of the input :)

**Comment by mattbasta** [comment]
Here's what I use (TypeScript):

```typescript
function composeValidation(
  ...rules: Array<(value: any) => React.ReactNode | undefined>
) {
  return (value: any) => {
    for (const rule of rules) {
      const result = rule(value);
      if (result) {
        return result;
      }
    }
    return undefined;
  };
}
```

In use:

```jsx
<MyField field="foo" validate={composeValidation(required, mustBeURL)} />
```

**Comment by joepuzzo** [comment]
Check out this! https://joepuzzo.github.io/informed/?path=/story/validation--elon
