### ISSUE TITLE
Cannot read property 'config' of undefined without proper <Field />

### ISSUE THREAD

**Issue by enisdenjo** [joepuzzo/informed#30]
First of all, I am glad that you took the time to rewrite the react-form!

I found react-form concepts really useful, but because it was too bloated I was about to write my own implementation which would look EXACTLY like **informed**. Credits for perfect timing! 😆 

Anyway, back to issue. If the `<Form />` looks like this:
```jsx
<Form
  getApi={(formApi) => formApi.setValue('str', 'gni')}
>
  <Text field="str" />
  <button type="submit">Submit</button>
</Form>
```

Calling `formApi.setValue(key, value)` I get this error after witch the complete tree unmounts:
```
Cannot read property 'config' of undefined
```

Its pointing to this line:
https://github.com/joepuzzo/informed/blob/9a68ff6b45555566ec5f38592a64eef0080f5cff/src/Controller/FormController.js#L87

I figured that you cannot set a value when there is no initialized `<Field />` representing that key.

Is this intentional? Maybe setting values should work even without the field component? What do you think?

Best,
Denis

**Comment by joepuzzo** [comment]
So setting a value thag does not have a field will fail. If you want to initialize a field value then render a field and use initialValue prop. If you want a “hidden” field that gets submitted when the rest of the form does, just pas that manually

**Comment by joepuzzo** [comment]
So in other words yes it was intentional

**Comment by enisdenjo** [comment]
Sweet. You can close this issue.

**Comment by vfonic** [comment]
@joepuzzo thanks for the great lib!

I'm having the exact same issue. My form is rather strange. I have a form with limited fields and a button, smth like "get fields for data". I receive "form fiels" asynchronously and then I want to set these field's initial values before showing them.

Do you know any workaround for this? Or should I use several `Form`s and merge them all into one before finally sending it altogether?

**Comment by joepuzzo** [comment]
Im not sure I understand what your trying to do. Can u elaborate?

**Comment by vfonic** [comment]
Here's the example: https://codesandbox.io/s/pyq9zlm8vx

I have multi-step form and depending on some other information (I'm not receiving it from informed actually), I need to set the data on the next step, but...because step 2 is not yet rendered, I can't call `setValue` due to the issue mentioned here.

**Comment by vfonic** [comment]
Here's the example: https://codesandbox.io/s/pyq9zlm8vx

I have multi-step form and depending on some other information (I'm not receiving it from informed actually), I need to set the data on the next step, but...because step 2 is not yet rendered, I can't call `setValue` due to the issue mentioned here.

**Comment by AlpacaGoesCrazy** [comment]
You can set field that does not have rendered for melement useing `formApi.setValues`, however you will need to set all other fields which are currently preset alongside to not loose anything:
```
formApi.setValues({
	...formState.values,
	newValue: 'this does not have form element'
})
```

**Comment by zeropaper** [comment]
I believe that if this is an intentional behaviour, the error should be less cryptic.

**Comment by joepuzzo** [comment]
Yup its on my list to throw better errors. You cannot do what your trying to do :) need a matching form element
