### ISSUE TITLE
Any way to differentiate between a regular submit and a submit that comes from ArrayFieldApi.add?

### ISSUE THREAD

**Issue by absolutelysimon** [joepuzzo/informed#301]
Currently the ArrayField.add function submits the form. I was previously doing some processing in Form's onSubmit, but now that processing fires if I try to add an ArrayField. Any way for me to filter those submits, other than manually trying to check if the relevant ArrayField has a blank set?

**Comment by joepuzzo** [comment]
No it doesn’t, a button without type=“button” will by default be of type submit and will trigger a submit

**Comment by absolutelysimon** [comment]
Ugh. Don't know how I missed that. Thanks.
