### ISSUE TITLE
There is no more "Relevant" Component?

### ISSUE THREAD

**Issue by guipolitano** [joepuzzo/informed#302]
Hi, I cant use this Component, https://joepuzzo.github.io/informed/?path=/story/dynamic-forms--dynamic-fields. It even show on Import. Its the documentation outdated?
![image](https://user-images.githubusercontent.com/43428456/87249610-747f4f80-c436-11ea-84cb-5b22ba7f7d91.png)

Thx very much

**Comment by joepuzzo** [comment]
Update to latest version its new

**Comment by guipolitano** [comment]
> Update to latest version its new

Thx for the answer, but im in the version 3.9.0 (im think is the latest, im i wrong?)

![image](https://user-images.githubusercontent.com/43428456/87301939-d4cdca00-c4e6-11ea-9ed6-064b0d561b32.png)

Already run a "yarn upgrade" but still not showing the Relevant component.

**Comment by joepuzzo** [comment]
run an `npm ls informed` and lmk what version is output in console

**Comment by guipolitano** [comment]
![image](https://user-images.githubusercontent.com/43428456/87302210-57ef2000-c4e7-11ea-9af4-c0f5d276b27d.png)

I think the index.d.ts its not exporting the type of Relevant. The Component exists in node_modules/informed/index.js

**Comment by joepuzzo** [comment]
Ahh Yes, I don't use or maintain the typescript file ( the community has ) lol. If you want you can make a PR with the type update for that.

**Comment by guipolitano** [comment]
Ohh, I did not know. I will do some tests and probably make a PR soon. Thx for the answer and the great package, im loving it. =P

**Comment by joepuzzo** [comment]
No probs! Yeah sorry I have just never been a typescript guy lol. But the code is solid.
