### ISSUE TITLE
Values object passed to validation function lags behind changes

### ISSUE THREAD

**Issue by OllyHodgson** [joepuzzo/informed#307]
Hello,

I frequently run into an issue when doing [complex validation](https://joepuzzo.github.io/informed/?path=/story/validation--complex-validation) with `validateOnChange`: The `values` object passed to the validate function is consistently one step behind the change.

In this example, I need the user to choose a value from exactly one of the two Select boxes. However, the `values` passed to the validation function always contains the form state _before_ the change happened. e.g. if field `one` triggered the validator, `values['one']` is not the same as the `value` argument.

```
import React from "react";
import { Form, Select, Option } from "informed";

const FormValidationTest = () => {

  const validateMultiple = (value, values) => {
    const itemsSelected = Object.keys(values).length;
    if (itemsSelected !== 1) {
      return "Please choose one 1 of the two items";
    } else {
      return undefined;
    }
  };

  return (
    <Form>
      <Select field="one" id="one" validate={validateMultiple} validateOnChange>
        <Option value="">Please select...</Option>
        <Option value="Canada">Canada</Option>
        <Option value="Japan">Japan</Option>
      </Select>
      <Select field="two" id="two" validate={validateMultiple} validateOnChange>
        <Option value="">Please select...</Option>
        <Option value="UK">United Kingdom</Option>
        <Option value="USA">United States</Option>
      </Select>
    </Form>
  );
};

export default FormValidationTest;
```

Is it supposed to work like this, or should I see the latest changes in the `values` object?

**Note:** If I add `validateOnBlur` to the `<Select>` components, the validation works correctly when the user clicks away from the select box, but that's not quite what I want here. It's not clear to me if this is a timing thing (the formState has had time to update) or it's supposed to work that way.

**Comment by joepuzzo** [comment]
Yes this is known, but thats why you get the value and values.

**Comment by joepuzzo** [comment]
Because the form has not yet updated. The values is the state before its completed. This was the exact reason for exposing both value and values. And examples in docs should reflect this.

**Comment by OllyHodgson** [comment]
OK. Is there a way for the validation function to tell which field passed the `value`? I know one of the `values` has changed, but how do I know which one?

I think the bit I missed from the documentation was:

> Validation will **occur on submission.**

Which in hindsight tells me `validateOnChange` isn't really compatible with complex validation.
