### ISSUE TITLE
FormApi.setValue() not working as expect on custom select (dropdown) field

### ISSUE THREAD

**Issue by mathiasms14** [joepuzzo/informed#309]
I am trying to set the value of a select field depending on the selection of another field (Autocomplete field). So inside the onChange of the field (Autocomplete) I am trying to setting the new value of the selectfield with the formApi.setValue(). The value is setting correctly (because it appears when I submit the form) the only problem is that the dropdown is not selecting the option. Maybe I am doing something wrong :( 

Thank you in advance!!

**Comment by joepuzzo** [comment]
Your custom select needs to have value= to relect the form fields value. See the custom input docs. Make it work with that example then try to see why its not working with yours. Sounds like its not hooked up correctly.
