### ISSUE TITLE
Reusable of existing code: lodash/defaultTo

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [joepuzzo/informed#31]
Hi. I know, you hate me ;)

You are use `!value && value !== 0 ? '' : value` expression to avoid of `undefined` or `null` test in input. But, the `defaultTo(value, '')` from `lodash` return the same result but it looks clearer.

`Lodash` is the big library but you can import only `import defaultTo from "lodash/defaultTo";`. Then JS code after minification will be contain only code from `lodash/defaultTo.js`, not whole `lodash`.

You thought about it?

**Comment by joepuzzo** [comment]
Ha yup thought about it and im not a lodash guy.. i like to keep it pure js as much as possible :) just the way i roll
