### ISSUE TITLE
Cannot set initialValues for <Form> from dynamically-set values

### ISSUE THREAD

**Issue by misterlocations** [joepuzzo/informed#310]
I have a component where a Form is rendered inside a drawer, and I'm trying to pass an object for the Form's _initialValues_ prop. When I pass hard-coded strings into that prop, the form inside the drawer will contain those initial values just fine.

However, since the contents of the drawer depend on a selection from the containing screen, the data being passed to initialValues starts off as an empty object. When I then try to pass a new value into initialValues (upon next render), I do not get the pre-filled values as expected - all the fields in my form remain blank.

My code is like this:
```
const [selection, setSelection] = React.useState({});
...
return

<> 

// just an example
<button onClick={() => setSelection(options.find(o => o.id === id))}
<Form initialValues={selection} />

</>

```

Is this behavior intentional, and is there a workaround in order to pre-fill form values from a varying selection?

**Comment by joepuzzo** [comment]
Reset the form if you want the new initial values via formApi.reset()

**Comment by misterlocations** [comment]
@joepuzzo Thanks for pointing that out! I didn't find the API doc until today, so I was unaware of reset(). 

For anyone else who wants to pre-fill values of a form based on the results of an API call, this is what I did:

```
import React, { useState, useEffect } from 'react';
import { Form, Text, useFormApi } from 'informed';

const Contents = ({initialValues = {} }) => {

    const formApi = useFormApi();

    React.useEffect(() => {
        formApi.setValues(initialValues)
    }, [initialValues]);

    return (
        <div>
            <label>
                First name:
                <Text field="firstName" />
            </label>
            <label>
                Last name:
                <Text field="lastName" />
            </label>
            <button type="submit">Submit</button>
        </div>
    );    
};

export default function TestForm() {

    const submit = values => window.alert(`Form successfully submitted with ${JSON.stringify(values)}`);
    const [vals, setVals] = React.useState({})
    const formApi = useFormApi();

    async function getData() {
        const response = await fetch("http://localhost:3000/");
        const data = await response.json();
        return data;
    }

    // do api call
    React.useEffect(() => {
        const doFetch = async () => {
            const data = await getData();
            setVals(data)
        }
        doFetch();
    }, []);

    return <Form onSubmit={submit} initialValues={vals}>
        <Contents initialValues={vals}/>       
    </Form>

}
```
