### ISSUE TITLE
Dynamic forms are broken in React.StrictMode

### ISSUE THREAD

**Issue by mattbasta** [joepuzzo/informed#315]
I recently upgraded from 3.9.0 to 3.13.1 and upgraded React from the latest 16.x version to 17.0.1 and found that some of my forms started failing. When a field with validation is removed from the render tree, the validation is still performed and an error for it appears in `useFormState().errors`.

I don't know whether the issue is the result of changes in React 16 -> 17 or informed 3.9 -> 3.13.

In this example, I have a field called `Homepage` which looks like this:

```jsx
<div>
  {enableHomepage && <Homepage field="homepage" validate={required} />}
</div>
```
When `enableHomepage` becomes false, the field is removed from the page, but the form will fail to submit because the validation (`required`, which checks that a value exists) is still run, even though `Homepage` is no longer in the form.

This only happens in `React.StrictMode` in development mode. Debugging within `informed`, the `fieldsById` member contains two entries for each field, each with a different ID. When a field is removed, only one of the two entries is removed, but the other (with references to the validation) remains.

Per the docs, `StrictMode` double-invokes `useState` lazy initializer functions (functions passed to `useState`) to suss out functions which should not have side effects. Per https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects:

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> 
> ...
> 
> - Functions passed to `useState`, `useMemo`, or `useReducer`

`useField` abuses a lazy initializer function to cause run-once behavior:

https://github.com/joepuzzo/informed/blob/master/src/hooks/useField.js#L445

I'm not sure why an upgrade triggered this behavior to start failing, but it seems like an obvious reason this would start to fail.

I'd suggest replacing the `useState` with a `useRef`:

```js
useState(() => {
  // ...
});

// becomes

const setUp = React.useRef(false);
if (!setUp.current) {
  setUp.current = true;
  // ...
}
```

**Comment by joepuzzo** [comment]
This is a known issue with strict mode. The problem is a field will register twice due to reacts strict mode, and therefore when the field gets unmounted it only "cleans up" after one of the fields. I understand how useRef works but that will not solve the problem of "faking a constructor".

**Comment by joepuzzo** [comment]
I spent hours trying to solve this and determined it was just strict mode. I dont remember off the top of my head what exact issue was, but I know it was a result of the field getting registered twice with two different ids .

**Comment by mattbasta** [comment]
Yeah, that's what I'm seeing. Is there a reason the field needs to be registered _during_ the initial render rather than during the `useEffect` directly below?

**Comment by joepuzzo** [comment]
Having fields register right away is important. There are lots of issues that come up when the form context is at the mercy of react painting everything on screen. Also 90% of the unit tests fail if I only do it in the use effect.

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/initialref-ruj00?file=/src/App.js Here is example that shows why the ref solution will NOT work

**Comment by joepuzzo** [comment]
It uses a common pattern ( the one you showed above ) via an `useInitRef` hook

**Comment by joepuzzo** [comment]
However strict mode will still cause the field to register twice, and will never cleanup the first one

**Comment by joepuzzo** [comment]
This is one of the reasons I hate Strict mode with a passion. Also don't like concurrent mode as its confusing and the React dev team cant even figure out a good way to get it stable. React should have ability to have a guarenteed "construct" method for a component. Thats a very useful, trivial, and typical patten in generic programming.

**Comment by joepuzzo** [comment]
IMO there are things that can and should be done BEFORE the component renders.. NOT after.

**Comment by mattbasta** [comment]
I mean, I appreciate that, but it basically means I have to stop using informed :(

**Comment by joepuzzo** [comment]
That does not make sense

**Comment by joepuzzo** [comment]
This only happens in strict mode

**Comment by joepuzzo** [comment]
Dont use strict mode

**Comment by mattbasta** [comment]
I need to run my code in Strict Mode, since we're targeting React 18 concurrent mode, which essentially requires the `React.StrictMode` behavior:

> The commit phase is usually very fast, but rendering can be slow. For this reason, the upcoming concurrent mode (which is not enabled by default yet) breaks the rendering work into pieces, pausing and resuming the work to avoid blocking the browser. This means that React may invoke render phase lifecycles more than once before committing, or it may invoke them without committing at all (because of an error or a higher priority interruption).

If informed does not respect this, it will simply not work in concurrent mode, which will necessitate us switching frameworks regardless.

**Comment by joepuzzo** [comment]
It will be nearly impossible to write a library that is capable of what this is without a guaranteed initialization function.

**Comment by mattbasta** [comment]
Have you tried replacing the `useEffect` with `useLayoutEffect`, which runs synchronously before the browser has a chance to paint?

**Comment by joepuzzo** [comment]
I have yes

**Comment by joepuzzo** [comment]
I can give that another shot. I know I had issues there as well but forgot

**Comment by joepuzzo** [comment]
Hmm that actually may work now I need to dig into why I went down the useState route instead of layout effect

**Comment by joepuzzo** [comment]
hmm interesting I could have sworn layoutEffect had issue before.

**Comment by joepuzzo** [comment]
Ok so here is what I will do. Im going to release a patch update to fix this. ( via useLayoutEffect ). I have done some exploratory testing and everything seems to still be working ( to my surprise ). If I find any reason that this did infact break something I may revert back. However currently this is looking promising.

**Comment by joepuzzo** [comment]
@mattbasta Ok released new version. LMK if that fixes the issue. and also keep me posted if that caused any issues please.

**Comment by mattbasta** [comment]
That's cleared things up! Many thanks.

**Comment by joepuzzo** [comment]
So this did this fix your problem ? Just want to validate all is working well now.

**Comment by joepuzzo** [comment]
Also if you want to have some fun. I just added this today https://joepuzzo.github.io/informed/?path=/story/formatting--formatter
