### ISSUE TITLE
Informed and Material UI's Autocomplete component

### ISSUE THREAD

**Issue by jsheffers** [joepuzzo/informed#316]
I've been trying to get Informed to work with Material UI's Autocomplete component which renders an MUI TextField.  This works great for the most part.  When I type into the text field, it updates the Informed state perfectly.  However, when I call `formApi.reset()` the form state gets reset, but the value in the input remains.  Any ideas on how to accomplish this?

https://codesandbox.io/s/purple-lake-eekxq?file=/src/App.js

**Comment by joepuzzo** [comment]
You forgot to add 

```
value={value}
```

on the FormField
