### ISSUE TITLE
JSON Schema example errors

### ISSUE THREAD

**Issue by mustafawm** [joepuzzo/informed#319]
Hello,

Seems like a nice library 👍 (esp if the builtin json form building part)

I'm following the JSON schema validation example from the [docs](https://joepuzzo.github.io/informed/?path=/story/validation--json-schema-validation-rendering) and it's not working (nothing is alerted, and there are a couple of typescript errors).

[Codesandbox to show the issue](https://codesandbox.io/s/wonderful-sanne-mf17u?file=/src/App.tsx)

**Comment by joepuzzo** [comment]
Its working as expected see here https://codesandbox.io/s/late-fast-svlxb. The default inputs dont render out errors. Its up to the user i.e you to decide what to do with them. 

See here for building your custom inputs

https://joepuzzo.github.io/informed/?path=/story/schema--custom-schema

**Comment by joepuzzo** [comment]
And see this https://joepuzzo.github.io/informed/?path=/story/custominputs--creating-custom-inputs

**Comment by mustafawm** [comment]
Got it. Thanks for clarifying that. 

I was actually looking for a way to use it with a component library, the custom schema example seems to show how to go about that.

**Comment by joepuzzo** [comment]
Yup the most powerful feature is custom components. Wouldn't suggest using it without building those first :)
