### ISSUE TITLE
Select ID attribute does not get put on the HTML element

### ISSUE THREAD

**Issue by Luphrid** [joepuzzo/informed#320]
When using the Select component, an attribute of id used to trickle down to the HTML element.  After upgrading to latest, the id no longer appears on the rendered select element.

**Comment by joepuzzo** [comment]
Let me look

**Comment by Luphrid** [comment]
Thank you!

**Comment by joepuzzo** [comment]
Fixed. I accidentally ran an `npm version minor` instead of patch LOL so its in `V3.24.0`

**Comment by Luphrid** [comment]
Joe.  You are seriously the man.  Thank you so much!
