### ISSUE TITLE
ArrayField set Value with drag and drop not working!

### ISSUE THREAD

**Issue by mathiasms14** [joepuzzo/informed#325]
Hey guys I am using informed to handle all my forms in my App. But I encounter a problem on how to deal with ArrayField with Drag and Drop (react-beautiful-dnd). I am using the arrayField inside the DragDropContext like the gif right here.

![Screen Recording 2020-12-16 at 17 34 45](https://user-images.githubusercontent.com/52463976/102403805-91abe180-3fc5-11eb-894c-3bc9b115f27a.gif)

The problem is that I am trying to set the value (with the new order) of my array items with the setValue method. For what I have read that is not possible, is that true? If it is, how can I set a new order value for my arrayField items? 

Thank you in advance!!

**Comment by joepuzzo** [comment]
As it stands we dont support swap operation on array fields, array fields are very tricky creatures. This would potentially be a hard thing to add. It comes down to the array field tracking the form inputs via a path `modifier[1].name` and because the state object is modified using this path, a swap operation would ned to get added somehow.

**Comment by mathiasms14** [comment]
Thanks as always for the quick response dude! That make sense , do you have a work around for this kind of jobs?

**Comment by joepuzzo** [comment]
Ahh at the moment I do not have a workaround for swap. I would need to look into this. Array fields are a huge pain in the ass so would take some thinking lol

**Comment by mathiasms14** [comment]
lol yes they are !! Okey brother just close this issue if you want :), thanks for your help I will try to find some workaround into my app for this. Thanks for the time as always!!

**Comment by joepuzzo** [comment]
Ok

**Comment by joepuzzo** [comment]
I have done it !

**Comment by joepuzzo** [comment]
Stand by

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?path=/story/arrays--swap

**Comment by mathiasms14** [comment]
thats really awesome my man!! lemme check that now!!

**Comment by mathiasms14** [comment]
That look really solid dude!! I will add it to my app and let you know if I find something weird :) . Just a little feedback the readme for the swap has some super tiny mistakes  `set friends[0].name to test` and also the variable `index` is not inside the parameters of the render function. Greatt job dude as always!!!! Thanks for the quick response!!!!
