### ISSUE TITLE
`asField` not returning `required` to custom component

### ISSUE THREAD

**Issue by larrybotha** [joepuzzo/informed#330]
Given:

```jsx
const CustomField = asField({required}) => {
	return <input {required} />
}

<CustomField required={true} />
```

I would expect `input.getAttribute('required') === true`.

Instead, `input.getAttribute('required') === undefined` as a result of https://github.com/joepuzzo/informed/commit/2de4eceaf5d2d84bb10db9fe8232646fda5aef90#diff-0231c368f89794c64e7bc2db83761f86348f5f651442db34d3b71b89f88ae432.

### Suggestion:

- return `required` in `userProps`.

**Comment by joepuzzo** [comment]
Fixed in NExt major version! Also heads up, asField is getting depricated and only the `useField` will be available

**Comment by joepuzzo** [comment]
I will have next version out V soon ( after thanksgiving )

**Comment by joepuzzo** [comment]
v4 is out!
