### ISSUE TITLE
Dynamic fields inside Scope revert to initialValue even when keepState is true

### ISSUE THREAD

**Issue by evanl5** [joepuzzo/informed#333]
In the example below a `Form` is created with an initialValue for a dynamic field. When the dynamic field is rendered for the first time it properly displays the `initialValue`. If a user changes the value of the dynamic field and that field is then removed and later added back it will revert to the `initialValue`, even though keepState is true. This only happens when the dynamic field is rendered inside the `Scope` component.

See code sandbox:
https://codesandbox.io/s/keppstateinitialvaluescope-5n35p

Steps to reproduce:
1. Select "Are you married?" - "Yes"
2. Change "Spouse name"
3. Toggle "Are you married?" to "No" and back to "Yes"
4. "Spouse name" will revert to `initialValue` when it should remain what was entered in step 2.

**Comment by joepuzzo** [comment]
Let me look into this

**Comment by joepuzzo** [comment]
I have fix

**Comment by joepuzzo** [comment]
Ok fixed in the latest release thanks for the re-creation
