### ISSUE TITLE
Widen peer dependency range to include React 17

### ISSUE THREAD

**Issue by evankellogg** [joepuzzo/informed#334]
React 17 was released recently with minimal breaking changes. informed currently supports only ^16.8.0

Could this be widened to ^16.8.0 || ^17.0.0?

**Potential problems**
There are subtle differences between React 16 and React 17, so it's worth reviewing to see if any of them might affect the library's functionality.

**Comment by joepuzzo** [comment]
React 17 works fine with informed. In fact, the docs have been using 17 for a long time now, I just need to update the peer deps, but that is non blocker

**Comment by evankellogg** [comment]
It does work fine with React 17 as we are using with successfully today, however with a recent update to npm there are annoyances in running an _npm update_

This is not a blocker, but updating the peer-deps will remove the annoyance of using --force

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dpp-ui@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from informed@3.24.2
```

**Comment by joepuzzo** [comment]
Stand By

**Comment by joepuzzo** [comment]
Ok new version out with that peer dep change

**Comment by joepuzzo** [comment]
Also you need to update your git profile pic my dude 😁
