### ISSUE TITLE
SSR Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by danielsarin** [joepuzzo/informed#337]
There was an old pull request #221 that fixed this issue but it seems to be back again.

I get the error when using a custom component with `asField` and I think it's caused by `useCursorPosition.js`.

https://github.com/joepuzzo/informed/blob/84a450733c29739ecf477834d29b63d97dd7d934/src/hooks/useCursorPosition.js#L1-L36

I'm not sure I understand the code well enough, but is there a reason why `useCursorPosition.js` does not use `useIsomorphicLayoutEffect` instead of `useLayoutEffect`?

**Comment by joepuzzo** [comment]
no reason. I just used the wrong one

**Comment by apennell** [comment]
I've been seeing this warning recently as well. 

> no reason. I just used the wrong one

Is this something you plan to fix, or would accept pull requests for? Your response makes it sound like it would be a simple replacement.

**Comment by joepuzzo** [comment]
This should be fixed now

**Comment by mhuretski** [comment]
`useField` also generates warning
