### ISSUE TITLE
Cannot readt property 'field' of undefined. FormController.deregister

### ISSUE THREAD

**Issue by mathiasms14** [joepuzzo/informed#338]
Hey again dude ! how are you? I am having this issue on staging (locally my forms work).
<img width="572" alt="Screen Shot 2021-04-12 at 15 41 41" src="https://user-images.githubusercontent.com/52463976/114445163-22768080-9ba6-11eb-9729-783e2471ac00.png">

**Comment by joepuzzo** [comment]
IS this still an issue? Sorry I missed this issue.

**Comment by joepuzzo** [comment]
Try in v4!
