### ISSUE TITLE
setValue(null) removes the value from the state

### ISSUE THREAD

**Issue by enisdenjo** [joepuzzo/informed#34]
Hey,

when using `setValue` from the `<Field />` perspective and setting it to `null`, the next state is without that value instead of having it as `null`.

```js
const initialState = {
  some: 'value',
};
```
Then: `<Field field="some" />.setValue(null)`, we get the following state:
```js
const nextState = {};
```

In my use case `null` and `undefined` is VERY different, so I'd need the value to have the `null` set...

**Comment by enisdenjo** [comment]
Okay, I see. You can close this issue.

**Comment by XPilot** [comment]
I just run into this same issue... Should really update docs bro... I am doing some heavy computations to filter results and null is generally accepted. Null is null, undefined can safely remove keys from form values.... null not so much. Any way to fix this?
