### ISSUE TITLE
How to make use of Relevant

### ISSUE THREAD

**Issue by andrewdesmondm** [joepuzzo/informed#345]
Currently the `Relevant` feature is not exported. How can I make use of this in my forms?

**Comment by OllyHodgson** [comment]
My guess is you're using Flow or TypeScript and the type definitions aren't aware of the `<Relevant />` component. IIRC the type definitions on this project are managed by the community, not @joepuzzo.

For my Flow project, I had to add the following to my Informed type definition (inside `declare module "informed" {}`):

```
  declare export class Relevant extends React$Component<{
    when: Informed$Values => boolean
  }> {}
```

I imagine a similar addition will be needed for [the Typescript definition in the project](https://github.com/joepuzzo/informed/blob/master/index.d.ts). It's a bit bizarre that it's not there already - Relevant is an _incredibly_ useful component!

**Comment by joepuzzo** [comment]
I dont support the TS stuff so thats prob the issue. Relevant is exported

**Comment by joepuzzo** [comment]
Try in V4. Im working on updating types now
