### ISSUE TITLE
Select dropdown flickers and closes in Firefox

### ISSUE THREAD

**Issue by akshare** [joepuzzo/informed#346]
On Mac Catalina, Firefox browser (88.0.1), the select field flickers and closes automatically after couple of selections.
Not sure if it's occurring in other Firefox versions as well.

Was able to replicate the behavior in the demo: https://joepuzzo.github.io/informed/?path=/story/inputs--select-input

**Comment by joepuzzo** [comment]
Assuming this is only for my custom input styles. So not a bug with the actual library.

**Comment by akshare** [comment]
Waited for latest Firefox version hoping this would fix itself, but unfortunately, the issue remains.

I disabled page styles in Firefox to make sure it wasn't from css.


https://user-images.githubusercontent.com/10148279/132592304-a33c0b47-c408-4108-8e37-d0da4970c282.mov

**Comment by joepuzzo** [comment]
Hmm I dont understand how thats possible lol. Its literally just state managing the value selected ( like any other react controlled select ) can you confirm this is not issue if you built your own react select ( like basic state managed from docs )

**Comment by akshare** [comment]
I can confirm now that it's an issue with Firefox since this behavior can be replicated in plain html select as well.
