### ISSUE TITLE
Props changed don't affect fieldState

### ISSUE THREAD

**Issue by gurmiguel** [joepuzzo/informed#35]
The main purpose of a React component is that "when its internal and external state (props) change, its content must change (or not)".
But that's not the case for the inputs. For example, I use a **Text** component and validate if it's empty, but I don't want it to until I submit, okay so far, but I want that after submitting the form, if there was an error, the component should validate on Change, so I can do a proper validation, so I tag it with **validateOnChange**, but when it changes, nothing happens, just when I submit again the form, it revalidates.

I guess a simple check on **componentDidUpdate** reflecting changes to the **fieldState** would solve the issue.

As a workaround, the following code achieves (closely) the desired behavior.

```javascript
<Text
    field={"name"}
    validate={validation}
    placeholder={"Name"}
    initialValue={formState.values['name']}
    validateOnMount={this.state.formSent}
    validateOnChange={this.state.formSent}
    key={`name-${this.state.formSent|0}`}
/>
```
Assuming you have a state flag _formSent_ changing with the **Form** prop **onSubmitFailure**. The **key** prop is used to force the component to remount, which is not the perfect behavior, but solves the problem, but as it's a brand new component you should set **validateOnMount** so it validates right after the first submit. 

_EDIT: Another downside about this, is that you have to set the **initialValue** of the field according to the formState, so it doesn't empty whenever it remounts, and it would affect other behaviors_

As of now, I'm a bit busy so I couldn't make a PR nor avaliate a change in the source code. If you could please take a look, I don't think it would be something too expensive.

**Comment by joepuzzo** [comment]
Ok so are you basically saying that by changing the validateOnMount and onChange props it should change the functionality dynamically?

**Comment by gurmiguel** [comment]
As for the [docs](https://joepuzzo.github.io/informed/?selectedKind=Inputs&selectedStory=Intro), each field has some flags, **validateOnMount**, **validateOnChange**, **validateOnBlur**, except for **validateOnMount**, for obvious reasons, my proposal is to reflect the prop changes to the internal **fieldState**, as for the use case I cited or something similar, it may be the best alternative, and I actually don't see why not,

**Comment by joepuzzo** [comment]
Ok so im now seeing this issue and it will take some time but i will look into getting this fixed

**Comment by gurmiguel** [comment]
Thank you, sorry for not helping much in coding, but I'll watch the issue for any comments if you have.

By the way, congrats for the lib.

**Comment by joepuzzo** [comment]
Hey try the latest release it was a simple fix that should work now :)!

**Comment by gurmiguel** [comment]
Perfect, I used the storybook to test it and worked just fine.

Thank you very much :)
