### ISSUE TITLE
getFullField appears to be mocked for Jest tests using @testing-library/react

### ISSUE THREAD

**Issue by luke-denton-aligent** [joepuzzo/informed#352]
The `getFullField` function from `formApi`, in Jest tests, is an empty function. In actual fact, it seems that all the functions in `formApi` are empty; are they all being mocked?
Is there a way to disable that mock so we can actually get the functionality?

Here is a code sandbox showing the issue
https://codesandbox.io/s/informed-js-getfullfield-empty-function-7g1tf?file=/src/Component

**Comment by joepuzzo** [comment]
Simple. You are not rendering component in a form. so by default all form functions will be noops.

**Comment by luke-denton-aligent** [comment]
> Simple. You are not rendering component in a form. so by default all form functions will be noops.

:facepalm:

Thank you
