### ISSUE TITLE
FormAPI.setValue for nested value

### ISSUE THREAD

**Issue by enisdenjo** [joepuzzo/informed#36]
I am trying to set a value under a `<Scope scope="parent">...</Scope>`. The form values look like so:
```js
const values = {
  parent: {
    child: 'SET THIS VALUE',
  },
};
```

But neither `formApi.setValue('parent.child', 'NEXT VALUE')` nor `formApi.setValue(['parent', 'child'], 'NEXT VALUE')` work.

Do I really have to use `formApi.setValues` and merge?

**Comment by joepuzzo** [comment]
This should work... are you using the latest code and can you create sandbox with issue?

**Comment by enisdenjo** [comment]
It is working as of 1.5.0.

**Comment by joepuzzo** [comment]
Awesome!
