### ISSUE TITLE
Object value touched getting true onSubmit

### ISSUE THREAD

**Issue by Bezmehrabi** [joepuzzo/informed#361]
Hi, I have the following code:
```js
const a  = useField({ field: 'friends.0' })
const b = useField({ field: 'friends.0.name' })

```
When I submit the form, the `friends.0` object `touched` value changes to `true`, and then the `friends.0.name` tries to set `touched` true for itself, but it throws an error because `can't read property name of true`.

Is that the right thing to set the `touched` value to `true` for object fields?

I can make a PR to ignore setting `touched` value when the field is `object` type.

**Comment by joepuzzo** [comment]
Try in new version please
