### ISSUE TITLE
getCurrentStep has been Removed?

### ISSUE THREAD

**Issue by SoloDev45** [joepuzzo/informed#371]
In my use case, I want to know about the current step name in the MultieStep form. In the previous version, I'm using the getCurrentStep() method which is giving me the expected output.

But now the getCurrentStep has been removed, how can I get the current step name now?

**Comment by joepuzzo** [comment]
Stand by

**Comment by joepuzzo** [comment]
Ok I did two things for you
1. I added that function back 
2. I added docs for `MultistepState` which show how to use `previousStep` `nextStep` and `current`

See docs here https://joepuzzo.github.io/informed/?path=/story/multistep-forms--multistepstate

**Comment by SoloDev45** [comment]
I didn't get the getCurrentStep() function, But I have solved my issue with **MultistepState** :clap:

**Comment by joepuzzo** [comment]
Ok function should be there tho but cool!
