### ISSUE TITLE
[Missing dependency] @babel/runtime

### ISSUE THREAD

**Issue by romainbellande** [joepuzzo/informed#38]
I use informed in a typescript project and the compilation failed without adding @babel/runtime manually. Can you add it to the package.json ?

**Comment by joepuzzo** [comment]
Yup i can look into adding this today

**Comment by joepuzzo** [comment]
This is fixed

**Comment by FredyC** [comment]
@romainbellande Is that something specific to your setup? I cannot imagine why Typescript would need such a module installed as a dependency. I mean I do use TypeScript as well but without Babel. Feels much easier and faster in overall.
