### ISSUE TITLE
How to incorporate input type "hidden"?

### ISSUE THREAD

**Issue by devbucket** [joepuzzo/informed#39]
In my application I user `<Scope>` to group multiple fields. These fields belong to a dataset that also as an ID. I need to pass this ID along with the scoped group. But unfortunately fields with `type="hidden"` are not parsed by informed.

Can you please explain how to handle this?

**Comment by joepuzzo** [comment]
So why are you hiding fields? Why not pass the data in at the end on submission?

**Comment by devbucket** [comment]
How would I do this then?

**Comment by joepuzzo** [comment]
So when informed calls the on submit function you are probably going to call some other funtion to take the values of the form and do womthing with them. Simply add your “hidden” values then

**Comment by pedrobeiraof** [comment]
I have the same problem with a different situation. I'm using a modal to complete the form but when i close the modal i lost the values of the inputs inside of it. There is any way to keep this data on formState ?

**Comment by joepuzzo** [comment]
^^ You need to do something with the data.. this is outside the scope of informed.

**Comment by joepuzzo** [comment]
@devbucket what is the status of this? Can i close?

**Comment by fletcher91** [comment]
We're using a custom input which interfaces with the component API, which basically just renders an `input` element with any given `type` property.

We have two use cases;
* Being able to have our form generator insert values dynamically into a form via a single API (the `Input` component).
* Making forms work without javascript via SSR (long-term)

**Comment by FredyC** [comment]
With `react-form` I just did the following to have a value set. No need to render any input. I believe it would work the same way in Informed. The Field component is exposed as well, just not documented.

```jsx
<Field
  field={['prices', index, 'priceType', 'enum']}
  defaultValue={priceType}
  render={() => null}
/>
```

**Comment by devbucket** [comment]
I solved it in my own way. Thank you.

I think its bad, that informed is not able to handle hidden form fields. Sometimes they are necessary and they are a native feature as well.
Its just a bit weird to have such a really nice tool with such a good API but then it lacks such basic things.

**Comment by FredyC** [comment]
@devbucket I am failing to see how is it lacking? My example above fulfills the role of hidden input assuming you don't need an actual input. What would that be good for? On submit you get values from all fields no matter how they are rendered.

**Comment by joepuzzo** [comment]
Hidden fields were a “hack” in the past to shove values into a form submission.. since you dont have to do that anymore there is no need

**Comment by fletcher91** [comment]
Why add another merge mechanism after the validations when an additional entry in the initial values object suffices. API consistency isn't a hack. And besides, when one wants to do SSR, the hidden values become a necessity nevertheless.

But as long as hidden inputs work via custom inputs, there isn't really a problem.

**Comment by devbucket** [comment]
Agree with @fletcher91. Anyways, this issue might be closed now.
