### ISSUE TITLE
Not seeing initialValue applied until after interacting with the input

### ISSUE THREAD

**Issue by spenceropope** [joepuzzo/informed#40]
I'm using the Text input with an initialValue, however, the input initializes with no value (empty) and then once I interact with it (click on then, click off) the initial value is applied. Do I need to define this initialValue somewhere else than just on the element.

`<Text field="address" id="form-address"  initialValue="John" />`

**Comment by joepuzzo** [comment]
I will look into this today. What version are you using?

**Comment by spenceropope** [comment]
I was using 1.1.3. I can try to reproduce it in a code sandbox tonight.

**Comment by joepuzzo** [comment]
Cool Thanks. Also try the latest version! We are on 1.5.2

**Comment by joepuzzo** [comment]
Any updates on this? Can i close?
