### ISSUE TITLE
Why HOC only?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#43]
Hey, I must say I am bit confounded right now. I am using the react-form in a middle-sized project and it works quite well for its needs. Finding out today that it has been deprecated was surprising at least and I was at least hoping that Informed would be very similar. It's kinda sad realization it's mainly HOC based. This was the main reason why I haven't picked other solutions.

What is the logic behind such a decision? I mean you have the render prop approach for the Form state, but everything else must go through HOC. Why? Internally it's so much easier to have to render prop component being exposed as HOC. It's rather cumbersome in an opposite way.

It's not like HOC are bad, I am not saying that but why issuing such a constraint when it's easy not to? Please reconsider this decision. I am not sure what other solutions are out there, but I don't want to end up writing my own form library because this ends up another HOC only solution.

PS: I do like that you got rid of Redux, it was wildly unnecessary and harder to debug. Although there is still redux in keywords in package.json :)

**Comment by joepuzzo** [comment]
So i like HOC a lot more personally but i do still expose the Field component so u can still easilly use that. HOC makes creating custom inputs very easy and intuitive. I think in the end i will just expose both and let users pick what they want

**Comment by FredyC** [comment]
Oh, I should have probably looked into the code first :) I kinda assume that since it's not mentioned in the docs, it won't be there.

I don't like HOC mainly because of a clash of prop names. I want to pass some prop from the parent only to later find out it was overwritten by HOC to something else. Render prop components are much more transparent on this although nesting them is a rather hellish experience for sure :)

Btw, I also noticed some Scope component in examples, is that something similar to NestedField? It's undocumented too.

**Comment by joepuzzo** [comment]
Yeah so I actually like hoc for that reason lol because you dont have to explicitly pass props. And as for scope. Its similar but not the same. It allows u to scope fields and thay is it! It does not take validation functions and stuff

**Comment by FredyC** [comment]
I think I might have the limitation of the HOC approach. Consider the following example with react-form. It's a self-contained input component that would validate value to be numeric.

```js
const FormInputNumeric = ({ field }) => (
  <Field field={field} validate={validateNumber}>{fieldApi => 
    <input onChange={...} value={fieldApi.value} />
  }</Field>
)
```

How would create such self-contained validated component with HOC? I don't believe it's possible directly. It would need to be another wrapping component around the HOC one. Or am I missing something here?

**Comment by joepuzzo** [comment]
Yeah in your case above. If i did not also export field comp. you could still achive this but it would not be clean. Simply wrap your component one more time with another component that sets the field and passes down the ...props

**Comment by FredyC** [comment]
I would not call that 'simply' really :) Just showing that HOC is now always a good option :) Closing this now since you have no problem with keeping render prop variant exposed as well.
