### ISSUE TITLE
Setting values on the form later?

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#45]
In the `react-form` I had a component like this which essentially loads data asynchronously while the form is being already displayed empty giving better UX. Would it be too problematic to have `values` prop in Informed as well which would override the state completely on every update?

```js
export class FormLoader extends React.Component {
  state = {}
  async componentDidMount() {
    if (!this.props.shouldLoad) {
      return
    }
    const values = await this.props.loader()
    this.setState({ values })
  }
  render() {
    const { shouldLoad, loader, ...props } = this.props
    return <Form values={this.state.values} {...props} />
  }
}
```

**Comment by joepuzzo** [comment]
Use set state or set values to do this. Dynamic things should use functions l.

**Comment by FredyC** [comment]
Ah, haven't thought about that. Good stuff 👍
