### ISSUE TITLE
Updating formState.touched on radio button

### ISSUE THREAD

**Issue by basicdays** [joepuzzo/informed#46]
Awesome library that you've written. Just ran into a small bug.

When I'm keyboarding through the form and tab to a radio group, if I hit the space bar to select the current highlighted radio button, the `formState.touched` is not updated. If I use an arrow key to highlight a different radio button instead, then the touched object is correctly updated. I did notice however, that the radio group's validation is correctly ran and the `formState.values` object is correctly updated.

The reason I need the touched object is because I'm currently using the `formState.touched` to determine if the user has at least tried each form element before I enable the submit button.

Thanks for your time.

**Comment by joepuzzo** [comment]
Yeah so the problem here is that informeds definition of touched and yours are slightly different. Touched occurs onBlur in my default inputs. So this is actually correct behavior. If u want it to work differently you could always create a custom input

**Comment by basicdays** [comment]
Aah gotcha. Wasn't sure if it was inconsistent behavior or not, but it makes sense it's spec'ed that way. I can work with that, thanks for the really quick response.
