### ISSUE TITLE
Need export makePathArray in npm package

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [joepuzzo/informed#48]
Hi,

You have many great functions and classes. Why is not published in `npm` package?

I would be happy:
* `makePathArray`
* `ObjectMap`
* context's from `informed/src/Context/index.js`

Its will be very helpful to implement self custom fields.

**Comment by joepuzzo** [comment]
You can create custom inputs.. check out the custom input section of docs

**Comment by dzwiedziu-nkg** [comment]
When you export `BasicRadioGroup` I will get all what I need. But I think it is the good idea to publish `makePathArray` and `ObjectMap` as separated library.

**Comment by joepuzzo** [comment]
I will export Basic Radio Group but im not going to export internal functions

**Comment by joepuzzo** [comment]
Basic Radio Group is now exported.
