### ISSUE TITLE
docs: page for migration path from react-form

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#5]
I'm starting with the lib; i'm seeing this should be added for new users coming from react-form

**Comment by joepuzzo** [comment]
Good idea.. for now take a look at the changelog

**Comment by 0xdevalias** [comment]
Some words about the difference/why a new version would be good too. And perhaps some info on whether react-forms is EOL, or likely to be maintained still.

**Comment by joepuzzo** [comment]
Updated the readme for REACT form with info on the transition. Working on migration page. I also updated changelog with some more info.
