### ISSUE TITLE
Dynamic fields - bug when field props changed

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [joepuzzo/informed#53]
During writing example for #49 I saw bug when field is not recreating but only field name is changed.

Simple example: https://dzwiedziu-nkg.github.io/test-react-informed/
Source: https://github.com/dzwiedziu-nkg/test-react-informed

Bug: field store old value when `field` props changed. 

It happen when we use conditional renders i.e. my example. React use Virtual DOM. Before unomunt and mount new component's instances try to update only props. React create new instance or discard component only when there's no other way.

**Comment by joepuzzo** [comment]
V2 is in progress and this is priority!

**Comment by joepuzzo** [comment]
Check out V2!!!
