### ISSUE TITLE
Dynamically adjust validateOn* props for a field

### ISSUE THREAD

**Issue by ajwootto** [joepuzzo/informed#57]
My use case is that I would like to validate an input on change, but only once the user has entered data in the field and blurred it (dirty and touched).  So the flow would be:

User enters page, input hasn't been touched
User clicks input, enters invalid text, error doesn't appear until user has blurred input 
User clicks away, Input is now touched and error appears
User clicks on input again, modifies entered data and makes it valid. Input error state should be cleared the moment the entered data is valid (not on blur)

As far as I can tell, the only way to achieve this is to somehow adjust the value of validateOnChange from false (before the input is touched) to true (after the input has been touched)

I tried to accomplish this by creating a chain of HOCs that wrap the asField HOC to change the validateOnChange prop before its passed in, using the withFieldState HOC at a higher level to determine whether the field has been touched yet. However, this creates some crazy recursion loop and crashes the page so I don't think I should be doing that.

Let me know if I'm missing something obvious here..

**Edit** 
I think I managed to get it working with the HOC chain using something like this:

```javascript
const withValidation = (Component) => {
  // Validate on change after the field has been interacted with the first time
  return (props) => {
    const {touched, pristine, ...rest} = props
    return <Component {...rest} validateOnBlur validateOnChange={touched && !pristine}/>
  }
}

const withInputFieldState = (Component) => {
  return withFormState((props) => {
    const {formState, ...rest} = props
    const touched = formState.touched[props.field]
    const pristine = formState.pristine[props.field]
    return <Component {...rest} touched={touched} pristine={pristine}/>
  })
}

export default withInputFieldState(withValidation(asField(Text)))
```
It seems fairly ugly though

**Comment by joepuzzo** [comment]
So if i'm understanding correctly what you want is validateOnTouchAfterBlur lol right?

**Comment by ajwootto** [comment]
or validateOnChangeAfterBlur I guess ;)

I wonder if there's a more general way to just have the validateOn_ props take a function which is passed the current field state?

**Comment by joepuzzo** [comment]
It is now possible to change these props in V2
