### ISSUE TITLE
Unable to change external reference for 'onSubmit' from a Rerender

### ISSUE THREAD

**Issue by evankellogg** [joepuzzo/informed#59]
`<Form className={classes.form} onSubmit={e => (isRegistration ? register(e, this.state) : login(e, this.state)) } >`

**Comment by evankellogg** [comment]
`  <Form
                    className={classes.form}
                    onSubmit={e => (isRegistration
                      ? register(e, this.state)
                      : login(e, this.state))
                    }
                  >`

**Comment by joepuzzo** [comment]
@evankellogg Hey sorry i forgot to close this but its fixed now . :)
