### ISSUE TITLE
asField: missing export (to use it on custom inputs)

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#6]
`asField` can be useful for creating custom inputs. It is not exported right now.

**Comment by joepuzzo** [comment]
Ahh i knew i fogot somthing i will get this up by end of day

**Comment by joepuzzo** [comment]
I added this but am still working on the documentation page for it. But if you need it now its there.

**Comment by jacargentina** [comment]
Yeah, I'm using it already. 👌
