### ISSUE TITLE
Array - Add/Remove value

### ISSUE THREAD

**Issue by yehuda54** [joepuzzo/informed#61]
I have a fairly complex form, with nested values and arrays.  On the form, you have the ability to add/remove array values.  I am currently using react-form and I am able to accomplish this via formApi.addValue() / formApi.removeValue() as documented on https://react-form.js.org/#/

However, I am in the process of converting over to informed. ... but I dont see this method.  Additionally, there is no example on help pages on how to accomplish this as you did on react-form docs.  

**What is the correct way in "informed" to dynamically add / remove values from an array?**

FYI: If you want users to switch over to the new informed lib., you should have the parallel examples so the user can compare the old implementation with the new implementation.   The documentation is much better on the react-form site.

Thank you for a great form library.

**Comment by joepuzzo** [comment]
So i am aware of this and unfortunately dont have a solve atm. There is already an issue out for this so im going to close this one and reference that one. https://github.com/joepuzzo/informed/issues/8
