### ISSUE TITLE
passing props to component ?

### ISSUE THREAD

**Issue by terencechow** [joepuzzo/informed#62]
I have a component which I pass to `Form`. How do I pass props to it? 

    <Form component={FormContent} someProp='test />

```
class FormContent extends React.Component {
  constructor(props){
    super(props)
    // prop.someProp doesnt exist
    }
    
     ...
}
```

**Comment by joepuzzo** [comment]
I would not use `component=` use one of the other methods of rendering a form instead.

**Comment by joepuzzo** [comment]
Closing as this is not an issue
