### ISSUE TITLE
Field hooks for setting number on change

### ISSUE THREAD

**Issue by yehuda54** [joepuzzo/informed#63]
One of my fields in my initial value json object state are number values, not strings.  When I load the value, if the field is for options in a select box, the value does not match any options because select is only looking for a string type and not number types (it appears). Is there hook available to prepare/format the value for the ui display?

Additionally, when submitting the form, the value is pushed to the state values json  object as a string and not a number type.

Can I utilize "onValueChange" parse the string back to a number and set the state as a number? If yes, can you please provide a sample on how to properly do it?

Thank you

**Comment by joepuzzo** [comment]
Can you give an example of this issue in a code sandbox so i can take a look.
