### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/core-js/json/stringify'

### ISSUE THREAD

**Issue by chrism2671** [joepuzzo/informed#64]
I'm a newbie. I've installed informed as per the docs, but am getting the following error when I try to `yarn start`.

```
Failed to compile.

./node_modules/informed/dist/index.js
Module not found: Can't resolve '@babel/runtime/core-js/json/stringify' in '/home/chris/code/elixir/blog/blog/node_modules/informed/dist'
```
What am I doing wrong?

PS I have done `npm install --save babel-runtime` in my project, although I don't see why this is necessary.

**Comment by Clairly** [comment]
I'm seeing this too. 

```
 ERROR  Failed to compile with 4 errors

These dependencies were not found:

* @babel/runtime/core-js/json/stringify in ./node_modules/informed/dist/index.js
* @babel/runtime/core-js/map in ./node_modules/informed/dist/index.js
* @babel/runtime/core-js/object/keys in ./node_modules/informed/dist/index.js
* @babel/runtime/core-js/promise in ./node_modules/informed/dist/index.js

To install them, you can run: npm install --save @babel/runtime/core-js/json/stringify @babel/runtime/core-js/map @babel/runtime/core-js/object/keys @babel/runtime/core-js/promise
```

**Comment by chasevida** [comment]
I ran into this issue just now too but did manage to get it working.

You will need to ensure you have the right versions of both `@babel/runtime` and `@babel/plugin-transform-runtime`... that is if you are using a later version of babel, all versions need to match all other babel versions (at least that's what's been my issue. Then add the following to your `.babelrcjs`:

```
"plugins": [
    // ...other plugins
    "@babel/plugin-transform-runtime"
  ],
```

But yeah, not sure why the `npm` version needs this, I'd prefer the npm distribution to be independently deployable without needing babel installs. There may be a good reason for this that I just don't know about - total newbie to this repo.

**Comment by samlecuyer** [comment]
Shouldn't informed use a .babelrc to enable this plugin?

**Comment by samlecuyer** [comment]
Looks like in `@babel/runtime@7.0.0-beta.56` they split the runtime into 2 packages. This package is built with a pre-56 version but will allow a post-55 version to be installed.

Adding the following to your package.json should fix this
```
"@babel/runtime": "<=7.0.0-beta.55",
```

[v7.0.0-beta.56]( https://github.com/babel/babel/commit/6695f5e2f7a2cfe49acfb63508dc4f1812185c7f#diff-a0a234e4064e6815dfc180424ff80914)

**Comment by jacargentina** [comment]
@joepuzzo can you update Babel dips to latest .rc-1 please? maybe that way this is fixed for all.

**Comment by joepuzzo** [comment]
I can give this a shot yes

**Comment by gholaday** [comment]
I tried doing @samlecuyer 's fix, but its still giving me the error. Im using yarn instead of npm

**Comment by joepuzzo** [comment]
@jacargentina when you say to the latest rc-1 do you mean beta.56 ??  And how would that fix this issue?

**Comment by jacargentina** [comment]
@joepuzzo i don't think its beta.56; its a release candidate published on August 9

In my project using informed as a dependency, current master gives the error for this issue, ie: `Module not found: Can't resolve '@babel/runtime/core-js/json/stringify'`

Updating to latest npm dependencies, solves that error, and I can use informed again without problems. Does all this responds your doubts?

**Comment by joepuzzo** [comment]
When you say "Updating to latest npm dependencies" what do you mean. What i find strange that according to `@babel/plugin-transform-runtime` docs, I should be able to simply include `@babel/runtime` as a normal dep of `informed` and should be all set. Obviously this is not the case as it seems you guys need to manually install `@babel/runtime`. <<< was that the fix you did?

**Comment by joepuzzo** [comment]
Just saw your PR im manually merging it now

**Comment by joepuzzo** [comment]
That was a fun one :) thanks for the PR @jacargentina . one thing i had to change in there was update the webpack config for the dist and also add corejs babel plugin as a normal dep.

**Comment by yehuda54** [comment]
I am still having the same issue after running "npm update" and bringing in "informed": "^1.10.3"

Is there anything else I need to do? I am using "create-react-app" ( #71 )

**Comment by yehuda54** [comment]
"informed": "^1.10.4" build solved the issue -- thank you for fixing it

**Comment by joepuzzo** [comment]
Yup sorry the fix took a few tries lol
