### ISSUE TITLE
formState.submits count

### ISSUE THREAD

**Issue by devourment77** [joepuzzo/informed#66]
Previously with react-forms, there was a `submits` attribute that included the count of form submits / attempts.  This looks to be omitted from informed, any reason?  Could it come back?

We use it in a few places and is one of the reasons we have not migrated to informed just yet.

**Comment by joepuzzo** [comment]
Ok im adding this now .. question tho.. would you want it to increment even if it fails submission due to an invalid form?

**Comment by devourment77** [comment]
Yes, that is how react-forms worked. It was basically a form submission (valid or invalid).

**Comment by joepuzzo** [comment]
This is in the latest version!
