### ISSUE TITLE
How to create multi-step form?

### ISSUE THREAD

**Issue by vfonic** [joepuzzo/informed#67]
I'm trying to build a multi-step form.

It has these requirements:
- It will consist of couple of steps. (Thank you Captain Obvious!)
- Each step will have to be valid before user can continue to the next step.
- User should be able to navigate back to the previous step
- It should be possible to pre-set the next step fields based on current step field values

I'm wondering if I'm doing something wrong.

Here's an example that fails to set the next step value for field host:
https://codesandbox.io/s/pyq9zlm8vx

Here's an example that resets all the values when user goes back to previous step:
https://codesandbox.io/s/1y7kwln247

This issue is related to this issue: https://github.com/joepuzzo/informed/issues/30#issuecomment-412135380

I'm thinking of a workaround. I'm trying to sett all fields, one-by-one, upon first rendering of the next step. I would have a parent component with `this.state.values` that will store the form's state, and, on step change, it would do something like:

```jsx
Object.keys(this.state.values).forEach(key => {
  // trying to set field value for a field that's currently not rendered will result in "Cannot read property `config`"
  if (this.formApi.fieldExists(key)) {
    this.formApi.setValue(key, this.state.values[key]);
  }
});
```

This seems like a total overkill. Any suggestions how I can avoid this?

**Comment by joepuzzo** [comment]
Just have a form at each step and save the values along the way for final submission

**Comment by joepuzzo** [comment]
Since this is not an issue im going to close but feel free to post additional questions

**Comment by rafenden** [comment]
> Just have a form at each step and save the values along the way for final submission

Could you post an example, please? This seems to be a common use case.
