### ISSUE TITLE
File objects replaced with empty plain objects on setValue call

### ISSUE THREAD

**Issue by kyleroberthammond** [joepuzzo/informed#70]
Same issue as this from react-form

https://github.com/react-tools/react-form/issues/207

**Comment by kyleroberthammond** [comment]
Ignore my ignorance but why are you stringfy and then parsing the object? 
Whats the purpose? Is it for copying the object?

**Comment by pttsky** [comment]
Just ran into the same situation. I saw there was no example in docs with file input and tried `asField`, which helped everytime... But now I will need to write code to save the file directly into the store.

**Comment by joepuzzo** [comment]
Cant you save the file separately from informed? Even in the react docs they mention that file is an uncontrolled input. All of informds are controlled. https://reactjs.org/docs/forms.html

**Comment by joepuzzo** [comment]
Might work now with V2 give it a shot an  reopen if its still an issue
