### ISSUE TITLE
React-Native

### ISSUE THREAD

**Issue by AnimaWolf** [joepuzzo/informed#73]
Hey, I love this library and use it wherever I possibly can. I was wondering if there are any plans for a react-native version?

**Comment by joepuzzo** [comment]
Hey so i don't have any plans to support react native. I don't personally use react native so im not sure what steps would need to be taken but if my understanding is correct should this lib simply work in react native as its still a react app?? What steps are needed for support?

**Comment by AnimaWolf** [comment]
React-native has no access to elements like form, input, etc... It would require a different structure on some levels using React-Native elements such as TextInput which has a very different API than the regular input elements.

If I weren't so busy right now I'd take a swing at it to port this. If I have the time and I come up with something I'll be sure to contact you.

**Comment by joepuzzo** [comment]
Sounds good

**Comment by joepuzzo** [comment]
I think you can achieve this by simply creating custom inputs.

**Comment by joepuzzo** [comment]
You can totally use this with react native. I have tried it myself and it works! Just create custom inputs
