### ISSUE TITLE
How to reset form after submit?

### ISSUE THREAD

**Issue by kotsoft** [joepuzzo/informed#76]
Hi, thank you for this great library. I would like the ability to access the formApi in the onSubmit callback so I can call reset(). Currently I believe just the form values get passed to it, but I think if the formApi could also be passed to it that would work better for me. Currently to do what I need to do, I don't believe I can use a stateless component.

**Comment by alaycock** [comment]
To get access to the Form API, you can use the `getApi` prop to gain access to the `formApi`.
```
import React from "react";
import { Form } from "informed";

class MyComponent extends React.Component {
  saveApi(formApi) {
    this.formApi = formApi;
  }

  render () {
    return (
      <Form getApi={this.saveApi} onSubmit={() => this.formApi.reset()}>
        ...
      </Form>
    );
  }
}
```

**Comment by joepuzzo** [comment]
^^^ What he said lol

**Comment by sushmitg** [comment]
The `getApi` doesn't work in a dynamically rendered functional component. For example, in @alaycock's code if you convert `MyComponent` into a functional component :

```
const MyFormComponent = (props) => {
    let loginFormApi; 

    const saveApi = (formApi) => {
      loginFormApi = formApi;
    }

    return (
      <Form getApi={saveApi} onSubmit={() => loginFormApi.reset()}>
        ...
      </Form>
    );
}
```

And if this component is inside a tab except the first one.

```
const Tabs = (props) => {
  return (
       <Nav tabs>
          <NavLink
            className={getActiveTabClass("registration")}
            onClick={() => setActiveTab("registration")} >
            Registration
          </NavLink>
          <NavLink
            className={getActiveTabClass("login")}
            onClick={() => setActiveTab("login")} >
            Login
          </NavLink>
      </Nav>
      <TabContent activeTab={activeTab}>
        <TabPane tabId="registration">
          <MyComponent {...props} />
        </TabPane>
        <TabPane tabId="login">
          <MyFormComponent {...props} />
        </TabPane>
      </TabContent>
  )
}
```

Now let's say you click on the login tab and the tab changes and the login form is rendered.
Now when you submit the login form, the code breaks and throws the following error:
`Cannot read property 'reset' of undefined`

This works for the function component "MyComponent" in the first tab aka the registration tab in the example. It's probably because the second <TabPane> initially has "display: none".

**Comment by joepuzzo** [comment]
This does not work because you cant store a reference to something in a let.. you need to create a ref and refer to current. See the useRef hook docs in react

**Comment by sushmitg** [comment]
> This does not work because you cant store a reference to something in a let.. you need to create a ref and refer to current. See the useRef hook docs in react

But the same code works for `<MyComponent {...props} />` Component in first tab?

**Comment by Jucesr** [comment]
```js
import React, {useRef} from 'react'

const MyFormComponent = (props) => {
    let loginFormApi = useRef(null); 

    const saveApi = (formApi) => {
      loginFormApi = formApi;
    }

    return (
      <Form getApi={saveApi} onSubmit={() => loginFormApi.reset()}>
        ...
      </Form>
    );
}
```

This worked for me.

**Comment by joepuzzo** [comment]
@Jucesr There is a better way 

```
const apiRef = useRef();

  return (
      <Form apiRef={apiRef}>
           ...
      </Form>
  );
```

**Comment by Jordaneisenburger** [comment]
@joepuzzo I tried your solution but useRef isn't a function, it's an object and according to the informed docs we need to pass a function right ?

PS: apiRef={apiRef} needs to be getApi={apiRef} I assume

**Comment by joepuzzo** [comment]
useRef is a react thing :) https://reactjs.org/docs/hooks-reference.html#useref 

Sorry i should have shown that import and not assumed users would know that

**Comment by joepuzzo** [comment]
So the apiRef does work :) just need to import hook from react

**Comment by Jordaneisenburger** [comment]
I'm aware of useRef being a hook but kept giving me `current:null` for some reason. But all good since I got it working now. Thanks for the quick response!
