### ISSUE TITLE
How to add a date fields?

### ISSUE THREAD

**Issue by Mulli** [joepuzzo/informed#77]
I am new to React and Forms in general.
however, I am having fun using informed!

Documentation is missing date field and date picker suggestions.
Can you provide please?

**Comment by JaffParker** [comment]
It's actually pretty simple, considering that Informed exposes directly field APIs such as `setTouched` and `setValue`. Personally, I like using [React DatePicker](https://reactdatepicker.com/) as it allows much customization and simply gives you the date value in the `onChange` handler. So here's the code you can use to make it work:

```jsx
import React from 'react'
import DatePicker from 'react-datepicker/lib/datepicker'
import {asField} from 'informed'

export const DateInput = asField(({
  fieldState: {value},
  fieldApi: {setTouched, setValue},
  ...props
}) => <DatePicker onFocus={() => setTouched(true)} onChange={date => setValue(date)}
                  selected={value} openToDate={value} {...props} />)
```

Then you use it simply like this:

```jsx
<DateInput field="date" />
```

**Comment by JaffParker** [comment]
And as I just noticed, an alternative syntax is available to achieve this. It's not documented, but it was _the_ way in the old react-form, and it is in the exports (it's also my preferred), so here we go:

```jsx
import React from 'react'
import DatePicker from 'react-datepicker/lib/datepicker'
import {Field} from 'informed'

export const DateInput = ({name, ...props}) =>
  <Field field={name}>
    {({
      fieldState: {value},
      fieldApi: {setTouched, setValue}
    }) => <DatePicker onFocus={() => setTouched(true)} onChange={date => setValue(date)}
                      selected={value} openToDate={value} {...props} />
    }
  </Field>
```

I find this way gives me more control over the component, and it allows for clear separation between your props and the Informed's field props.

**Comment by joepuzzo** [comment]
Can we close this? I too btw habe used react date picker with success :)
