### ISSUE TITLE
values from preSubmit are set in the state

### ISSUE THREAD

**Issue by Volune** [joepuzzo/informed#79]
`informed@1.10.4`

I tried to use `preSubmit` to convert one select value `"true"`/`"false"` to an actual boolean. But the boolean is then set in the form state, breaking the selected `<option>`. I've read in the doc that that should not happen.

It seems related to that line: https://github.com/joepuzzo/informed/blob/master/src/Controller/FormController.js#L298

**Comment by joepuzzo** [comment]
You could always just convert before you do whatever it is you do after onSubmit

**Comment by Redmega** [comment]
No, the doc is patently incorrect. I suppose the right way forward depends on @joepuzzo's intent. Was the intent for `preSubmit()` to be a pure function between the validation and submission steps, without mutating the state? Or was the intent for it to mutate?

If the intent was for it NOT to mutate, the docs do not need to be changed -- the code needs to be fixed to reflect the proper use case.

If the intent was for it to mutate, that's a simpler fix as the docs just need to be updated.

**Comment by joepuzzo** [comment]
removed presubmit
