### ISSUE TITLE
Please can we have addValue and removeValue back?!

### ISSUE THREAD

**Issue by joewestcott** [joepuzzo/informed#8]

**Comment by joepuzzo** [comment]
You dont need them. Look at the dynamic fields section of the new docs.

**Comment by joewestcott** [comment]
[Here?](https://joepuzzo.github.io/informed/?selectedKind=Dynamic%20Forms&selectedStory=Dynamic%20Fields&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

It doesn't have an example with a field array. How would I go about implimenting a button to add a  'friend' in [this example](https://joepuzzo.github.io/informed/?selectedKind=Arrays&selectedStory=Array%20Of%20Scopes&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)?

Thanks!

**Comment by joepuzzo** [comment]
Yup, here you go! https://codesandbox.io/s/q9q804wo09

**Comment by joepuzzo** [comment]
I used a map function in the example above, however, you could just as easily use iteration over an integer.

**Comment by joepuzzo** [comment]
Also i noticed i may have bug when removing but i can look into that and get back to you

**Comment by joewestcott** [comment]
Thankyou.
However, the example provided requires a lot of extra boilerplate. It places an additional burden onto the developer to sync data between form state provided by the library, and state held by additional react components which just exist to work around this problem. There's more functionality to add, too, such as removeValue, swapValue, and initialising the array length from initialState which is not provided in the example. These are things that `react-form` handled very nicely.

Also, I think adding a array item (friend, in your example) *should* manipulate the form state, even if a value has not been provided, or any fields have been touched. A 'blank' friend is still form data, and in my opinion should be handled by the form library.

Interested to hear your thoughts.

**Comment by joepuzzo** [comment]
I added remove value to that example. I think there is just an issue with the field getting completely removed on unmount.. Initializing the array length? How did you achive this before? and how would adding add and remove achieve that? You could just use `initialValues` right? 

As to your second point. Technically it has nothing to do with the form state. I happened to name the array friends but really its the data that represents the amount of fields to render. 

Now all this being said.. i don't disagree that there is a way to write this internally but i would need some time to audit and make sure that its something that i can add that will not introduce to much complexity internally. One of the main goals of the rewrite was to not over-bloat the lib like before and that means i want to think before i just go adding every feature under the sun :) ☀️ . Which was, in my opinion, a mistake i made in the past.

**Comment by joewestcott** [comment]
Thankyou for working with me on this.

> Initializing the array length? How did you achive this before?

Setting initialValues on the `<Form>` component to `{ friends: [{ name: 'one' }, { name: 'two' }] }`  would create two friend sections with prefilled names. Since the amount of 'friend' sections is now up to the React component and it's local state, this initialising functionality would have re-implemented by the developer too.

> but really its the data that represents the amount of fields to render.

The form state data? In your example it's the react component that holds the amount of fields to render. There would be no way to reuse the 'friends' data in another part of the form without lifting that local state up to form level. In doing so, you're basically working with (and syncing) two form states.


I do understand your position, and appreciate your work. Unfortunately I have a codebase depending on addValue and removeValue, so if I cannot convince you to [fix react-form](https://github.com/react-tools/react-form/pulls), I'll have to fork it just to accept the commits by the community. :(

**Comment by joepuzzo** [comment]
Dont fork.. create a pr if you think u can add it. I will look into it eventually but if you create a pr then i could audit that.

**Comment by KaRkY** [comment]
I tried to make it work with setValue but the problem is that field is not registered and then this error is thrown: "Cannot read property 'config' of undefined"

I think that array handlig should be done from form state and not from outside like in the example.

And another problem with hte example is when you add 3 friends and delete 2nd you get state like this: ["Friend1", null, "Friend3"] it should be ["Friend1", "Friend3"].

**Comment by joewestcott** [comment]
@joepuzzo I'm referring to forking react-form, due to regressions in the last few releases.

**Comment by vfonic** [comment]
> I do understand your position, and appreciate your work. Unfortunately I have a codebase depending on addValue and removeValue, so if I cannot convince you to fix react-form, I'll have to fork it just to accept the commits by the community. :(

How about adding @joewestcott as a maintainer for react-form project? @joepuzzo do you think it's feasible option to have react-form along with the new informed package?

I like react-form's API, and the fact that it uses render props (child as a function). This is also becoming more and more mainstream especially with the new React Context API.

**Comment by joepuzzo** [comment]
So this library does use render props all over the place? And heavily uses the new context api. And as for react form. I dont have that control. You would have to talk to tanner ( the person that actually controlls react form ) 

I rewrote react form originally from scratch and informed is very similar and will be mantained and uses all the latest and greatest react has to offer.

**Comment by joepuzzo** [comment]
Sorry i bave been busy with other issues and not put my brain on this one yet. This will be my next fix

**Comment by joepuzzo** [comment]
This is not an easy fix haha may take some time to get this one out there.

**Comment by yehuda54** [comment]
If I can give a crack at a solution I got working after raising issue #61 

Let me preface that I am long time developer but practically a beginner at ES6 and React ... so if it is a problematic solution or I can improve on the design, please point it out because I would love to learn. 

I added two method to my class component (note: using lodash helper funcitons)

    addValue(property) {
        const propertyState = _.defaultTo(this.formApi.getValue(property), []);

        this.formApi.setValues(
            Object.assign({},
                this.formApi.getState().values,
                {[property]: ([...propertyState, ''])}))
    }

    removeValue(property, index) {
        const propertyState = _.defaultTo(this.formApi.getValue(property), []);

        this.formApi.setValues(
            Object.assign({},
                this.formApi.getState().values,
                {[property]: propertyState.filter((value, i) => index !== i ) }
            ))
    }

and bound the methods 'this' in the class constructor and also bound the formAPI (as mentioned in the documentation for external manipulation):
        this.setFormApi = this.setFormApi.bind(this)

        this.addValue = this.addValue.bind(this)
        this.removeValue = this.removeValue.bind(this)

In my form components, I simply use the methods and pass them in as props:
<Form
                    **getApi={this.setFormApi}**
                    onSubmit={config => this.updateFormState({ config })}>
                    {({ formState, formApi }) => (
                        <div>
                            <MyComponent
                                values={formState.values.list}
                                **addValue={()=> this.addValue('list')}
                                removeValue={(index) => this.removeValue('list', index)}**/>


                            <button type="submit" className="mb-4 btn btn-primary">
                                Submit
                            </button>
                        </div>
                    )}
                </Form>


function MyComponent(props) {
    const values = _.get(props, 'values', [])
    **const addValue = props.addValue
    const removeValue = props.removeValue**

    return (
        <section >
            <div className="row">
                <div className="col-auto">
                    <h4 className="one">List Values</h4>
                </div>
                <div className="col-auto">
                    <button
                        onClick={() => **addValue()** }
                        type="button" className="btn btn-sm btn-outline-success ">Add Item</button>
                </div>
            </div>

            {values.map((value, i) => (
                <div key={`item-${i}`} className="form-row align-items-center">
                    <div className="col-sm-11">
                        <Text field={`item[${i}]`} id={`item-${i}`} className="form-control mb-1" />
                    </div>
                    <div className="col-sm-1">
                        <button
                            onClick={() => **removeValue(i)**}
                            type="button" className="btn btn-sm btn-outline-danger pull-right">Remove</button>
                    </div>
                </div>
            ))}

        </section>
    )
}

**Comment by joepuzzo** [comment]
Unfortunately its not this simple. When each fieild mounts.. it calls a register function to register itself with informed. When you add or remove it would have to reregister in some way. This will involve a much larger rewrite.

**Comment by joepuzzo** [comment]
In other words this was a design flaw on my part. My internal data structure needs to change to support this.

**Comment by NelsonBrandao** [comment]
I was trying to implement a form with an 'Add another' feature, similar to what was discussed.

First I was trying to add another empty object to the array using the `setValue` method but was getting this error `Cannot read property 'config' of undefined` similar to what another user reported earlier.

But I was able to get around this using the `setValues({ ... })`. From my tests adding items, removing items from any order on the array and validations are all working.

My code

```
onAddAnother = (formApi) => () => {
    formApi.setValues({ products: [ ...formApi.getValue('products'), {} ] });
}

onRemove = (formApi, index) => () => {
   // I'm using setValues instead of setValue
    formApi.setValues({
        products: [
            ...formApi.getValue('products').slice(0, index),
            ...formApi.getValue('products').slice(index + 1),
        ],
    });
}

render () {
    return (
            <Form
                initialValues={{ products: [ { name: 'FAKE_NAME' } ] }}
            >
                {({ formApi, formState }) => (
                    <React.Fragment>
                        {formState.values.products.map((_, index) => (
                            <Scope key={index} scope={`products-[${index}]`}>
                                <InputTextAsField
                                    label="Product Name"
                                    type="text"
                                    field="name"
                                />
                                <ButtonIcon
                                    type="button"
                                    icon="close"
                                    onClick={this.onRemove(formApi, index)}
                                />
                            </Scope>
                        ))}
                        <ButtonIcon
                             type="button"
                             icon="plus"
                             onClick={this.onAddAnother(formApi)}
                        />
                     </React.Fragment>
                    )}
              </Form>
     )
}
```

Do you see any problem with this @joepuzzo

**Comment by crusoexia** [comment]
Same situation, need a better and elegant solution.

**Comment by joepuzzo** [comment]
Working on it in V2!! its super easy and cool thanks to new version of react and effects!

**Comment by reddybashanaguru** [comment]
> Also i noticed i may have bug when removing but i can look into that and get back to you

Can u please update on this asap??

**Comment by joepuzzo** [comment]
Going to solve in V2

**Comment by joepuzzo** [comment]
ITs finally HERE!!!! Check out V2 now! ( don't forget it requires React 16.8.1 )

**Comment by huykon** [comment]
how to make initialValues form is dynamic?

**Comment by joepuzzo** [comment]
Initial values are already dynamic but they wont show up until you reset the form. Remember they are “Initial Values”

**Comment by huykon** [comment]
yes. now I have to set a random key for form to each time update the values of form. But I think this is not good solution for it. 
Thanks

**Comment by joepuzzo** [comment]
Why do you need a random key? I dont follow.

**Comment by huykon** [comment]
random key help me refresh form after each I want chagne the initial values
