### ISSUE TITLE
How to do controlled inputs with informed?

### ISSUE THREAD

**Issue by AndrewRayCode** [joepuzzo/informed#83]
This library looks interesting, I was looking for form abstractions that use the context API to reduce the number of props you need to pass from a parent `<Form>` to child `<Inputs>`, and it looks like you're doing that! 👏 

From looking at the [Input props](https://joepuzzo.github.io/informed/?selectedKind=Inputs&selectedStory=Intro&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) it looks like you only allow for uncontrolled inputs with `initialValue`, and attempt to get around the controlled input probelm with allowing arbitrary lookups for the `field` prop?

I'm always scared about writing code in strings, and would prefer to manually pass it in with a `value={}` and have the component consuming the form hang on to the form state (or at least have the option to). This way you could do things like programmatic updating of fields in response to events outside the form (and generally other stuff you can do with controlled components)

**Comment by AndrewRayCode** [comment]
I mean the end consumer of this library sees all inputs as uncontrolled, which takes away some flexibility.

Do you think it's theoretically possible to have end consumer treat them like controlled inputs and pass in `<Text name="arbitrary" value={formData.arbitrary} />` ?

I was thinking something like this to have the parent component control form data state:

https://gist.github.com/AndrewRayCode/c7313e3f9ad3fac9d382e9868b538b2e

**Comment by joepuzzo** [comment]
That defeats the purpose of the lib. The purpose of informed is to "Control" the input for the user, but still leave it flexible enough for them to also control it when necessary

**Comment by joepuzzo** [comment]
Closing as its not an issue
