### ISSUE TITLE
Scope API?

### ISSUE THREAD

**Issue by jheising** [joepuzzo/informed#84]
Is it possible to utilize a formApi and formState for a Scope? A self encapsulated api and state for a Scope would make it really easy to be able to move sub-forms around and not have to worry about where they live in the context of their parents.

I've tried using:

```
<Scope scope="medications">
    {({formApi, formState}) => (<div></div>)}
</Scope
```

But react returns an error that says: `Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

**Comment by joepuzzo** [comment]
Hmm there might be a limitation but let me look into it

**Comment by joepuzzo** [comment]
TBH i really want to remove scopes from informed as you can easily achieve scopes with field names like `friends.name`

**Comment by joepuzzo** [comment]
Update I have not documented this yet but I now export a `useScopedApi` hook
