### ISSUE TITLE
Can anyone recommend a mask library?

### ISSUE THREAD

**Issue by rscotten** [joepuzzo/informed#86]
Hello,

I want to add an input mask for a phone number.  I know there is a mask prop that allows you to pass in a function, but I don't want to roll my own masking function to format a phone number.

I know there are component libraries like `react-text-mask` and `react-input-mask`, and to use these with `informed` I'd have to use informed's `asField()` HOC, which is not ideal.

Can anyone recommend a good package that has the usual mask functions (e.g. allows masking phone numbers, etc.) for plugging into the mask prop?

**Comment by victorbf** [comment]
I need one as well :(

**Comment by joepuzzo** [comment]
You can now impliment your own mask functions with format, parse, and mask.. see docs for details in V2
