### ISSUE TITLE
Mask Attribute Is Adding Mask to Every Character of Input Value

### ISSUE THREAD

**Issue by deusprogrammer** [joepuzzo/informed#87]
I have placed a mask attribute on some of my fields.  Instead of adding the mask once, it adds it once for every character I type in, including when I hit backspace.

For example if I have a field like the following:

<Text field="foo" mask={value => value + " kg"} />

When I type the following:

"10"

The input field will become "1 kg0 kg".

Am I missing something here, or is this broken?

I'm using informed version 1.10.5 and using Chrome version 69

**Comment by joepuzzo** [comment]
No this is expected behavior.. i need to add format and parse props but have not had the time. In the mean time i use Regex to mask things for my use-cases.

**Comment by deusprogrammer** [comment]
Awesome, that’s what I ended up doing as well.  Thanks for your efforts.  Your library made my project far easier.

The only thing I would recommend is updating the documentation to mention this.  If I get a chance I will fork your repo and add those features.
