### ISSUE TITLE
How do you make custom inputs?

### ISSUE THREAD

**Issue by Jordan4jc** [joepuzzo/informed#9]
I'm using the Material UI library and want to make inputs that work with this library that look like the material ones using their components. I don't understand how to make custom inputs even after diving into the code to figure out how the ones that are shipped with it are created.

I keep getting an undefined error at `replace` and I don't know why

I've tried setting up my input super basic to try to figure out where this error is coming from and I can't.

```
import React, { Component } from 'react'
import { asField } from 'informed';

class CustomInput extends Component {
  render() {
    console.log(this.props)
    const { fieldApi, fieldState, ...props } = this.props;
    const {
      value
    } = fieldState;
    const {
      setValue,
      setTouched
    } = fieldApi;
    const {
      onChange,
      onBlur,
      forwardedRef,
      ...rest
    } = props
    return (
      <input
          {...rest}
          ref={forwardedRef}
          value={!value && value !== 0 ? '' : value}
          onChange={e => {
            setValue(e.target.value)
            if (onChange) {
              onChange(e)
            }
          }}
          onBlur={e => {
            setTouched()
            if (onBlur) {
              onBlur(e)
            }
          }}
      />
    );
  }
}

export default asField(CustomInput);
```

This is basically just the same component as the `Text` component but I'm getting a `Cannot read property 'replace' of undefined` error

Could use some help with this and also maybe an update to the docs on how one might actually build their own custom informed inputs

**Comment by fletcher91** [comment]
Bumped into this as well, I think passing a `field` string prop to the component fixed the issue, but the path was quite chaotic so I'm not sure.

The property [doesn't trickle down](https://github.com/joepuzzo/informed/blob/master/src/components/Field.js#L35) so it can't (yet?) be used as a fallback in case a `name` property hasn't been passed.

**Comment by fletcher91** [comment]
In theme of the title, I'm trying to create a generic `input` component which just takes a `type` property and sorts itself out (stretching the html spec {a bit} accepting `textarea` and `select` as well).

Some things like [form submit state](https://github.com/joepuzzo/informed/issues/10), field active and blur states, don't seem to be exposed/implemented yet. Haven't come around to testing whether [file handles can be passed as values](https://github.com/react-tools/react-form/issues/207) rather than base64 encoded strings, but [it seems not](https://github.com/joepuzzo/informed/blob/c9988d5a1e874ce46304e8efd7be0014c5c07694/src/ObjectMap/index.js#L59).

Overall API is quite an improvement though 🎉

**Comment by joepuzzo** [comment]
Oh crap i have not added the docs for that.. i knew i was missing somthing. So there is a high order component called asField that allows you to do this. For now check out the form-fields directory to see how i hooked inputs up

**Comment by joepuzzo** [comment]
In the end its pretty straightfoward. Just hook up on blur and onchange to set touched and set value

**Comment by fletcher91** [comment]
Touched is when a field has been modified from its initial value right?

I mean the `true` active state when the user clicks on the input to enter a value, and `false` subsequently when the user clicks/tabs away regardless of the value. ([Material UI example](https://material.io/design/components/text-fields.html#filled-text-field) of the label shifting upward on activation).

The `fieldApi` doesn't contain a `setState` call, but it can obviously be implemented via component state. Though having these options exposed might help in third party extension/theme development.

**Comment by joepuzzo** [comment]
There is no set State at the field level. And touched is when onBlur is called. You can see how its hooked up in my code

**Comment by joepuzzo** [comment]
Im not forgetting about this.. its hight on my priority list to get docs for this out

**Comment by joepuzzo** [comment]
Docs are added. I will add more at a later date but whats there should be enough for now
