### ISSUE TITLE
Reset() not working fine

### ISSUE THREAD

**Issue by hamed-farag** [joepuzzo/informed#90]
Hello,

I have an issue, am trying to use a form in both edit and new mode, base on some condition I want to reset my form in the new mode

I tried to use formApi.reset(), but not work with me so I tried to use formApi.setState({values: {}}); and it worked fine !!

![image](https://user-images.githubusercontent.com/5382471/46236103-9866c380-c37d-11e8-8564-bea21b8ac769.png)

Render Method
![image](https://user-images.githubusercontent.com/5382471/46236114-a74d7600-c37d-11e8-98e0-e48a5fdcc4dd.png)

and finally 
![image](https://user-images.githubusercontent.com/5382471/46236124-b59b9200-c37d-11e8-8c7b-64f0b1765b56.png)

am missed something?

**Comment by joepuzzo** [comment]
hmm when you tried to use `this.formApi.reset()` what was the error you were getting?

**Comment by joepuzzo** [comment]
Updates or can i close?
