### ISSUE TITLE
 MOCHA  Tests completed with 59 failure(s): Invariant Violation: Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by anyexinglu** [joepuzzo/informed#91]
Run `yarn test` directly

![image](https://user-images.githubusercontent.com/8243326/46457899-8e621c00-c7e6-11e8-8cb2-3f3aa07f50b9.png)

**Comment by joepuzzo** [comment]
Hmm can you give me version of npm and node you are running? I just ran on my comp and it works.

**Comment by joepuzzo** [comment]
Also run an `npm ci` then try again

**Comment by joepuzzo** [comment]
updates? can i close?
