### ISSUE TITLE
Select component validation example?

### ISSUE THREAD

**Issue by rhernand3z** [joepuzzo/informed#93]
Hello,

I am trying to look for an example in the documentation that shows the usage of a Select Drop-down being required.
In my scenario I have a select drop down for gender:
```
<Select>
  <option value='male'>male</option>
  <option value='female'>female</option>
  <option value='other'>other</option>
</Select>
```

How can I accomplish this?

**Comment by rhernand3z** [comment]
Hi Joe,

Thanks for the prompt response. In your example, where is this field being required upon submit or where in the UI is there validation errors? In the examples, input fields take a validate prop, I got that working but I don't see an example where a select drop down takes a validation function or is presented as required in the UI. The form can submit without a value selected which I am trying to prohibit. Thanks in advance.

**Comment by joepuzzo** [comment]
Yup so you can pass a validation function to any type of input. For select its on the Select comp. just like all the others. Same interface

**Comment by rhernand3z** [comment]
Thanks that really helped, working through a multi-step form and this library made it very simple. If I publish a tutorial online would it be ok?

**Comment by joepuzzo** [comment]
That is fine yes!
