### ISSUE TITLE
onSubmit doesn't take values as parameter

### ISSUE THREAD

**Issue by saysmaster** [joepuzzo/informed#94]
I have this react component (part of it)

```
onSubmit = v => {
		console && console.log(v);
		this.props.onClose && this.props.onClose(true);
	}
...
<Form initialValues={this.props.initialValues} onSubmit={this.onSubmit}>
	<FormGroup>
		<label htmlFor="firmName-field">{'Firm Name'}</label>
		<Text field="firmName" id="firmName-field" className="form-control" />
	</FormGroup>
	<Button color="primary" type="submit">{'Save'}</Button>
</Form>
```

Reading the documentation for the Form's props I see 

> onSubmit: A function that gets called when form is submitted successfully. The function receives the values as a parameter

But when I submit the form, onSubmit receives an event object and not the values of the form. (v == synthetic event). What am I doing wrong?

**Comment by saysmaster** [comment]
Inspecting more carefully I see that the values of the form are **injected** in the event object! That doesn't seem right.

```
{
	"dispatchConfig": null,
	"_targetInst": null,
	"nativeEvent": null,
	"type": null,
	"target": null,
	"eventPhase": null,
	"bubbles": null,
	"cancelable": null,
	"defaultPrevented": null,
	"isTrusted": null,
	"view": null,
	"detail": null,
	"screenX": null,
	"screenY": null,
	"clientX": null,
	"clientY": null,
	"pageX": null,
	"pageY": null,
	"ctrlKey": null,
	"shiftKey": null,
	"altKey": null,
	"metaKey": null,
	"button": null,
	"buttons": null,
	"_dispatchListeners": null,
	"_dispatchInstances": null,
	"firmName": "test" <-----------------
}
```

It's hard to create a generic form component with this. Doesn't seem right.

I would expect something like `onSubmit(values)` or `onSubmit(event,values)`, not having the values injected to the event.

**Comment by joepuzzo** [comment]
I dont think u have it coded correctly. Would need to see the source code to debug.

**Comment by joepuzzo** [comment]
Also making a code sandbox always helps so i can really take a look at whats going on
