### ISSUE TITLE
How to sync form values with model data

### ISSUE THREAD

**Issue by mrfelton** [joepuzzo/informed#96]
I'm trying to get a form to reflect the state of some model data and stay in sync with it.

For example, I want to load the form with initial values for one model, and then switch out the model and have the form update automatically to show the values from the new model.

I have tried using `initialState` to do this, but it never updates after the first render.

What is the correct way to load new valued into an already rendered form?

**Comment by mrfelton** [comment]
I believe I just figured this out. The solution is to set the special react `key` property on the form. This ensures that if they key changes, the entire form resets with the new data.

See https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key

**Comment by Kaelinator** [comment]
This should be added to the docs. I was trying to solve this for a while!

**Comment by Kaelinator** [comment]
@grudelsud
I would try passing member into the `initialValues` prop on the `<Form>`. Pass in something like `member.id` for the `key` prop, so long as `member.id` is unique for each new set of `initialValue`.

Check out [this file](https://github.com/NPCo/kailee-mills-angels/blob/master/client/src/components/AngelEditForm.js), it might help!

**Comment by grudelsud** [comment]
that worked! thanks @Kaelinator and happy new year!
