### ISSUE TITLE
Cannot easily pass errors from outside the form into it

### ISSUE THREAD

**Issue by JaffParker** [joepuzzo/informed#97]
I have a form that will have some validation errors coming from the parent component. I need to take those errors and pass them to the form state. However, informed doesn't seem to provide such functionality. I could do it via `setError` function, but I would like to be able to achieve that without having to convert my components to stateful components. Is there such a way?

**Comment by joepuzzo** [comment]
Im a little confused. Why cant you use set error ? If you have errors externally then you must already have stuff stored somewhere

**Comment by mrfelton** [comment]
I seem to be unable to call `setError` from within a child render function. Eg:
```javascript
<Form>
  {({ formApi }) => {
    if (formApi && outsideError) {
      formApi.setError('field', outsideError)
    }
    return (... <FormFields /> ...)
  }}
</Form>
```

> index.js:1 Uncaught TypeError: Cannot read property 'config' of undefined
    at Object.eval [as setError] (index.js:1)
    at react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement (ConnectionDetails.js:146)
    at Form.get (index.js:1)
    at Form.render (index.js:1)
    at finishClassComponent (react-dom.development.js:13727)
    at updateClassComponent (react-dom.development.js:13690)
    at beginWork (react-dom.development.js:14489)
    at performUnitOfWork (react-dom.development.js:17014)
    at workLoop (react-dom.development.js:17054)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
(anonymous) @ index.js:1
react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement @ ConnectionDetails.js:146
get @ index.js:1
render @ index.js:1
finishClassComponent @ react-dom.development.js:13727
updateClassComponent @ react-dom.development.js:13690
beginWork @ react-dom.development.js:14489
performUnitOfWork @ react-dom.development.js:17014
workLoop @ react-dom.development.js:17054
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:16366
renderRoot @ react-dom.development.js:17148
performWorkOnRoot @ react-dom.development.js:17993
performWork @ react-dom.development.js:17901
performSyncWork @ react-dom.development.js:17873
requestWork @ react-dom.development.js:17761
scheduleWork @ react-dom.development.js:17566
enqueueSetState @ react-dom.development.js:11695
Component.setState @ react.development.js:373
Wizard._defineProperty @ Wizard.js:172
Wizard._defineProperty @ Wizard.js:196
onSubmit @ ConnectionType.js:54
_callee2$ @ index.js:1
tryCatch @ runtime.js:62
invoke @ runtime.js:288
prototype.(anonymous function) @ runtime.js:114
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
run @ es6.promise.js:75
(anonymous) @ es6.promise.js:92
flush @ _microtask.js:18
_tickCallback @ internal/process/next_tick.js:61
react-dom.development.js:15123 The above error occurred in the <Form> component:
    in Form (created by ForwardRef)
    in StyledComponent (created by Styled(Component))
    in ConnectionDetails (created by Context.Consumer)
    in Step (created by Onboarding)

It seems that the earliest possible place that I can call this is within the forms `onChange` handler

**Comment by mrfelton** [comment]
Actually, I can do this from my `componentDidMount` hook without issue.

```javascript
  componentDidMount() {
    const { startLndHostError } = this.props
    if (startLndHostError) {
      this.formApi.setError('connectionHost', startLndHostError)
    }
  }
```

**Comment by joepuzzo** [comment]
Yeah you dont want to change state in a render method. It is very bad and will lead to many issues

**Comment by FrimJo** [comment]
I want to call `formApi.setValue()` in my `componentDidUpdate()`, is this not recommended? Should we only run set-functions on user inputs like `onChange`, `onClick`etc?

I'm running a calculation when my components updates, and I want to save the result to the form state.

**Comment by joepuzzo** [comment]
You should be able to use the setValue wherever. It’s designed so u can manually set the values

**Comment by joepuzzo** [comment]
Closing as V2 is out and this should work as expected
