### ISSUE TITLE
Doc clarification on notify

### ISSUE THREAD

**Issue by ulybu** [joepuzzo/informed#98]
So I ran into a corner case that _may_ worth a warning in the doc:

I use a custom field `A` that is supposed to notify `B` when its value changes. 

```js
// A's declaration
notify={['B']}
```

I change A's value using the formApi

```js
formApi.setValue('A', 'newValue');
```

It happens that setting A's value that way doesn't triggers B's validation. Indeed I need to add `validateOnChange` :

```js
// A's declaration
notify={['B']}
notifyOnChange={true}
```

This behavior seems to be expected:  https://github.com/joepuzzo/informed/blob/7e0c54b048f53775ad55557c6000917d0374ef21/src/Controller/FormController.js#L127

So, the way to understand the notification system is not `Will notify other field(s) when its value changes` but more `Will notify other field(s) when its value go through validation (successful or nor)`.

Not that I particularly disagree with the behavior, but it can lead to counter-intuitive situation. Because A's value has indeed changed `formApi.getValue('A') // "newValue"`, I think most people would expect that B also take in account that modification and trigger its own validation.

Thoughts ?

**Comment by joepuzzo** [comment]
I agree i maybe could be more clear in the docs on this one. Its impotant to put the validateOnChange because without it the notify would do nothing

**Comment by Jakobo** [comment]
Just helping out with the docs as I use more of Informed on a project. This is what's in the Storybook right now:

>Sometimes when validating you may need to notify other fields about your changes. A great example of this is when you have a password and confirm password field, and when one changes you want the other to validate as well. To achieve this, `informed` allows you to pass notify to an input with an array of fields to notify.

Should we just add something like this?

> To avoid excessive message passing, `informed` only notifies other fields of changes as part of the validation process. If you'd like to control when validation (and thus, notification) occur, you can pass to your field the `validateOnChange` and `validateOnBlur` props.

**Comment by joepuzzo** [comment]
Yeah this sounds helpful
