### ISSUE TITLE
How can I get the name of the field currently being validated from a validate handler

### ISSUE THREAD

**Issue by mrfelton** [joepuzzo/informed#99]
Validation handlers get passed the value of the field that is being validated. But how can you know which field that value came from?

Use case is to use `yup` to define a validation schema for the form and have a single validation method that is able to validate any form value that is thrown at it using the defined schema.

I'd like to avoid having to create a custom `validate` method for every single form field.

Here is a simplified example:

```javascript
const schema = yup.object().shape({
      field1: yup.boolean(),
      field2: yup.number()
})

validate(value) {
    // schema.validate(value)
    // FIXME: How do I know what field is being validated here? I only have access to the value.
}

...

{<Text field="field1" validate={validate}/>}
{<Text field="field2" validate={validate}/>}
```

**Comment by mrfelton** [comment]
Another example use case would be if I wanted to include the name of the field in the error message returned by the validator.

**Comment by mrfelton** [comment]
Here is a solution that works, but it feels like this is something that would be better handled by informed nativly.

```
<Text field="name" validate={this.validate.bind(this, 'name')}/>
```

Then you can have a validator method like:

```
  validate(field, value, values) {
    console.log('validate this....', this)
    console.log('validate field....', field)
    console.log('validate value....', value)
    console.log('validate values....', values)
  }
```

Now, the field name is available within `field` - meaning that I can reuse this validator across multiple fields.

**Comment by joepuzzo** [comment]
You should know what the field name is in your balidation function for that field.. when it comes to wanting to write a generic function for multiple fieds what u did above is fine

**Comment by joepuzzo** [comment]
Are we good with this? Can I close?

**Comment by mrfelton** [comment]
Yes, I think that's ok @joepuzzo . I still sorta feel that it would make sense for that information to be readily available without having to take manual steps to pass it in as per my example, but the workaround is ok so I'm good for you to close this one out. Thanks.
